# Ingested from Rhea. The spine follows the carbon skeleton from
# 1,8-diazacyclotetradecane-2,9-dione to adipate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-8-diazacyclotetradecane-to-adipate "1,8-diazacyclotetradecane… to adipate" {
  spacing 250

  spine at 0,0 {
    1_8_diazacyclotetradecane_2_9_dione
    <-> ec_3_5_2_12 [3.5.2.12] +h2o
    n_6_aminohexanoyl_6_aminohexanoic_acid
    <-> ec_3_5_1_46 [3.5.1.46] +h2o
    6_aminohexanoic_acid
    <-> ec_2_6_1_116 [2.6.1.116] +akg -glutamate
    6_oxohexanoate
    <-> ec_1_2_1_63 [1.2.1.63] +nadp +h2o -nadph -hplus
    adipate
    <-> . +glutaryl_coa -glutarate
    adipoyl_coa
    <-> . +h2o -coa -hplus
    adipate
  }

  branch from 6_oxohexanoate side left {
    6_oxohexanoate
    <-> ec_3_7_1_11 [3.7.1.11] +h2o +hplus
    cyclohexane_1_2_dione
  }

  branch from 6_oxohexanoate side right {
    6_oxohexanoate
    <-> . +nadp +nadph +hplus
    6_hydroxyhexanoate
  }

  branch from glutamate side left {
    glutamate
    <-> ec_2_6_1_72 [2.6.1.72] +d_4_hydroxyphenylglycine +akg
    4_hydroxyphenylglyoxylate
  }

  branch from glutamate side right {
    glutamate
    <-> ec_2_6_1_52 [2.6.1.52] +4_phosphonatooxy_l_threonine +akg
    r_3_hydroxy_2_oxo_4_phosphonatoooxy_butanoate
  }

  branch from adipoyl_coa side left {
    adipoyl_coa
    <-> . +coa +acetyl_coa
    3_oxooctanedioyl_coa
  }
}
