# Ingested from Rhea. The spine follows the carbon skeleton from
# 1-acyl-sn-glycerol to 1-O-acyl-sn-glycero-3-phosphocholine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-acyl-sn-glycerol-to-1-o-acyl-sn-glycero-3-pho "1-acyl-sn-glycerol to 1-O-acyl-sn-glycero-3-pho…" {
  spacing 152

  spine at 0,0 {
    1_acyl_sn_glycerol
    <-> . +phosphatidylcholine -1_o_acyl_sn_glycero_3_phosphocholine
    1_3_diglyceride
    <-> . +1_acyl_sn_glycero_3_phospho_1d_myo_inositol +1_o_acyl_sn_glycero_3_phosphocholine -choline_alfoscerate
    1_phosphatidyl_1d_myo_inositol
    <-> . +1_acyl_sn_glycero_3_phosphoethanolamine +choline_alfoscerate -1_o_acyl_sn_glycero_3_phosphocholine
    2_ammonioethyl_2r_2_3_dihydroxypropyl_phosphate
  }

  branch from 1_phosphatidyl_1d_myo_inositol side left {
    1_phosphatidyl_1d_myo_inositol
    <-> . +1_acyl_sn_glycero_3_phospho_1d_myo_inositol +coa
    acyl_coa
  }
}
