# Ingested from Rhea. The spine follows the carbon skeleton from
# 1-acyl-2-oleoyl-sn-glycero-3-phosphoserine(1−) to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-acyl-2-oleoyl-sn-glycer-to-h2o "1-acyl-2-oleoyl-sn-glycer… to H2O" {
  spacing 188

  spine at 0,0 {
    1_acyl_2_oleoyl_sn_glycero_3_phosphoserine
    <-> . +h2o -fatty-acid -hplus
    2_oleoyl_sn_glycero_3_phosphoserine
    <-> . +oleoyl_coa -coa
    1_2_dioleoyl_sn_glycero_3_phospho_l_serine
    <-> . +h2o -oleate -hplus
    1_oleoyl_sn_glycero_3_phosphoserine
    <-> . +linoleoyl_coa -coa
    1_oleoyl_2_linoleoyl_sn_glycero_3_phospho_l_seri
    <-> ec_3_6_3_1 [3.6.3.1] +h +adp +phosphate -1_oleoyl_2_linoleoyl_sn_glycero_3_phospho_l_seri -h2o
    atp
  }

  branch from 1_oleoyl_sn_glycero_3_phosphoserine side left {
    1_oleoyl_sn_glycero_3_phosphoserine
    <-> . +arachidonoyl_coa +coa
    1_oleoyl_2_arachidonoyl_sn_glycero_3_phospho_l_s
  }

  branch from 1_oleoyl_sn_glycero_3_phosphoserine side right {
    1_oleoyl_sn_glycero_3_phosphoserine
    <-> . +stearoyl_coa +coa
    1_oleoyl_2_stearoyl_sn_glycero_3_phospho_l_serin
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    validamycin_a
  }

  branch from atp side right {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    o_phosphoviomycin
  }

  branch from h2o side left {
    h2o
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +atp
    viomycin
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_47 [3.6.3.47] +h +adp +phosphate +atp
    docosanoyl_coa
  }
}
