# Ingested from Rhea. The spine follows the carbon skeleton from
# 1-(all-cis-docosa-7,10,13,16-tetraenoyl)glycerol to (2E,11Z,14Z,17Z,20Z)-hexacosapentaenoyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-all-cis-docosa-7-10-13-to-2e-11z-14z-17z-20z-h "1-(all-cis-docosa-7,10,13… to (2E,11Z,14Z,17Z,20Z)-hexa…" {
  spacing 152

  spine at 0,0 {
    1_all_cis_docosa_7_10_13_16_tetraenoyl_glycerol
    <-> . +h2o -glycerol -hplus
    all_cis_docosa_7_10_13_16_tetraenoate
    <-> . +atp +coa -amp -ppi
    7z_10z_13z_16z_docosatetraenoyl_coa
    <-> . +malonyl-coa +hplus -co2 -coa
    9z_12z_15z_18z_3_oxotetracosatetraenoyl_coa
    <-> . +nadph +hplus -nadp
    3r_9z_12z_15z_18z_3_hydroxytetracosatetraenoyl
    <-> . -h2o
    2e_9z_12z_15z_18z_tetracosapentaenoyl_coa
    <-> . +nadph +hplus -nadp
    9z_12z_15z_18z_tetracosatetraenoyl_coa
    <-> . +malonyl-coa +hplus -co2 -coa
    11z_14z_17z_20z_3_oxohexacosatetraenoyl_coa
    <-> . +nadph +hplus -nadp
    3r_11z_14z_17z_20z_3_hydroxyhexacosatetraenoyl
    <-> . -h2o
    2e_11z_14z_17z_20z_hexacosapentaenoyl_coa
  }

  branch from 7z_10z_13z_16z_docosatetraenoyl_coa side left {
    7z_10z_13z_16z_docosatetraenoyl_coa
    <-> . +fe2 +o2 +hplus +iron +h2o
    7z_10z_13z_16z_19z_docosapentaenoyl_coa
  }

  branch from ppi side right {
    ppi
    <-> ec_4_2_3_102 [4.2.3.102] +fpp
    sesquithujene
  }

  branch from 2e_11z_14z_17z_20z_hexacosapentaenoyl_coa side left {
    2e_11z_14z_17z_20z_hexacosapentaenoyl_coa
    <-> . +nadph +hplus +nadp
    11z_14z_17z_20z_hexacosatetraenoyl_coa
  }
}
