# Ingested from Rhea. The spine follows the carbon skeleton from
# 1-palmitoyl-2-acyl-sn-glycero-3-phosphoethanolamine zwitterion to 1-stearoyl-2-acyl-sn-glycero-3-phosphoethanolamine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-palmitoyl-2-acyl-sn-gly-to-1-stearoyl-2-acyl-s "1-palmitoyl-2-acyl-sn-gly… to 1-stearoyl-2-acyl-sn-glyc…" {
  spacing 152

  spine at 0,0 {
    1_palmitoyl_2_acyl_sn_glycero_3_phosphoethanolam
    <-> . +h2o -palmitate -hplus
    2_acyl_sn_glycero_3_phosphoethanolamine
    <-> . +stearoyl_coa -coa
    1_stearoyl_2_acyl_sn_glycero_3_phosphoethanolami
  }
}
