# Ingested from Rhea. The spine follows the carbon skeleton from
# 1-stearoyl-2-arachidonoyl-sn-glycero-3-phospho-1D-myo-inositol 4-phosphate(3−) to 1-stearoyl-2-arachidonoyl-sn-glycero-3-phospho-(1D-myo-inositol 3,4,5-triphosphate)(7−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-stearoyl-2-arachidonoyl-to-1-stearoyl-2-arachi "1-stearoyl-2-arachidonoyl… to 1-stearoyl-2-arachidonoyl…" {
  spacing 152

  spine at 0,0 {
    1_stearoyl_2_arachidonoyl_sn_glycero_3_phospho_1
    <-> . +atp -adp -hplus
    1_stearoyl_2_arachidonoyl_sn_glycero_3_phospho_1
    <-> . +atp -adp -hplus
    1_stearoyl_2_arachidonoyl_sn_glycero_3_phospho_1
  }
}
