# Ingested from Rhea. The spine follows the carbon skeleton from
# 1-stearoyl-2-myristoyl-sn-glycero-3-phosphocholine to 1-stearoyl-2-oleoyl-sn-glycero-3-phosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1-stearoyl-2-myristoyl-sn-to-1-stearoyl-2-oleoyl "1-stearoyl-2-myristoyl-sn… to 1-stearoyl-2-oleoyl-sn-gl…" {
  spacing 182

  spine at 0,0 {
    1_stearoyl_2_myristoyl_sn_glycero_3_phosphocholi
    <-> . +h2o -tetradecanoate -hplus
    1_stearoyl_sn_glycero_3_phosphocholine
    <-> . +h2o -choline -hplus
    1_stearoyl_sn_glycero_3_phosphate
    <-> . +oleoyl_coa -coa
    1_stearoyl_2_oleoyl_sn_glycero_3_phosphate
    <-> . +h2o -pi
    1_octadecanoyl_2_9z_octadecenoyl_sn_glycerol
    <-> . +atp -adp -hplus
    1_stearoyl_2_oleoyl_sn_glycero_3_phosphate
  }

  branch from tetradecanoate side left {
    tetradecanoate
    <-> . +1_2_di_o_myristoyl_sn_glycero_3_phosphocholine +h2o +hplus
    1_myristoyl_sn_glycero_3_phosphocholine
  }

  branch from tetradecanoate side right {
    tetradecanoate
    <-> ec_1_13_11_92 [1.13.11.92] +o2
    2r_2_hydroperoxytetradecanoate
  }

  branch from 1_stearoyl_sn_glycero_3_phosphate side left {
    1_stearoyl_sn_glycero_3_phosphate
    <-> . +h2o +pi
    1_stearoyl_sn_glycerol
  }

  branch from 1_stearoyl_sn_glycero_3_phosphate side right {
    1_stearoyl_sn_glycero_3_phosphate
    <-> ec_3_6_3_1 [3.6.3.1] +h +adp +phosphate +h2o
    atp
  }

  branch from 1_stearoyl_2_oleoyl_sn_glycero_3_phosphate side left {
    1_stearoyl_2_oleoyl_sn_glycero_3_phosphate
    <-> . +ctp +hplus +ppi
    cdp_1_stearoyl_2_oleoyl_sn_glycerol
  }
}
