# Ingested from Rhea. The spine follows the carbon skeleton from
# 14-demethyllanosterol to 5α-cholest-8-en-3β-ol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 14-demethyllanosterol-to-5-cholest-8-en-3-ol "14-demethyllanosterol to 5α-cholest-8-en-3β-ol" {
  spacing 206

  spine at 0,0 {
    tmas
    <-> . +nadph +hplus -nadp
    4_4_dimethyl_5_cholest_8_en_3_ol
    <-> . +fe2 +o2 +hplus -iron -h2o
    4_hydroxymethyl_4_methyl_5_8_cholesten_3_ol
    <-> . +fe2 +o2 +hplus -iron -h2o
    4_formyl_4_methyl_5_8_cholesten_3_ol
    <-> . +fe2 +o2 +hplus -iron -h2o
    3_hydroxy_4_methyl_5_cholest_8_ene_4_carboxylate
    <-> . +nadp -co2 -nadph
    4_methyl_5_cholest_8_en_3_one
    <-> . +nadph +hplus -nadp
    4_methyl_5_cholest_8_en_3_ol
    <-> . +fe2 +o2 +hplus -iron -h2o
    4_hydroxymethyl_5_cholest_8_en_3_ol
    <-> . +fe2 +o2 +hplus -iron -h2o
    4_formyl_5_cholest_8_en_3_ol
    <-> . +fe2 +o2 +hplus -iron -h2o
    3_hydroxy_5_cholest_8_ene_4_carboxylate
    <-> . +nadp -co2 -nadph
    5_cholest_8_en_3_one
    <-> . +nadph +hplus -nadp
    zymostenol
  }

  branch from 4_hydroxymethyl_4_methyl_5_8_cholesten_3_ol side left {
    4_hydroxymethyl_4_methyl_5_8_cholesten_3_ol
    <-> ec_1_14_13_72 [1.14.13.72] +nadh +h +3beta_4alpha_5alpha_4_4_dimethylcholest_8_en_3 +o2 +h2o
    nad
  }

  branch from 4_hydroxymethyl_4_methyl_5_8_cholesten_3_ol side right {
    4_hydroxymethyl_4_methyl_5_8_cholesten_3_ol
    <-> ec_1_14_13_72 [1.14.13.72] +nadh +h +o2 +4_formyl_4_methyl_5_8_cholesten_3_ol +nad
    h2o
  }

  branch from 3_hydroxy_4_methyl_5_cholest_8_ene_4_carboxylate side left {
    3_hydroxy_4_methyl_5_cholest_8_ene_4_carboxylate
    <-> ec_1_14_13_72 [1.14.13.72] +h +3beta_4alpha_5alpha_4_4_dimethylcholest_8_en_3 +o2 +nadph +h2o
    nadp
  }

  branch from 3_hydroxy_4_methyl_5_cholest_8_ene_4_carboxylate side right {
    3_hydroxy_4_methyl_5_cholest_8_ene_4_carboxylate
    <-> ec_1_14_13_72 [1.14.13.72] +h +3beta_4alpha_5alpha_4_4_dimethylcholest_8_en_3 +o2 +nad +h2o
    nadh
  }

  branch from 4_methyl_5_cholest_8_en_3_ol side left {
    4_methyl_5_cholest_8_en_3_ol
    <-> ec_1_3_1_72 [1.3.1.72] +h +nadph +nadp
    3s_4s_5s_10s_13r_4_10_13_trimethyl_17_2r_6_meth
  }

  branch from 4_methyl_5_cholest_8_en_3_ol side right {
    4_methyl_5_cholest_8_en_3_ol
    <-> .
    4_methylcholesta_8_14_en_3_ol
  }

  branch from 4_hydroxymethyl_5_cholest_8_en_3_ol side left {
    4_hydroxymethyl_5_cholest_8_en_3_ol
    <-> ec_1_14_13_72 [1.14.13.72] +nadh +o2 +4_methyl_5_cholest_8_en_3_ol +nad +h2o
    h
  }

  branch from 4_hydroxymethyl_5_cholest_8_en_3_ol side right {
    4_hydroxymethyl_5_cholest_8_en_3_ol
    <-> ec_1_14_13_72 [1.14.13.72] +4_formyl_5_cholest_8_en_3_ol +nadp +h2o +h +nadph
    o2
  }

  branch from 4_formyl_5_cholest_8_en_3_ol side left {
    4_formyl_5_cholest_8_en_3_ol
    <-> ec_1_14_13_72 [1.14.13.72] +o2 +nadp +3_hydroxy_5_cholest_8_ene_4_carboxylate +h2o
    nadph
  }
}
