# Ingested from Rhea. The spine follows the carbon skeleton from
# 17-O-acetylnorajmaline(1+) to D-glucopyranose; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 17-o-acetylnorajmaline-to-d-glucopyranose-12320 "17-O-acetylnorajmaline to D-glucopyranose" {
  spacing 254

  spine at 0,0 {
    17_o_acetylnorajmaline
    <-> ec_1_3_1_73 [1.3.1.73] +nadp -nadph -hplus
    1_2_dihydrovomilenine
    <-> ec_1_5_1_32 [1.5.1.32] +nadp -nadph -hplus
    vomilenine
    <-> ec_2_4_1_219 [2.4.1.219] +udp_d_glucose -udp -hplus
    raucaffricine
    <-> ec_3_2_1_125 [3.2.1.125] +h2o -glucose
    vomilenine
  }

  branch from vomilenine side left {
    vomilenine
    <-> . +nadp +nadph +hplus
    20s_19_20_dihydrovomilenine
  }

  branch from glucose side right {
    glucose
    <-> ec_1_1_3_10 [1.1.3.10] +o2 +h2o2
    2_dehydro_d_glucopyranose
  }

  branch from glucose side left {
    glucose
    <-> ec_2_4_1_230 [2.4.1.230] +d_glcp_1_2_d_glcp +pi
    d_glucose_1_phosphate
  }

  branch from udp_d_glucose side right {
    udp_d_glucose
    <-> ec_2_4_1_210 [2.4.1.210] +limonin +h2o +udp +hplus
    limonin_17_d_glucoside
  }

  branch from udp_d_glucose side left {
    udp_d_glucose
    <-> ec_2_4_1_127 [2.4.1.127] +menthol +udp +hplus
    menthyl_d_glucoside
  }

  branch from glucose side right {
    glucose
    <-> ec_2_7_1_147 [2.7.1.147] +adp +amp +hplus
    g6p
  }

  branch from glucose side left {
    glucose
    <-> ec_3_2_1_104 [3.2.1.104] +cholesteryl_d_glucoside +h2o
    cholesterol
  }
}
