# Ingested from Rhea. The spine follows the carbon skeleton from
# (1R,6R)-2-(3-carboxylatopropanoyl)-6-hydroxycyclohexa-2,4-diene-1-carboxylate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1r-6r-2-3-carboxylatop-to-h2o "(1R,6R)-2-(3-carboxylatop… to H2O" {
  spacing 292

  spine at 0,0 {
    1r_6r_2_3_carboxylatopropanoyl_6_hydroxycyclohe
    <-> ec_4_2_1_113 [4.2.1.113] -h2o
    2_succinatobenzoate
    <-> ec_6_2_1_26 [6.2.1.26] +atp +coa -amp -ppi
    4_2_carboxyphenyl_4_oxobutanoyl_coa
    <-> ec_4_1_3_36 [4.1.3.36] +hplus -h2o
    1_4_dihydroxy_2_naphthoyl_coa
    <-> ec_3_1_2_28 [3.1.2.28] +h2o -coa -hplus
    1_4_dihydroxy_2_naphthoate
    <-> ec_2_5_1_74 [2.5.1.74] +all_trans_octaprenyl_diphosphate +hplus -co2 -ppi
    2_demethylmenaquinol_8
    <-> . +thiosulfate -h -2_demethylmenaquinone_8 -sulfite
    hydrogen_sulfide
    <-> ec_1_14_14_1 [1.14.14.1] +h +paraoxon -h2o
    parathion
  }

  branch from ppi side left {
    ppi
    <-> . +gtp +atp
    3_2_cgamp
  }

  branch from ppi side right {
    ppi
    <-> . +gtp +atp
    pppa_2_5_pg
  }

  branch from h side left {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +carbomycin +phosphate +carbomycin +h2o
    atp
  }

  branch from h side right {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    daunorubicin
  }

  branch from h2o side left {
    h2o
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +atp
    premithramycinone
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +atp
    doxorubicin
  }
}
