# Ingested from Rhea. The spine follows the carbon skeleton from
# (1R,6R)-2-(3-carboxylatopropanoyl)-6-hydroxycyclohexa-2,4-diene-1-carboxylate to S-adenosyl-L-homocysteine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 1r-6r-2-3-carboxylatop-to-s-adenosyl-l-homocyst "(1R,6R)-2-(3-carboxylatop… to S-adenosyl-L-homocysteine" {
  spacing 256

  spine at 0,0 {
    1r_6r_2_3_carboxylatopropanoyl_6_hydroxycyclohe
    <-> ec_4_2_1_113 [4.2.1.113] -h2o
    2_succinatobenzoate
    <-> ec_6_2_1_26 [6.2.1.26] +atp +coa -amp -ppi
    4_2_carboxyphenyl_4_oxobutanoyl_coa
    <-> ec_4_1_3_36 [4.1.3.36] +hplus -h2o
    1_4_dihydroxy_2_naphthoyl_coa
    <-> ec_3_1_2_28 [3.1.2.28] +h2o -coa -hplus
    1_4_dihydroxy_2_naphthoate
    <-> ec_2_5_1_74 [2.5.1.74] +all_trans_octaprenyl_diphosphate +hplus -co2 -ppi
    2_demethylmenaquinol_8
    <-> ec_2_1_1_163 [2.1.1.163] +sam -sah -hplus
    menaquinol_8
  }
}
