# Ingested from Rhea. The spine follows the carbon skeleton from
# 2,3-dihydroxy-N-benzoylserine dimer to NADPH; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-3-dihydroxy-n-benzoylse-to-nadph-null "2,3-dihydroxy-N-benzoylse… to NADPH" {
  spacing 308

  spine at 0,0 {
    2_3_dihydroxy_n_benzoylserine_dimer
    <-> . +h2o -n_2_3_dihydroxybenzoyl_l_serine
    h
    <-> ec_6_3_2_14 [6.3.2.14] +adp +n_2_3_dihydroxybenzoyl_l_serine +phosphate -2_3_dihydroxybenzoate -l_serine
    atp
    <-> . +nadh +h +2_3_dihydroxybenzoate +o2 -1_2_3_trihydroxybenzene -nad -h2o
    co2
    <-> . +1_2_3_trihydroxybenzene +nadp +h2o -resorcinol -o2 -nadph
    h
  }

  branch from h side left {
    h
    <-> ec_1_14_13_88 [1.14.13.88] +o2 +2s_naringenin +nadph +nadp +h2o
    2s_dihydrotricetin
  }

  branch from h side right {
    h
    <-> ec_4_1_1_77 [4.1.1.77] +2e_2_hydroxypenta_2_4_dienoate +co2
    4_oxalocrotonate
  }

  branch from atp side left {
    atp
    <-> . +h +adp +phosphate +h2o
    5_6_eet
  }

  branch from atp side right {
    atp
    <-> . +h +adp +phosphate +h2o
    8_9_epoxy_5z_11z_14z_eicosatrienoate
  }

  branch from l_serine side left {
    l_serine
    <-> . +l_cysteine +l_arginine +h2o
    arginyl_cystinyl_serine
  }

  branch from l_serine side right {
    l_serine
    <-> . +l_arginine +h2o
    arginyl_seryl_serine
  }

  branch from co2 side left {
    co2
    <-> ec_4_1_1_68 [4.1.1.68] +cis_2_oxohept_3_enedioic_acid
    5_carboxy_2_oxohept_3_enedioate
  }

  branch from co2 side right {
    co2
    <-> ec_4_1_1_96 [4.1.1.96] +spermidine +h
    carboxyspermidine
  }

  branch from 1_2_3_trihydroxybenzene side left {
    1_2_3_trihydroxybenzene
    <-> ec_1_13_11_35 [1.13.11.35] +h +o2
    z_5_oxohex_2_enedioate
  }

  branch from 1_2_3_trihydroxybenzene side right {
    1_2_3_trihydroxybenzene
    <-> ec_1_14_13_236 [1.14.13.236] +nadh +h +o2 +nad +h2o
    catechol
  }

  branch from nad side left {
    nad
    <-> . +nadh +3_oxotetracosanoyl_coa +h
    3_hydroxytetracosanoyl_coa
  }

  branch from nad side right {
    nad
    <-> . +nadh +3_oxodocosanoyl_coa +h
    3_hydroxydocosanoyl_coa
  }

  branch from h2o side left {
    h2o
    <-> . +three_disacharide_linked_murein_units_tetrapepti
    three_disacharide_linked_murein_units_tetrapepti
  }

  branch from h2o side right {
    h2o
    <-> . +two_disacharide_linked_murein_units_pentapeptide
    two_linked_disacharide_pentapeptide_and_tripepti
  }

  branch from resorcinol side left {
    resorcinol
    <-> ec_1_10_3_2 [1.10.3.2] +h2o +o2
    3_benzosemiquinone
  }

  branch from o2 side right {
    o2
    <-> ec_1_14_16_1 [1.14.16.1] +5_6_7_8_tetrahydrobiopterin +l_tryptophan +5_hydroxy_l_tryptophan
    4as_6r_4a_hydroxy_l_erythro_5_6_7_8_tetrahydrob
  }

  branch from o2 side left {
    o2
    <-> . +4_hydroxy_3_all_trans_hexaprenyl_benzoate
    3_4_dihydroxy_5_all_trans_hexaprenyl_benzoate
  }

  branch from nadph side right {
    nadph
    <-> ec_1_3_1_54 [1.3.1.54] +h +cobalt_precorrin_6 +nadp
    co_precorrin_6b
  }

  branch from nadph side left {
    nadph
    <-> ec_1_5_1_30 [1.5.1.30] +h +riboflavin +nadp
    4a_5_dihydroriboflavin
  }

  branch from h2o side right {
    h2o
    <-> . +2_4_dihydroxy_2_heptenedioic_acid
    cis_2_oxohept_3_enedioic_acid
  }

  branch from h2o side left {
    h2o
    <-> . +d_alanine +n_acetyl_d_glucosamine_anhydrous_n_acetylmuramyl
    n_acetyl_d_glucosamine_anhydrous_n_acetylmuramyl
  }

  branch from h side right {
    h
    <-> ec_1_13_11_2 [1.13.11.2] +catechol +o2
    2e_4z_2_hydroxy_6_oxohexa_2_4_dienoate
  }

  branch from h side left {
    h
    <-> ec_3_6_1_26 [3.6.1.26] +cmp +1_2_ditetradec_7_enoyl_sn_glycerol_3_phosphate +h2o
    cdp_1_2_ditetradec_7_enoylglycerol
  }

  branch from adp side right {
    adp
    <-> . +h +phosphate +atp +h2o
    11s_12r_eet
  }

  branch from adp side left {
    adp
    <-> . +h +phosphate +atp +h2o
    14_15_epoxy_5z_8z_11z_eicosatrienoate
  }

  branch from phosphate side right {
    phosphate
    <-> . +h +adp +atp +h2o
    9r_10s_9_10_epome
  }
}
