# Ingested from Rhea. The spine follows the carbon skeleton from
# 2,7,10,13,16-docosapentenoylcoa to FAD; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-7-10-13-16-docosapenten-to-fad "2,7,10,13,16-docosapenten… to FAD" {
  spacing 176

  spine at 0,0 {
    2_7_10_13_16_docosapentenoylcoa
    <-> .
    3_7_10_13_16_docosapentenoylcoa
    <-> . +nadp -h -nadph
    2_4_7_10_13_16_docosahexenoylcoa
    <-> . +fadh2 +h -fad
    4z_7z_10z_13z_16z_docosapentaenoyl_coa
    <-> . +o2 -2_4_7_10_13_16_docosahexenoyl_coenzyme_a
    h2o2
    <-> . +fadh2 +h +2_4_7_10_13_16_docosahexenoyl_coenzyme_a -fad
    4z_7z_10z_13z_16z_docosapentaenoyl_coa
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    lovastatin_hydroxyacid_form
  }

  branch from h side right {
    h
    <-> . +l_leucine +l_lysine +l_arginine +h2o
    lysyl_arginyl_leucine
  }

  branch from 4z_7z_10z_13z_16z_docosapentaenoyl_coa side left {
    4z_7z_10z_13z_16z_docosapentaenoyl_coa
    <-> . +h +adp +phosphate +h2o
    atp
  }

  branch from 4z_7z_10z_13z_16z_docosapentaenoyl_coa side right {
    4z_7z_10z_13z_16z_docosapentaenoyl_coa
    <-> . +r_carnitine +4e_7e_10e_13e_16e_docosapentaenoylcarnitine
    coa
  }
}
