# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-acyl-6-(α-D-mannosyl-(1→4)-α-D-glucosaminyl)-1-(1-radyl,2-acyl-sn-glycero-3-phospho)-1D-myo-inositol zwitterion to N-retinylidene-N-retinylphosphatidylethanolamine betaine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-acyl-6-d-mannosyl-1-to-n-retinylidene-n-retiny "2-acyl-6-(α-D-mannosyl-(1… to N-retinylidene-N-retinylp…" {
  spacing 172

  spine at 0,0 {
    2_acyl_6_d_mannosyl_1_4_d_glucosaminyl_1_1_radyl
    <-> . +1_2_diacyl_sn_glycero_3_phosphoethanolamine -dag
    2_acyl_6_2_phosphoethanolamine_d_mannosyl_1_4_d
    <-> ec_2_7_1_174 [2.7.1.174] +dag +ctp -cdp -hplus
    1_2_diacyl_sn_glycerol_3_phosphate
    <-> . +n_retinylidene_n_retinylethanolamine +hplus -h2o
    n_retinylidene_n_retinylphosphatidylethanolamine
  }

  branch from dag side left {
    dag
    <-> . +n_hexacosanoylsphinganine +1_phosphatidyl_1d_myo_inositol
    ins_1_p_cer_d18_0_26_0
  }

  branch from cdp side right {
    cdp
    <-> ec_2_7_1_40 [2.7.1.40] +ctp +pyruvate +hplus
    phosphonatoenolpyruvate
  }
}
