# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-acyl-6-[α-D-mannosyl-(1→2)-α-D-mannosyl-(1→2)-α-D-mannosyl-(1→6)-2-phosphoethanolamine-α-D-mannosyl-(1→4)-α-D-glucosaminyl]-1-(1-radyl,2-acyl-sn-glycero-3-phospho)-1D-myo-inositol zwitterion to γ-L-glutamylethanolamide zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-acyl-6-d-mannosyl-1-to-l-glutamylethanolamide "2-acyl-6-[α-D-mannosyl-(1… to γ-L-glutamylethanolamide" {
  spacing 152

  spine at 0,0 {
    2_acyl_6_d_mannosyl_1_2_d_mannosyl_1_2_d_mannosy
    <-> . +1_2_diacyl_sn_glycero_3_phosphoethanolamine -dag
    2_acyl_6_d_mannosyl_1_2_6_phosphoethanolamine_d
    <-> . +dag +phosphatidylcholine -1_o_acyl_sn_glycero_3_phosphocholine
    triacyl_sn_glycerol
    <-> . +h2o -fatty-acid -hplus
    1_3_diacyl_sn_glycerol
    <-> . +h2o -fatty-acid -hplus
    1_acyl_sn_glycerol
    <-> . +1_2_diacyl_sn_glycero_3_phosphoethanolamine -dag
    1_acyl_sn_glycero_3_phosphoethanolamine
    <-> . +h2o -fatty-acid -hplus
    2_ammonioethyl_2r_2_3_dihydroxypropyl_phosphate
    <-> . +h2o -sn_glycerol_3_phosphate -hplus
    ethanolaminium
    <-> . +glutamate +atp -adp -pi -hplus
    l_glutamylethanolamide
  }

  branch from dag side left {
    dag
    <-> . +dihydroceramide +1_2_diacyl_sn_glycero_3_phosphoethanolamine
    n_acylsphinganine_1_phosphoethanolamine
  }

  branch from 1_o_acyl_sn_glycero_3_phosphocholine side right {
    1_o_acyl_sn_glycero_3_phosphocholine
    <-> . +1_2_diacyl_sn_glycero_3_phospho_1_sn_glycerol +phosphatidylcholine
    1_acyl_sn_glycero_3_phospho_1_sn_glycerol
  }

  branch from 1_3_diacyl_sn_glycerol side left {
    1_3_diacyl_sn_glycerol
    <-> . +1_acyl_sn_glycerol +phosphatidylcholine
    acyl_sn_glycero_3_phosphocholine
  }

  branch from fatty-acid side right {
    fatty-acid
    <-> . +h2o +1_acyl_sn_glycero_3_phospho_1_sn_glycerol +hplus
    1_2_diacyl_sn_glycero_3_phospho_1_sn_glycerol
  }
}
