# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-hydroxy-3-oxobutyl phosphate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-hydroxy-3-oxobutyl-to-h2o "2-hydroxy-3-oxobutyl… to H2O" {
  spacing 220

  spine at 0,0 {
    2_hydroxy_3_oxobutyl_phosphate
    <-> ec_2_5_1_78 [2.5.1.78] +5_amino_6_d_ribitylamino_uracil -h -phosphate -h2o
    6_7_dimethyl_8_1_d_ribityl_lumazine
    <-> ec_2_5_1_9 [2.5.1.9] -h -riboflavin
    5_amino_6_d_ribitylamino_uracil
    <-> . +h +riboflavin +adp +phosphate -atp -h2o
    riboflavin
  }
}
