# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-[hydroperoxy-(4-glucosyl-hydroxyphenyl)methyl]-6-hydroxy-1-benzofuran-3-one to S-adenosyl-L-homocysteine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-hydroperoxy-4-glucosy-to-s-adenosyl-l-homocyst "2-[hydroperoxy-(4-glucosy… to S-adenosyl-L-homocysteine" {
  spacing 276

  spine at 0,0 {
    2_hydroperoxy_4_glucosyl_hydroxyphenyl_methyl_6
    <-> . +h2o -h2o2
    neoisoliquiritin
    <-> . +udp +h -udp_alpha_d_glucose
    isoliquiritigenin
    <-> .
    liquiritigenin
    <-> . +fmnh2 +o2 -fmn -h2o_chebi_15377 -hplus
    licodione
    <-> ec_2_1_1_65 [2.1.1.65] +sam -sah -hplus
    2_o_methyllicodione
  }

  branch from h2o2 side left {
    h2o2
    <-> ec_1_11_1_11 [1.11.1.11] +l_dehydroascorbic_acid +h2o +h
    l_ascorbate
  }

  branch from h2o2 side right {
    h2o2
    <-> . +16_hydroxyhexadecanoate +o2_mnxm735438
    16_oxohexadecanoate
  }

  branch from udp_alpha_d_glucose side left {
    udp_alpha_d_glucose
    <-> . +udp +aloenin +h
    6_2_4_dihydroxy_6_methylphenyl_4_methoxypyran_2
  }

  branch from udp_alpha_d_glucose side right {
    udp_alpha_d_glucose
    <-> . +udp +glucosyl_heptosyl_2_kdo2_lipid_a +h
    alpha_hep_1_3_alpha_hep_1_5_alpha_kdo_2_4_alpha
  }

  branch from h2o side left {
    h2o
    <-> . +l_threonine +l_isoleucine +l_tryptophan
    tryptophanyl_threonyl_isoleucine
  }

  branch from h2o side right {
    h2o
    <-> . +l_threonine +l_tryptophan +l_tyrosine
    tryptophanyl_threonyl_tyrosine
  }

  branch from h2o2 side left {
    h2o2
    <-> . +z_phenylacetaldehyde_oxime +h +h2o +nh4
    2_phenylacetaldehyde
  }

  branch from h2o2 side right {
    h2o2
    <-> . +docosan_1_ol +o2_mnxm735438
    docosanal
  }

  branch from udp side left {
    udp
    <-> ec_2_4_1_241 [2.4.1.241] +h +1_18_1_2_18_3_digalactosyldiacylglycerol +1_9z_octadecenoyl_2_9z_12z_15z_octadecatrienoyl
    udp_alpha_d_galactose
  }

  branch from udp side right {
    udp
    <-> ec_2_4_1_241 [2.4.1.241] +h +1_20_0_2_18_3_digalactosyldiacylglycerol +udp_alpha_d_galactose
    1_20_0_2_18_3_monogalactosyldiacylglycerol
  }

  branch from h side left {
    h
    <-> ec_2_3_3_11 [2.3.3.11] +r_2_hydroxyglutarate +coa +glyoxylate +h2o
    propanoyl_coa
  }

  branch from h side right {
    h
    <-> ec_2_3_3_11 [2.3.3.11] +propanoyl_coa +glyoxylate +h2o +s_2_hydroxyglutarate
    coa
  }

  branch from udp_alpha_d_glucose side left {
    udp_alpha_d_glucose
    <-> ec_2_4_1_249 [2.4.1.249] +udp +ternatin_c5 +h
    delphinidin_3_o_6_o_malonyl_beta_d_glucoside
  }

  branch from udp_alpha_d_glucose side right {
    udp_alpha_d_glucose
    <-> ec_2_4_1_249 [2.4.1.249] +udp +ternatin_c5_mnxm1371483 +h
    delphinidin_3_o_6_o_malonyl_beta_d_glucoside_mnxm1371396
  }
}
