# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-hydroxyhexacosanoyl-CoA(4−) to 1,2-diacyl-sn-glycerol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-hydroxyhexacosanoyl-coa-to-1-2-diacyl-sn-glyce "2-hydroxyhexacosanoyl-CoA to 1,2-diacyl-sn-glycerol" {
  spacing 172

  spine at 0,0 {
    2_hydroxyhexacosanoyl_coa
    <-> . +sphinganine -coa -hplus
    n_2_hydroxyhexacosanoyl_sphinganine
    <-> . +1_phosphatidyl_1d_myo_inositol -dag
    ins_1_p_cer_d18_0_2_oh_26_0
    <-> ec_2_7_1_107 [2.7.1.107] +dag +atp -adp -hplus
    1_2_diacyl_sn_glycerol_3_phosphate
    <-> ec_3_1_3_4 [3.1.3.4] +h2o -pi
    dag
  }

  branch from n_2_hydroxyhexacosanoyl_sphinganine side left {
    n_2_hydroxyhexacosanoyl_sphinganine
    <-> . +nadph +o2 +hplus +nadp +h2o
    n_hexacosanoylsphinganine
  }

  branch from dag side right {
    dag
    <-> ec_4_6_1_13 [4.6.1.13] +1_phosphatidyl_1d_myo_inositol
    1d_myo_inositol_1_2_cyclic_phosphate
  }

  branch from 1_2_diacyl_sn_glycerol_3_phosphate side left {
    1_2_diacyl_sn_glycerol_3_phosphate
    <-> . +1_acyl_sn_glycerol_3_phosphate +1_2_diacyl_sn_glycero_3_phospho_1_sn_glycerol
    1_acyl_sn_glycero_3_phospho_1_sn_glycerol
  }
}
