# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-methylanisole to 2-hydroxy-6-oxo-2,4-heptadienoate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-methylanisole-to-2-hydroxy-6-oxo-2-4-hepta "2-methylanisole to 2-hydroxy-6-oxo-2,4-hepta…" {
  spacing 192

  spine at 0,0 {
    2_methylanisole
    <-> . +fadh2 +o2 -fad -formaldehyde -h2o -hplus
    o_cresol
    <-> ec_1_14_13_243 [1.14.13.243] +nadh +o2 +hplus -nad -h2o
    3_methylcatechol
    <-> . +o2 -hplus
    2_hydroxy_6_oxo_2_4_heptadienoate
  }

  branch from o_cresol side left {
    o_cresol
    <-> ec_1_14_13_243 [1.14.13.243] +nadh +o2 +hplus +nad +h2o
    toluene
  }

  branch from o_cresol side right {
    o_cresol
    <-> . +2_methylphenoxy_acetate +akg +o2 +succinate +co2
    glyoxylate
  }

  branch from formaldehyde side left {
    formaldehyde
    <-> . +n6_n6_n6_trimethyl_l_lysine +akg +o2 +succinate +co2
    n6_n6_dimethyl_l_lysine_1
  }

  branch from formaldehyde side right {
    formaldehyde
    <-> ec_1_14_99_66 [1.14.99.66] +n6_n6_dimethyl_l_lysine_1 +hydrogen_acceptor +h2o +hydrogen_donor
    l_lysinium
  }

  branch from 3_methylcatechol side left {
    3_methylcatechol
    <-> ec_1_3_1_68 [1.3.1.68] +nad +co2 +nadh
    1_6_dihydroxy_2_methylcyclohexa_2_4_diene_1_carb
  }

  branch from 3_methylcatechol side right {
    3_methylcatechol
    <-> . +nadh +o2 +hplus +co2 +nad +h2o
    3_methylsalicylate
  }
}
