# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-nitrophenolate to L-2-aminoadipate(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-nitrophenolate-to-l-2-aminoadipate "2-nitrophenolate to L-2-aminoadipate" {
  spacing 180

  spine at 0,0 {
    2_nitrophenolate
    <-> ec_1_14_13_31 [1.14.13.31] +nadph +o2 +hplus -nitrite -nadp -h2o
    catechol
    <-> ec_6_7_1_2 [6.7.1.2] +e_3_aminocoumarate +nitrite +atp +hplus -amp -ppi -h2o
    e_3_diazocoumarate
    <-> ec_1_2_1_95 [1.2.1.95] +l_allysine +amp +ppi +nadp -atp -nadph -hplus
    l_2_aminoadipate
  }

  branch from catechol side left {
    catechol
    <-> ec_1_14_14_20 [1.14.14.20] +fadh2 +o2 +fad +h2o +hplus
    phenol
  }

  branch from nitrite side right {
    nitrite
    <-> ec_1_14_12_24 [1.14.12.24] +2_4_dinitrotoluene +nadh +o2 +nad
    4_methyl_5_nitrocatechol
  }

  branch from ppi side left {
    ppi
    <-> ec_2_7_7_47 [2.7.7.47] +streptomycin +atp
    3_adenylylstreptomycin
  }
}
