# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-nitrophenolate to nitrite; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-nitrophenolate-to-nitrite "2-nitrophenolate to nitrite" {
  spacing 180

  spine at 0,0 {
    2_nitrophenolate
    <-> ec_1_14_13_31 [1.14.13.31] +nadph +o2 +hplus -nitrite -nadp -h2o
    catechol
    <-> ec_1_7_1_2 [1.7.1.2] +nitrite +nadp +h2o -nadph -hplus
    nitrate
    <-> ec_1_7_5_1 [1.7.5.1] +hydroquinones -nitrite -h2o
    1_4_benzoquinones
  }

  branch from nitrite side left {
    nitrite
    <-> ec_1_7_1_4 [1.7.1.4] +nadp +h2o +nadph +hplus
    nh3
  }

  branch from 1_4_benzoquinones side right {
    1_4_benzoquinones
    <-> ec_1_1_5_11 [1.1.5.11] +butan_1_ol +hydroquinones
    butanal
  }
}
