# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-oxoglutaramate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-oxoglutaramate-to-h2o-null "2-oxoglutaramate to H2O" {
  spacing 276

  spine at 0,0 {
    2_oxoglutaramate
    <-> ec_2_6_1_15 [2.6.1.15] +l_serine -3_hydroxypyruvate
    l_glutamine
    <-> ec_1_1_1_291 [1.1.1.291] +nadh +h +3_hydroxypyruvate -nad
    l_glyceric_acid
    <-> ec_1_2_1_22 [1.2.1.22] +nadh +h -nad -h2o
    l_glyceraldehyde
    <-> ec_3_6_3_17 [3.6.3.17] +h +adp +phosphate -l_glyceraldehyde -h2o
    atp
  }

  branch from l_glutamine side left {
    l_glutamine
    <-> ec_4_3_3_6 [4.3.3.6] +glyceraldehyde_3_phosphate +d_ribulose_5_phosphate +h +l_glutamate +phosphate +h2o
    pyridoxal_5_phosphate
  }

  branch from l_glutamine side right {
    l_glutamine
    <-> ec_4_3_3_6 [4.3.3.6] +d_glyceraldehyde_3_phosphate +d_ribulose_5_phosphate +pyridoxal_5_phosphate +h +phosphate +h2o
    l_glutamate
  }

  branch from 3_hydroxypyruvate side left {
    3_hydroxypyruvate
    <-> . +co2 +h
    dihydroxyfumarate
  }

  branch from 3_hydroxypyruvate side right {
    3_hydroxypyruvate
    <-> . +fadh2 +h +nh4 +d_serine +h2o
    fad
  }

  branch from nad side left {
    nad
    <-> ec_1_1_1_1 [1.1.1.1] +nadh +h +2_octanone
    2s_octan_2_ol
  }

  branch from nad side right {
    nad
    <-> ec_1_1_1_1 [1.1.1.1] +nadh +h +heptan_2_one
    heptan_2r_ol
  }

  branch from h2o side left {
    h2o
    <-> ec_3_4_14_5 [3.4.14.5] +l_alanine +gly_pro
    gly_pro_ala
  }

  branch from h2o side right {
    h2o
    <-> ec_3_2_1_3 [3.2.1.3] +isomaltose
    beta_d_glucose
  }

  branch from atp side left {
    atp
    <-> ec_6_2_1_1 [6.2.1.1] +diphosphate +fluoroacetyl_coa +amp +coa
    fluoroacetate
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_3 [2.7.1.3] +alpha_d_xylose +h +adp
    alpha_d_xylose_1_phosphate
  }
}
