# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-trans,6-trans-farnesyl diphosphate(3−) to zerumbone; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-trans-6-trans-farnesyl-to-zerumbone "2-trans,6-trans-farnesyl… to zerumbone" {
  spacing 180

  spine at 0,0 {
    fpp
    <-> ec_4_2_3_104 [4.2.3.104] -ppi
    1e_4e_8e_humulene
    <-> ec_1_14_14_113 [1.14.14.113] +fmnh2 +o2 -fmn -h2o -hplus
    8_hydroxy_humulene
    <-> ec_1_1_1_326 [1.1.1.326] +nad -nadh -hplus
    zerumbone
  }

  branch from ppi side left {
    ppi
    <-> ec_2_5_1_153 [2.5.1.153] +tuberculosinyl_diphosphate +h2o
    13s_edaxadiene
  }

  branch from fmn side right {
    fmn
    <-> ec_1_14_14_67 [1.14.14.67] +11_hydroxysugiol +fmnh2 +o2 +h2o +hplus
    11_20_dihydroxysugiol
  }
}
