# Ingested from Rhea. The spine follows the carbon skeleton from
# 2-trans,6-trans-farnesyl diphosphate(3−) to FMN(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2-trans-6-trans-farnesyl-to-fmn-22672 "2-trans,6-trans-farnesyl… to FMN" {
  spacing 216

  spine at 0,0 {
    fpp
    <-> ec_2_5_1_103 [2.5.1.103] -ppi
    presqualene_pp
    <-> ec_1_3_1_96 [1.3.1.96] +nadph +hplus -ppi -nadp
    squalene
    <-> ec_1_14_14_17 [1.14.14.17] +fmnh2 +o2 -fmn -h2o -hplus
    epoxysqualene
  }

  branch from epoxysqualene side left {
    epoxysqualene
    <-> ec_5_4_99_8 [5.4.99.8]
    cycloartenol
  }

  branch from epoxysqualene side right {
    epoxysqualene
    <-> ec_5_4_99_31 [5.4.99.31]
    thalianol
  }

  branch from epoxysqualene side left {
    epoxysqualene
    <-> ec_5_4_99_35 [5.4.99.35]
    taraxerol
  }

  branch from epoxysqualene side right {
    epoxysqualene
    <-> ec_5_4_99_36 [5.4.99.36]
    isomultiflorenol
  }
}
