# Ingested from Rhea. The spine follows the carbon skeleton from
# (25S)-3alpha,7alpha,12alpha-trihydroxy-5beta-cholestan-26-oyl-CoA to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 25s-3alpha-7alpha-12alp-to-h2o-null "(25S)-3alpha,7alpha,12alp… to H2O" {
  spacing 308

  spine at 0,0 {
    25s_3alpha_7alpha_12alpha_trihydroxy_5beta_chol
    <-> . +fad -h -24e_3alpha_7alpha_12alpha_trihydroxy_5beta_chol
    fadh2
    <-> . +h +24e_3alpha_7alpha_12alpha_trihydroxy_5beta_chol -3alpha_7alpha_12alpha_trihydroxy_5beta_cholestan
    fad
    <-> ec_6_2_1_7 [6.2.1.7] +diphosphate +amp +3alpha_7alpha_12alpha_trihydroxy_5beta_cholestan -atp -coa -25r_3alpha_7alpha_12alpha_trihydroxy_5beta_chol
    h
    <-> . +25r_3alpha_7alpha_12alpha_trihydroxy_5beta_chol +nadph -25r_3alpha_7alpha_12alpha_trihydroxy_5beta_chol_mnxm730282 -h2o
    nadp
  }

  branch from fadh2 side left {
    fadh2
    <-> . +4z_7z_10z_13z_16z_19z_docosahexaenoyl_coa +fad +h
    2_4_7_10_13_16_19_docosaheptenoylcoa
  }

  branch from fadh2 side right {
    fadh2
    <-> . +2e_11z_octadecadienoyl_coa +h +fad
    11e_octadecenoyl_coa
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    7_beta_oh_gliclazide_glucuronide
  }

  branch from h side right {
    h
    <-> . +adp +phosphate +atp +h2o
    n_acetyl_5_aminosalicylic_acid
  }

  branch from fad side left {
    fad
    <-> . +nadh +acetyl_coa +fadh2 +h +coa +nad +h2o
    linoelaidyl_coenzyme_a
  }

  branch from fad side right {
    fad
    <-> . +nadh +acetyl_coa +fadh2 +h +coa +nad +h2o
    5z_8z_11z_icosatrienoyl_coa
  }

  branch from atp side left {
    atp
    <-> . +h +adp +phosphate +h2o
    acetaminophen_glutathione_conjugate
  }

  branch from atp side right {
    atp
    <-> . +acetaminophen_glutathione_conjugate +h +phosphate +acetaminophen_glutathione_conjugate +h2o
    adp
  }

  branch from coa side left {
    coa
    <-> . +s_carnitine +3_hydroxyoctadecenoylcoa
    3_hydroxy_octadecenoyl_carnitine
  }

  branch from coa side right {
    coa
    <-> . +3s_hydroxyoctadecanoyl_coa +s_carnitine
    3_hydroxyoctadecanoylcarnitine
  }

  branch from nadp side left {
    nadp
    <-> . +7_aminoclonazepam +h2o +h +nadph
    clonazepam
  }

  branch from nadp side right {
    nadp
    <-> . +h2o +h +clonazepam +nadph
    7_aminoclonazepam
  }

  branch from h2o side left {
    h2o
    <-> . +d_glucuronate +4_acetamidophenol +h
    acetaminophen_o_beta_d_glucosiduronic_acid
  }

  branch from h2o side right {
    h2o
    <-> . +beta_d_mannose_6_phosphate +phosphoenolpyruvate +h +phosphate
    2_keto_3_deoxy_d_glycero_d_galactononic_acid_9_p
  }

  branch from fad side left {
    fad
    <-> . +6z_9z_12z_octadecatrienoyl_coa +fadh2 +h
    2e_6z_9z_12z_octadecatetraenoyl_coa
  }

  branch from fad side right {
    fad
    <-> . +z_tetradec_7_enoyl_coa +fadh2 +h
    e_z_tetradeca_2_7_dienoyl_coa
  }

  branch from fadh2 side left {
    fadh2
    <-> . +e_z_dodeca_2_5_dienoyl_coa +h +fad
    cis_dodec_5_enoyl_coa
  }

  branch from fadh2 side right {
    fadh2
    <-> . +5z_8z_11z_14z_eicosatetraenoate +h +o2 +fad +h2o
    14_15_eet
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    adenosylcobalamin
  }

  branch from h side right {
    h
    <-> . +adp +phosphate +atp +h2o
    1_o_octadecyl_sn_glycero_3_phosphocholine
  }

  branch from diphosphate side left {
    diphosphate
    <-> . +h +amp +nad +atp +nh4
    deamino_nad
  }

  branch from diphosphate side right {
    diphosphate
    <-> . +9z_12z_octadecadienoate +atp +coa +amp
    9e_12e_octadecadienoyl_coa
  }

  branch from amp side left {
    amp
    <-> . +diphosphate +h +11z_octadecenoyl_coa +atp +coa
    trans_vaccenic_acid
  }

  branch from amp side right {
    amp
    <-> . +diphosphate +4_2r_3s_4r_5r_5_6_amino_9h_purin_9_yl_4_hydroxy +h +atp +coa
    4_hydroxyphenylacetate
  }

  branch from atp side left {
    atp
    <-> . +1_aminopropan_2_ol +adenosyl_cobyric_acid +adp +phosphate
    adenosyl_cobinamide
  }

  branch from atp side right {
    atp
    <-> . +h +adp +phosphate +h2o
    alpha_hydroxyalprazolam_glucuronide
  }
}
