# Ingested from Rhea. The spine follows the carbon skeleton from
# (2R)-2-hydroxy-4-(methylsulfanyl)butanoate to H(+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2r-2-hydroxy-4-methyls-to-h "(2R)-2-hydroxy-4-(methyls… to H" {
  spacing 340

  spine at 0,0 {
    2r_2_hydroxy_4_methylsulfanyl_butanoate
    <-> . +nadp -nadph -hplus
    4_methylthio_2_oxobutanoate
    <-> . +tyrosine -methionine
    3_4_hydroxyphenyl_pyruvate
    <-> ec_4_1_1_80 [4.1.1.80] +hplus -co2
    4_hydroxyphenyl_acetaldehyde
    <-> ec_3_5_99_14 [3.5.99.14] +dopamine -h2o
    s_norcoclaurinium
    <-> ec_2_1_1_128 [2.1.1.128] +sam -sah -hplus
    s_coclaurinium
    <-> ec_2_1_1_140 [2.1.1.140] +sam -sah -hplus
    s_n_methylcoclaurinium
    <-> ec_1_14_14_102 [1.14.14.102] +fmnh2 +o2 -fmn -h2o -hplus
    s_3_hydroxy_n_methylcoclaurinium
    <-> ec_2_1_1_116 [2.1.1.116] +sam -sah -hplus
    s_reticulinium
    <-> ec_2_1_1_291 [2.1.1.291] +sam -sah -hplus
    s_laudanine
    <-> . +s_adenosyl_l_homocysteine +h -r_reticuline
    s_adenosyl_l_methionine
    <-> . +5_methoxybenzimidazole -s_adenosyl_l_homocysteine -h
    5_methoxy_6_methylbenzimidazole
  }

  branch from 3_4_hydroxyphenyl_pyruvate side left {
    3_4_hydroxyphenyl_pyruvate
    <-> . +l_kynurenine +tyrosine
    4_2_aminophenyl_2_4_dioxobutanoate
  }

  branch from 3_4_hydroxyphenyl_pyruvate side right {
    3_4_hydroxyphenyl_pyruvate
    <-> . +tyrosine +glyoxylate
    glycine
  }

  branch from sah side left {
    sah
    <-> ec_2_1_1_209 [2.1.1.209] +guanosine_5_monophosphate_1 +sam +hplus
    n1_methylguanosine_5_monophosphate_1
  }

  branch from sah side right {
    sah
    <-> ec_2_1_1_211 [2.1.1.211] +uridine_5_monophosphate_1 +sam +hplus
    2_o_methyluridine_5_monophosphate_1
  }

  branch from fmn side left {
    fmn
    <-> ec_1_14_14_30 [1.14.14.30] +2_methylpropanaminium +fmnh2 +o2 +h2o +hplus
    n_hydroxy_2_methylpropanamine
  }

  branch from fmn side right {
    fmn
    <-> . +arachidonate +fmnh2 +o2 +h2o +hplus
    14s_15r_eet
  }

  branch from s_reticulinium side left {
    s_reticulinium
    <-> ec_1_21_3_3 [1.21.3.3] +o2 +h2o2 +hplus
    s_scoulerine
  }

  branch from s_reticulinium side right {
    s_reticulinium
    <-> ec_2_1_1_337 [2.1.1.337] +sam +sah +hplus
    s_tembetarine
  }

  branch from s_adenosyl_l_methionine side left {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +h +avermectin_a1b_aglycone
    avermectin_b1b_aglycone
  }

  branch from s_adenosyl_l_methionine side right {
    s_adenosyl_l_methionine
    <-> ec_2_1_1_68 [2.1.1.68] +s_adenosyl_l_homocysteine +trans_sinapyl_alcohol +h
    e_5_hydroxyconiferyl_alcohol
  }

  branch from s_adenosyl_l_homocysteine side left {
    s_adenosyl_l_homocysteine
    <-> . +h +tetracenomycin_a2 +s_adenosyl_l_methionine
    tetracenomycin_e
  }

  branch from s_adenosyl_l_homocysteine side right {
    s_adenosyl_l_homocysteine
    <-> . +tetracenomycin_b2 +h +s_adenosyl_l_methionine
    tetracenomycin_b3
  }

  branch from h side left {
    h
    <-> ec_3_1_1_13 [3.1.1.13] +9z_12z_octadecadienoate +cholesterol +h2o
    cholesteryl_linoleate
  }

  branch from h side right {
    h
    <-> ec_3_1_1_13 [3.1.1.13] +9z_12z_15z_octadecatrienoate +cholesterol +h2o
    cholesteryl_linolenate
  }
}
