# Ingested from Rhea. The spine follows the carbon skeleton from
# (2R)-3-{[1-(5,6-dihydropyridin-2-yl)-2-hydroxy-2-{3-[(1E)-prop-1-en-1-yl]oxiran-2-yl}ethyl]sulfanyl}-2-acetamidopropanoate to (1S,2Z)-5-amino-1-(3-{3-[(1E)-prop-1-en-1-yl]oxiran-2-yl}oxiran-2-yl)pent-2-en-1-ol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2r-3-1-5-6-dihydropy-to-1s-2z-5-amino-1-3-3-nul "(2R)-3-{[1-(5,6-dihydropy… to (1S,2Z)-5-amino-1-(3-{3-[…" {
  spacing 176

  spine at 0,0 {
    2r_3_1_5_6_dihydropyridin_2_yl_2_hydroxy_2_3_1e
    <-> . -n_acetyl_l_cysteine
    2_3_3_1e_prop_1_en_1_yl_oxiran_2_yl_oxiran_2_yl
    <-> . +h2o
    2_3_3_1e_prop_1_en_1_yl_oxiran_2_yl_oxiran_2_yl
    <-> . +fadh2 +h -1s_2z_5_amino_1_3_3_1e_prop_1_en_1_yl_oxiran_2
    fad
  }

  branch from h2o side left {
    h2o
    <-> . +l_leucine +l_proline +l_tryptophan
    tryptophanyl_prolyl_leucine
  }

  branch from h2o side right {
    h2o
    <-> . +l_threonine +l_isoleucine +l_tryptophan
    tryptophanyl_threonyl_isoleucine
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    glycochenodeoxycholate
  }

  branch from h side right {
    h
    <-> . +adp +taurochenodeoxycholate +phosphate +taurochenodeoxycholate +h2o
    atp
  }
}
