# Ingested from Rhea. The spine follows the carbon skeleton from
# (2R)-hydroxyhexanoate to phosphate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 2r-hydroxyhexanoate-to-phosphate "(2R)-hydroxyhexanoate to phosphate" {
  spacing 268

  spine at 0,0 {
    2r_hydroxyhexanoate
    <-> . +nad -nadh -hplus
    2_oxohexanoate
    <-> . +l_kynurenine -4_2_aminophenyl_2_4_dioxobutanoate
    l_2_aminohexanoic_acid
    <-> .
    d_norleucine
    <-> ec_6_3_2_4 [6.3.2.4] +d_alanine +atp -h -adp -phosphate
    d_alanyl_d_norleucine
  }

  branch from h side left {
    h
    <-> . +huvastatin_acid +h2o
    huvastatin_lactone
  }

  branch from h side right {
    h
    <-> . +monacolin_j_carboxylate +2_dimethylbutanoyl_s_methyl_mercaptopropanoate +simvastatin_hydroxy_acid
    methyl_mercaptopropanoate
  }

  branch from adp side left {
    adp
    <-> ec_2_7_1_21 [2.7.1.21] +acyclovir +h +atp
    acyclovir_monophosphate
  }

  branch from adp side right {
    adp
    <-> ec_2_7_1_21 [2.7.1.21] +h +3_azido_3_deoxythymidine_5_phosphate +atp
    zidovudine
  }

  branch from phosphate side left {
    phosphate
    <-> ec_3_1_3_12 [3.1.3.12] +6_o_mycolyltrehalose_6_phosphate +h2o +h
    alpha_alpha_trehalose_6_alpha_mycolate
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_12 [3.1.3.12] +6_o_cis_methoxy_mycolyl_trehalose_6_phosphate +h2o
    trehalose_cis_methoxy_mono_mycolate
  }

  branch from d_alanine side left {
    d_alanine
    <-> . +n_acetylglucosamine_n_acetylmuramoyl_l_alanyl_d
    a_peptidoglycan_with_d_d_cross_links_meso_diamin
  }

  branch from d_alanine side right {
    d_alanine
    <-> ec_3_4_17_13 [3.4.17.13] +l_alanyl_d_glutamyl_meso_2_6_diaminoheptanedioat +h +h2o
    l_alanyl_gamma_d_glutamyl_meso_2_6_diaminopimelo
  }

  branch from atp side left {
    atp
    <-> ec_6_3_2_1 [6.3.2.1] +diphosphate +pantoylglycine +amp +r_pantoate
    glycine
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_1 [2.7.1.1] +1_5_anhydro_d_glucitol_6_phosphate +h +adp
    1_5_anhydro_d_glucitol
  }

  branch from h side left {
    h
    <-> ec_2_2_1_12 [2.2.1.12] +co2 +r_1_3_diphenyl_pentane_1_4_dione +trans_chalcone
    pyruvate
  }

  branch from h side right {
    h
    <-> . +gdp_d_erythro_alpha_d_gluco_octose +diphosphate +d_erythro_alpha_d_gluco_octopyranose1_phosphate
    gtp
  }

  branch from adp side left {
    adp
    <-> ec_2_7_1_1 [2.7.1.1] +d_arabinose_5_phosphate +h +atp
    d_arabinofuranose
  }

  branch from adp side right {
    adp
    <-> ec_2_7_1_1 [2.7.1.1] +2_5_anhydro_d_mannitol +h +atp
    2_5_anhydro_d_mannitol_6_phosphate
  }

  branch from phosphate side left {
    phosphate
    <-> ec_3_1_3_12 [3.1.3.12] +6_o_trans_methoxy_mycolyl_trehalose_6_phosphate +h2o
    trehalose_trans_methoxy_mono_mycolate
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_12 [3.1.3.12] +6_o_cis_keto_mycolyl_trehalose_6_phosphate +h2o
    trehalose_cis_keto_mono_mycolate
  }
}
