# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-[(3aS,4S,5R,7aS)-5-hydroxy-7a-methyl-1,5-dioxo-octahydroinden-4-yl]propanoate to 3-[(3aS,4S,5R,7aS)-5-hydroxy-7a-methyl-1-oxo-octahydro-1H-inden-4-yl]-3-hydroxypropanoyl-CoA; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-3as-4s-5r-7as-5-hydr-to-3-3as-4s-5r-7as-5-hydr "3-[(3aS,4S,5R,7aS)-5-hydr… to 3-[(3aS,4S,5R,7aS)-5-hydr…" {
  spacing 176

  spine at 0,0 {
    3_3as_4s_5r_7as_5_hydroxy_7a_methyl_1_5_dioxo_oc
    <-> . +atp +coa -amp -ppi
    3_3as_4s_5r_7as_5_hydroxy_7a_methyl_1_oxo_octahy
    <-> . +hydrogen_acceptor -hydrogen_donor
    2e_3_3as_4s_5r_7as_5_hydroxy_7a_methyl_1_oxo_oc
    <-> . +h2o
    3_3as_4s_5r_7as_5_hydroxy_7a_methyl_1_oxo_octahy
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_226 [4.2.3.226] +2_cis_6_trans_farnesyl_diphosphate
    2_epi_prezizaene
  }

  branch from ppi side right {
    ppi
    <-> . +2_cis_6_trans_farnesyl_diphosphate
    curcumene
  }

  branch from hydrogen_donor side left {
    hydrogen_donor
    <-> ec_1_14_99_58 [1.14.99.58] +ferroheme_b +o2 +hplus +carbon_monoxide +fe2 +hydrogen_acceptor +h2o
    biliverdin
  }

  branch from hydrogen_donor side right {
    hydrogen_donor
    <-> ec_1_14_99_58 [1.14.99.58] +ferroheme_b +o2 +hplus +carbon_monoxide +fe2 +hydrogen_acceptor +h2o
    biliverdin
  }
}
