# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-dehydro-D-glucose-6-phosphate(2−) to 3-amino-3-deoxy-6-O-phosphono-D-glucopyranose(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-dehydro-d-glucose-6-pho-to-3-amino-3-deoxy-6-o "3-dehydro-D-glucose-6-pho… to 3-amino-3-deoxy-6-O-phosp…" {
  spacing 288

  spine at 0,0 {
    3_dehydro_d_glucose_6_phosphate
    <-> ec_2_6_1_104 [2.6.1.104] +glutamate -akg
    3_amino_3_deoxy_6_o_phosphono_d_glucopyranose
    <-> ec_3_1_3_92 [3.1.3.92] +h2o -pi
    3_amino_3_deoxy_d_glucopyranose
    <-> ec_2_7_1_179 [2.7.1.179] +atp -adp -hplus
    3_amino_3_deoxy_6_o_phosphono_d_glucopyranose
  }

  branch from akg side left {
    akg
    <-> . +fad +hplus +fadh2
    r_2_hydroxyglutarate
  }

  branch from akg side right {
    akg
    <-> . +nad +nadh +hplus
    s_2_hydroxyglutarate
  }
}
