# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-Epiecdysone to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-epiecdysone-to-h2o "3-Epiecdysone to H2O" {
  spacing 328

  spine at 0,0 {
    3_epiecdysone
    <-> . +nad -h -3_dehydroecdysone
    nadh
    <-> ec_1_1_1_50 [1.1.1.50] +h +3_dehydroecdysone -nad
    ecdysone
    <-> . +h +phosphate -h2o
    ecdysone_22_phosphate
  }

  branch from nadh side left {
    nadh
    <-> . +5_dehydro_l_gluconate +h +nad
    l_gluconic_acid
  }

  branch from nadh side right {
    nadh
    <-> . +all_trans_zeaxanthin +h +o2 +nad +h2o
    nostoxanthin
  }

  branch from h side left {
    h
    <-> . +o_citryl_l_serine +o_citryl_ethanolamine
    co2
  }

  branch from h side right {
    h
    <-> . +ctp +glycerol_2_phosphate +cdp_2_glycerol
    diphosphate
  }

  branch from 3_dehydroecdysone side left {
    3_dehydroecdysone
    <-> . +3_epiecdysone +nadp +h
    nadph
  }

  branch from 3_dehydroecdysone side right {
    3_dehydroecdysone
    <-> . +h +nadph +ecdysone
    nadp
  }

  branch from nad side left {
    nad
    <-> . +nadh +all_trans_beta_carotene +h +o2 +h2o
    2s_2_s_dihydroxy_all_trans_beta_carotene
  }

  branch from nad side right {
    nad
    <-> . +nadh +d_xylonate +h +h2o
    aldehydo_d_xylose
  }

  branch from h2o side left {
    h2o
    <-> ec_3_4_19_16 [3.4.19.16] +z_1_l_cysteinylglycin_s_yl_n_hydroxy_omega_meth +l_glutamate
    z_1_glutathion_s_yl_n_hydroxy_omega_methylsulfa
  }

  branch from h2o side right {
    h2o
    <-> ec_3_4_19_16 [3.4.19.16] +z_1_l_cysteinylglycin_s_yl_n_hydroxy_omega_meth +l_glutamate
    z_1_glutathion_s_yl_n_hydroxy_omega_methylsulfa
  }
}
