# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-Geranylgeranylindole to FMN(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-geranylgeranylindole-to-fmn "3-Geranylgeranylindole to FMN" {
  spacing 262

  spine at 0,0 {
    3_geranylgeranylindole
    <-> . +diphosphate +d_glyceraldehyde_3_phosphate -1s_2r_1_c_indol_3_yl_glycerol_3_phosphate
    2e_6e_10e_geranylgeranyl_diphosphate
    <-> . +cdp -2e_6e_10e_geranylgeranyl_phosphate
    ctp
    <-> . +2e_6e_10e_geranylgeranyl_phosphate +h2o -pi
    e_e_e_geranylgeraniol
    <-> ec_1_14_14_146 [1.14.14.146] +fmnh2 +o2 -fmn -h2o -hplus
    plaunotol
  }

  branch from 2e_6e_10e_geranylgeranyl_diphosphate side left {
    2e_6e_10e_geranylgeranyl_diphosphate
    <-> ec_2_5_1_29 [2.5.1.29] +ipp +diphosphate
    2e_geranyl_diphosphate
  }

  branch from 2e_6e_10e_geranylgeranyl_diphosphate side right {
    2e_6e_10e_geranylgeranyl_diphosphate
    <-> ec_2_5_1_41 [2.5.1.41] +diphosphate +sn_3_o_geranylgeranyl_glycerol_1_phosphate
    sn_glycerol_3_phosphate
  }

  branch from 1s_2r_1_c_indol_3_yl_glycerol_3_phosphate side left {
    1s_2r_1_c_indol_3_yl_glycerol_3_phosphate
    <-> ec_4_2_1_20 [4.2.1.20] +glyceraldehyde_3_phosphate +l_tryptophan +h2o +l_serine
    h
  }

  branch from 1s_2r_1_c_indol_3_yl_glycerol_3_phosphate side right {
    1s_2r_1_c_indol_3_yl_glycerol_3_phosphate
    <-> ec_4_1_2_8 [4.1.2.8] +indole +h
    glyceraldehyde_3_phosphate
  }

  branch from ctp side left {
    ctp
    <-> . +beta_d_fructose_6_phosphate +h +diphosphate
    cdp_d_fructose
  }

  branch from ctp side right {
    ctp
    <-> ec_2_7_7_67 [2.7.7.67] +2_3_bis_o_phytanyl_sn_glycerol_1_phosphate +h +diphosphate
    cdp_2_3_bis_o_phytanyl_sn_glycerol
  }

  branch from 2e_6e_10e_geranylgeranyl_phosphate side left {
    2e_6e_10e_geranylgeranyl_phosphate
    <-> . +e_e_e_geranylgeraniol +udp +hplus
    utp
  }

  branch from 2e_6e_10e_geranylgeranyl_phosphate side right {
    2e_6e_10e_geranylgeranyl_phosphate
    <-> . +h2o +pi +hplus
    2_trans_6_trans_10_trans_geranylgeranyl_diphosph
  }

  branch from e_e_e_geranylgeraniol side left {
    e_e_e_geranylgeraniol
    <-> . +nadph +o2 +hplus +nadp +h2o
    hydroxygeranylgeraniol
  }

  branch from e_e_e_geranylgeraniol side right {
    e_e_e_geranylgeraniol
    <-> . +nadph +o2 +hplus +nadp +h2o
    2e_6e_10e_geranylgeranate
  }

  branch from plaunotol side left {
    plaunotol
    <-> ec_1_14_13_110 [1.14.13.110] +2e_6e_10e_geranylgeraniol +h +o2 +nadph +h2o
    nadp
  }

  branch from fmn side right {
    fmn
    <-> . +all_cis_5_8_11_14_17_icosapentaenoate +fmnh2 +o2 +h2o +hplus
    5z_8z_14z_17z_11_12_epoxyicosatetraenoate
  }

  branch from fmn side left {
    fmn
    <-> . +all_cis_5_8_11_14_17_icosapentaenoate +fmnh2 +o2 +h2o +hplus
    5z_8z_11z_17z_14_15_epoxyicosatetraenoate
  }
}
