# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-hydroxy-2-methylpropanoyl-CoA(4−) to propionyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-hydroxy-2-methylpropano-to-propionyl-coa "3-hydroxy-2-methylpropano… to propionyl-CoA" {
  spacing 280

  spine at 0,0 {
    3_hydroxy_2_methylpropanoyl_coa
    <-> ec_3_1_2_4 [3.1.2.4] +h2o -coa -hplus
    3_hydroxyisobutyrate
    <-> ec_1_1_1_31 [1.1.1.31] +nad -nadh -hplus
    2_methyl_3_oxopropanoate
    <-> ec_1_2_1_27 [1.2.1.27] +nad +coa +h2o -hco3 -nadh -hplus
    propionyl_coa
  }

  branch from propionyl_coa side left {
    propionyl_coa
    <-> ec_2_3_1_94 [2.3.1.94] +s_methylmalonyl_coa +nadph +hplus +co2 +nadp +coa +h2o
    6_deoxyerythronolide_b
  }
}
