# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-hydroxy-3-phenylpropionic acid to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-hydroxy-3-phenylpropion-to-h2o "3-hydroxy-3-phenylpropion… to H2O" {
  spacing 224

  spine at 0,0 {
    3_hydroxy_3_phenylpropionic_acid
    <-> . -acetate -benzaldehyde
    h
    <-> ec_1_1_1_19 [1.1.1.19] +benzaldehyde +nadph -nadp
    benzyl_alcohol
    <-> ec_3_1_1_1 [3.1.1.1] +h +1_hydroxy_6_oxocyclohex_2_ene_1_carboxylate -h2o
    benzyl_6_hydroxy_2_cyclohexene_on_oyl
  }

  branch from h side left {
    h
    <-> . +emodin +emodin_anthrone +h2o
    emodin_dianthrone
  }

  branch from h side right {
    h
    <-> ec_3_1_1_26 [3.1.1.26] +9z_octadecenoate +mgmg_0_0_16_0 +h2o
    1_9z_octadecenoyl_2_hexadecanoyl_3_d_galactosyl
  }

  branch from acetate side left {
    acetate
    <-> . +s_4_hydroxy_nonenal_3_yl_l_cysteine +h2o
    4_hydroxy_2_nonenal_n_acetyl_l_cysteine
  }

  branch from acetate side right {
    acetate
    <-> . +3_aminobutan_2_ol +h2o
    n_3_hydroxybutan_2_yl_acetamide
  }

  branch from benzaldehyde side left {
    benzaldehyde
    <-> ec_1_14_13_84 [1.14.13.84] +benzoate +nadp +h2o +nadph
    o2
  }

  branch from benzaldehyde side right {
    benzaldehyde
    <-> ec_4_1_2_26 [4.1.2.26] +glycine
    l_threo_3_phenylserine
  }

  branch from benzyl_alcohol side left {
    benzyl_alcohol
    <-> ec_1_1_99_36 [1.1.99.36] +3_4_dimethoxybenzaldehyde +benzaldehyde
    3_4_dimethoxyphenyl_methanol
  }

  branch from benzyl_alcohol side right {
    benzyl_alcohol
    <-> ec_3_5_1_133 [3.5.1.133] +co2 +l_glutamine +h +h2o
    n_carbobenzyloxy_l_glutamine
  }

  branch from nadp side left {
    nadp
    <-> . +h +10e_12z_hexadeca_10_12_dienoate +nadph +h2o
    bombykol
  }

  branch from nadp side right {
    nadp
    <-> . +h +nadph +2_5_dihydroxybenzoate +h2o
    2_5_dihydroxybenzaldehyde
  }

  branch from h2o side left {
    h2o
    <-> ec_3_4_11_2 [3.4.11.2] +glycine +s_4_hydroxy_nonenal_3_yl_l_cysteine
    s_4_hydroxy_nonenal_3_yl_l_cysteinylglycine
  }

  branch from h2o side right {
    h2o
    <-> ec_3_2_1_149 [3.2.1.149] +linalool +a_6_o_beta_d_xylopyranosyl_beta_d_glucopyranose
    linalyl_beta_primeveroside
  }
}
