# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-hydroxy-L-kynurenine zwitterion to diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-hydroxy-l-kynurenine-to-diphosphate "3-hydroxy-L-kynurenine to diphosphate" {
  spacing 300

  spine at 0,0 {
    3_hydroxy_l_kynurenine
    <-> . +sam -sah -hplus
    3_hydroxy_4_methyl_l_kynurenine
    <-> . +h2o -alanine -hplus
    3_hydroxy_4_methylanthranilate
    <-> ec_2_7_7_97 [2.7.7.97] +atp +hplus -ppi
    2_amino_3_hydroxy_4_methylbenzoyl_amp
  }

  branch from sah side left {
    sah
    <-> . +tryptaminium +sam +hplus
    n_methyltryptaminium
  }

  branch from sah side right {
    sah
    <-> . +n_methyltryptaminium +sam +hplus
    n_n_dimethyltryptaminium
  }

  branch from alanine side left {
    alanine
    <-> . +cholate +h2o
    l_alanocholate
  }

  branch from alanine side right {
    alanine
    <-> . +taurocholate +l_alanocholate
    taurine
  }

  branch from ppi side left {
    ppi
    <-> . +kanamycin_a +utp
    4_uridylylkanamycin_a
  }

  branch from ppi side right {
    ppi
    <-> . +kanamycin_a +datp
    4_2_deoxyadenylyl_kanamycin_a
  }
}
