# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-methylpalmitoyl-CoA(4−) to N3-(carboxylatoformyl)-L-2,3-diaminopropionate(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-methylpalmitoyl-coa-to-n3-carboxylatoformyl-l "3-methylpalmitoyl-CoA to N3-(carboxylatoformyl)-L-…" {
  spacing 228

  spine at 0,0 {
    3_methylpalmitoyl_coa
    <-> . +akg +o2 -succinate -co2
    2_hydroxy_3_methylhexadecanoyl_coa
    <-> ec_4_1_2_63 [4.1.2.63] -formyl_coa
    2_methylpentadecanal
    <-> ec_2_8_3_16 [2.8.3.16] +formyl_coa +oxalate -formate
    oxalyl_coa
    <-> ec_2_3_1_58 [2.3.1.58] +3_amino_l_alanine -coa
    n3_carboxylatoformyl_l_2_3_diaminopropionate
  }

  branch from succinate side left {
    succinate
    <-> . +hexanoyl_coa +akg +o2 +co2
    2_hydroxyhexanoyl_coa
  }

  branch from formyl_coa side right {
    formyl_coa
    <-> . +2_hydroxystearoyl_coa
    heptadecanal
  }
}
