# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-oxooleoyl-CoA(4−) to (11Z-octadecenoyl)-cholesterol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-oxooleoyl-coa-to-11z-octadecenoyl-choles "3-oxooleoyl-CoA to (11Z-octadecenoyl)-choles…" {
  spacing 164

  spine at 0,0 {
    3_oxooleoyl_coa
    <-> . +coa -9z_hexadecenoyl_coa
    acetyl_coa
    <-> . +nadh +fadh2 +9z_hexadecenoyl_coa +h -coa -11z_octadecenoyl_coa -nad -h2o
    fad
    <-> . +11z_octadecenoyl_coa +cholesterol -coa
    11z_octadecenoyl_cholesterol
  }

  branch from cholesterol side left {
    cholesterol
    <-> ec_1_14_19_21 [1.14.19.21] +nadh +o2 +hplus +nad +h2o
    dehydrocholesterol_7
  }

  branch from cholesterol side right {
    cholesterol
    <-> . +glycyl_l_cysteine +hplus +l_cysteiniumyl_group
    glycino_3_cholesterol_ester_group
  }
}
