# Ingested from Rhea. The spine follows the carbon skeleton from
# 3-sinapoyloxypropylglucosinolate to sulfate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3-sinapoyloxypropylglucos-to-sulfate "3-sinapoyloxypropylglucos… to sulfate" {
  spacing 224

  spine at 0,0 {
    3_sinapoyloxypropylglucosinolate
    <-> . +coa -e_sinapoyl_coa
    z_3_hydroxypropyl_glucosinolate
    <-> . +h2o -glucose -hplus
    z_3_hydroxypropyl_n_sulfonatooxy_methanimidothi
    <-> . -sulfur_atom -sulfate
    4_hydroxybutylnitrile
    <-> ec_1_12_98_4 [1.12.98.4] +sulfur_atom +h2 -h
    hydrogen_sulfide
    <-> . +o2 -sulfate
    h
  }

  branch from z_3_hydroxypropyl_glucosinolate side left {
    z_3_hydroxypropyl_glucosinolate
    <-> . +methanesulfonate +h +o2 +h2o
    glucoiberin
  }

  branch from z_3_hydroxypropyl_glucosinolate side right {
    z_3_hydroxypropyl_glucosinolate
    <-> . +benzoyl_coa +coa
    glucomalcommin
  }

  branch from glucose side left {
    glucose
    <-> ec_3_2_1_216 [3.2.1.216] +d_glcp_1_2_d_glcp +h2o
    d_glucose
  }

  branch from glucose side right {
    glucose
    <-> ec_3_2_1_220 [3.2.1.220] +ipecoside +h2o
    ipecoside_aglycone
  }

  branch from sulfur_atom side left {
    sulfur_atom
    <-> ec_3_2_1_147 [3.2.1.147] +beta_d_glucose +indol_3_yl_acetonitrile +h +sulfate +h2o
    z_glucobrassicin
  }

  branch from sulfur_atom side right {
    sulfur_atom
    <-> ec_3_2_1_147 [3.2.1.147] +alpha_d_glucose +indol_3_yl_acetonitrile +h +sulfate +z_glucobrassicin
    h2o
  }

  branch from hydrogen_sulfide side left {
    hydrogen_sulfide
    <-> ec_4_2_1_22 [4.2.1.22] +l_homocysteine +l_cysteine +h
    l_l_cystathionine
  }

  branch from hydrogen_sulfide side right {
    hydrogen_sulfide
    <-> ec_4_2_1_22 [4.2.1.22] +mercaptoethanol +l_cysteine +h
    s_2_hydroxyethyl_l_cysteine
  }

  branch from h side left {
    h
    <-> ec_3_1_1_13 [3.1.1.13] +9z_octadecenoate +lanosterol +h2o
    lanosteryl_oleate
  }

  branch from h side right {
    h
    <-> ec_3_1_1_13 [3.1.1.13] +9z_octadecenoate +ergosterol +h2o
    ergosteryl_oleate
  }

  branch from sulfate side left {
    sulfate
    <-> ec_1_8_3_1 [1.8.3.1] +h +ferrocyanide +ferricyanide +h2o
    sulfite
  }

  branch from sulfate side right {
    sulfate
    <-> ec_3_1_6_1 [3.1.6.1] +2_hydroxy_5_nitrophenyl_hydrogen_sulfate +h2o +h
    4_nitrocatechol
  }
}
