# Ingested from Rhea. The spine follows the carbon skeleton from
# (3E)-2-oxopent-3-enoate to O2; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3e-2-oxopent-3-enoate-to-o2 "(3E)-2-oxopent-3-enoate to O2" {
  spacing 210

  spine at 0,0 {
    3e_2_oxopent_3_enoate
    <-> ec_5_3_2_6 [5.3.2.6]
    2_oxopent_4_enoate
    <-> . +2_methylpropanoate +h -h2o
    7_methyl_2_hydroxy_6_oxoocta_2_4_dienoate
    <-> . +h -o2
    3_isopropylcatechol
  }

  branch from h2o side left {
    h2o
    <-> ec_3_6_3_17 [3.6.3.17] +h +adp +l_rhodinose +phosphate +l_rhodinose
    atp
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_17 [3.6.3.17] +h +adp +phosphate +atp
    beta_d_fucose
  }

  branch from 3_isopropylcatechol side left {
    3_isopropylcatechol
    <-> . +o2
    7_methyl_2_hydroxy_6_oxoocta_2_4_dienoate
  }

  branch from o2 side right {
    o2
    <-> . +strictosamide
    strictosamide_ketolactam
  }

  branch from o2 side left {
    o2
    <-> ec_1_14_13_236 [1.14.13.236] +nadh +h +4_fluorophenol +nad +h2o
    4_fluorocatechol
  }
}
