# Ingested from Rhea. The spine follows the carbon skeleton from
# (3E)-5-oxopent-3-ene-1,2,5-tricarboxylic acid to O2; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 3e-5-oxopent-3-ene-1-2-to-o2 "(3E)-5-oxopent-3-ene-1,2,… to O2" {
  spacing 324

  spine at 0,0 {
    3e_5_oxopent_3_ene_1_2_5_tricarboxylic_acid
    <-> .
    2z_4e_5_hydroxypenta_2_4_diene_1_2_5_tricarboxy
    <-> ec_1_1_1_312 [1.1.1.312] +nadh +h -nad -h2o
    2_hydroxy_5_carboxymethylmuconate_semialdehyde
    <-> ec_1_13_11_15 [1.13.11.15] -3_4_dihydroxyphenylacetate -o2
    h
  }
}
