# Ingested from Rhea. The spine follows the carbon skeleton from
# 4-[(E)-2-(3,4-dihydroxyphenyl)ethenyl]-1,7-dihydroxy-2,3,5-trioxabicyclo[2.2.2]oct-7-en-6-one to excited state fungal oxyluciferin; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 4-e-2-3-4-dihydroxyph-to-excited-state-fungal-nu "4-[(E)-2-(3,4-dihydroxyph… to excited state fungal…" {
  spacing 158

  spine at 0,0 {
    4_e_2_3_4_dihydroxyphenyl_ethenyl_1_7_dihydroxy
    <-> . -o2 -3_hydroxyhispidin
    h
    <-> . +3_hydroxyhispidin +o2
    4_e_2_3_4_dihydroxyphenyl_ethenyl_1_hydroxy_6_ox
    <-> . -excited_state_fungal_oxyluciferin
    co2
  }

  branch from 3_hydroxyhispidin side left {
    3_hydroxyhispidin
    <-> . +nadph +o2 +hplus +nadp +h2o
    hispidin
  }
}
