# Ingested from Rhea. The spine follows the carbon skeleton from
# 4-(hydroxylamino)-N,N-dimethylaniline to H2O2; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 4-hydroxylamino-n-n-dim-to-h2o2 "4-(hydroxylamino)-N,N-dim… to H2O2" {
  spacing 262

  spine at 0,0 {
    4_hydroxylamino_n_n_dimethylaniline
    <-> ec_1_1_99_36 [1.1.99.36] +2_octanone -octan_2_ol
    n_n_dimethyl_4_nitrosoaniline
    <-> ec_1_1_99_36 [1.1.99.36] +2_phenyl_1_propanol -4_hydroxylamino_n_n_dimethylaniline
    2_phenylpropanal
    <-> ec_1_1_1_1 [1.1.1.1] +nadh +h -nad
    2_phenyl_1_propanol
    <-> ec_1_1_99_36 [1.1.99.36] +3_4_dimethoxybenzaldehyde -3_4_dimethoxyphenyl_methanol
    2_phenylpropanal
    <-> ec_1_1_99_36 [1.1.99.36] +glyoxal +3_4_dimethoxyphenyl_methanol -glycolaldehyde
    3_4_dimethoxybenzaldehyde
    <-> ec_1_11_1_14 [1.11.1.14] +1_3_4_dimethoxyphenyl_ethane_1_2_diol +h2o -h2o2
    1_2_bis_3_4_dimethoxyphenyl_propane_1_3_diol
  }

  branch from nad side left {
    nad
    <-> ec_1_1_1_211 [1.1.1.211] +nadh +h +6z_9z_12z_15z_18z_3_oxotetracosapentaenoyl_coa
    6z_9z_12z_15z_18z_3_hydroxytetracosapenta_6_9_1
  }

  branch from nad side right {
    nad
    <-> ec_1_2_1_3 [1.2.1.3] +nadh +h +2r_3_phosphoglycerate +h2o
    glyceraldehyde_3_phosphate
  }

  branch from 3_4_dimethoxyphenyl_methanol side left {
    3_4_dimethoxyphenyl_methanol
    <-> ec_1_1_99_36 [1.1.99.36] +3_4_dimethoxybenzaldehyde +3_phenylbutan_1_ol
    3_phenylbutanal
  }

  branch from 3_4_dimethoxyphenyl_methanol side right {
    3_4_dimethoxyphenyl_methanol
    <-> ec_1_1_99_36 [1.1.99.36] +hydroxyacetone +3_4_dimethoxybenzaldehyde
    methylglyoxal
  }

  branch from 3_4_dimethoxybenzaldehyde side left {
    3_4_dimethoxybenzaldehyde
    <-> ec_1_1_99_36 [1.1.99.36] +propane_1_2_diol +3_4_dimethoxyphenyl_methanol
    hydroxyacetone
  }

  branch from h2o2 side right {
    h2o2
    <-> . +nadh +octanedioyl_coa +acetyl_coa +h +coa +o2 +nad +h2o
    decanedioyl_coa
  }

  branch from h2o2 side left {
    h2o2
    <-> . +nadh +acetyl_coa +3z_6z_dodecadienoyl_coa +h +coa +o2 +nad +h2o
    cis_cis_tetradeca_5_8_dienoyl_coa
  }
}
