# Ingested from Rhea. The spine follows the carbon skeleton from
# (4R,5R)-1,2-dithiane-4,5-diol to 5-methyldeoxycytidine 5'-diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 4r-5r-1-2-dithiane-4-5-to-5-methyldeoxycytidine "(4R,5R)-1,2-dithiane-4,5-… to 5-methyldeoxycytidine…" {
  spacing 282

  spine at 0,0 {
    4r_5r_1_2_dithiane_4_5_diol
    <-> ec_1_1_4_2 [1.1.4.2] +3_hydroxy_2_methyl_3_phytyl_2_3_dihydro_1_4_naph -l_1_4_dithiothreitol
    2_3_epoxyphylloquinone
    <-> ec_1_17_4_1 [1.17.4.1] +ctp +l_1_4_dithiothreitol -dctp -h2o
    4r_5r_1_2_dithiane_4_5_diol
    <-> ec_6_3_4_2 [6.3.4.2] +h +dctp +adp +l_glutamate +phosphate -atp -dutp -h2o
    l_glutamine
    <-> . +phytyl_phosphate +dutp -phytyl_diphosphate
    dudp
    <-> ec_2_7_1_74 [2.7.1.74] +h +dcmp -2_deoxycytidine
    dutp
    <-> ec_2_7_1_74 [2.7.1.74] +2_deoxycytidine +nucleoside_5_triphoshate -nucleoside_5_diphosphate -hplus
    2_deoxycytosine_5_monophosphate
    <-> ec_2_1_1_54 [2.1.1.54] +methylene_thf -dhf
    2_deoxy_5_methyl_5_cytidylate
    <-> ec_2_7_4_19 [2.7.4.19] +atp -adp
    5_methyldeoxycytidine_5_diphosphate
  }

  branch from l_1_4_dithiothreitol side left {
    l_1_4_dithiothreitol
    <-> ec_1_1_4_1 [1.1.4.1] +4r_5r_1_2_dithiane_4_5_diol +menaquinone_2 +h2o
    2_3_epoxymenaquinone
  }

  branch from dctp side right {
    dctp
    <-> ec_2_7_1_48 [2.7.1.48] +cmp +h +dcdp
    cytidine
  }

  branch from dctp side left {
    dctp
    <-> . +cdp +dcdp
    cmp
  }

  branch from h2o side right {
    h2o
    <-> . +s_dnpa
    s_hemiketal
  }

  branch from h2o side left {
    h2o
    <-> ec_3_1_1_95 [3.1.1.95] +epsilon_rhodomycin_t +15_demethoxy_epsilon_rhodomycin
    methanol
  }

  branch from l_glutamine side right {
    l_glutamine
    <-> . +acetyl_coa +h +n_acetyl_l_glutaminyl_l_glutamine +h2o
    coa
  }

  branch from l_glutamine side left {
    l_glutamine
    <-> . +n_acetyl_l_glutaminyl_l_glutamine +l_glutamate
    n2_acetyl_l_glutaminyl_l_glutamamide
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_151 [2.7.1.151] +1d_myo_inositol_1_4_5_trisphosphate +h +adp
    1d_myo_inositol_4_5_bisphosphate
  }

  branch from atp side left {
    atp
    <-> . +1d_myo_inositol_3_4_6_trisphosphate +h +adp
    d_myo_inositol_3_6_bisphosphate
  }
}
