# Ingested from Rhea. The spine follows the carbon skeleton from
# 5α-cholestan-3-one to di-μ-sulfido-diiron(2+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 5-cholestan-3-one-to-di-sulfido-diiron "5α-cholestan-3-one to di-μ-sulfido-diiron" {
  spacing 152

  spine at 0,0 {
    5_cholestan_3_one
    <-> . +nadp -nadph -hplus
    cholest_4_en_3_one
    <-> . +di_sulfido_diiron +o2 +hplus -di_sulfido_diiron -h2o
    25r_26_hydroxycholest_4_en_3_one
    <-> . +di_sulfido_diiron +o2 +hplus -di_sulfido_diiron -h2o
    25r_3_ketocholest_4_en_26_al
    <-> . +di_sulfido_diiron +o2 +hplus -di_sulfido_diiron -h2o
    25r_4_dafachronate
  }

  branch from cholest_4_en_3_one side left {
    cholest_4_en_3_one
    <-> ec_1_14_15_29 [1.14.15.29] +di_sulfido_diiron +o2 +hplus +di_sulfido_diiron +h2o
    25s_4_dafachronate
  }

  branch from di_sulfido_diiron side right {
    di_sulfido_diiron
    <-> ec_1_14_15_32 [1.14.15.32] +pentalenene +di_sulfido_diiron +o2 +hplus +h2o
    pentalen_13_al
  }
}
