# Ingested from Rhea. The spine follows the carbon skeleton from
# 5-formimidoyltetrahydrofolate(2−) to hydrogen cyanide; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 5-formimidoyltetrahydrofo-to-hydrogen-cyanide "5-formimidoyltetrahydrofo… to hydrogen cyanide" {
  spacing 216

  spine at 0,0 {
    5_formimidoyltetrahydrofolate
    <-> ec_2_1_2_5 [2.1.2.5] +glutamate -thf
    n_formimidoyl_l_glutamate
    <-> ec_3_5_3_8 [3.5.3.8] +h2o -glutamate
    formamide
    <-> ec_4_2_1_66 [4.2.1.66] -h2o
    hydrogen_cyanide
  }

  branch from glutamate side left {
    glutamate
    <-> ec_2_6_1_49 [2.6.1.49] +ldopa +akg
    3_4_dihydroxyphenylpyruvate
  }

  branch from glutamate side right {
    glutamate
    <-> ec_2_3_1_35 [2.3.1.35] +n2_acetyl_l_ornithine +ornithine
    nag
  }

  branch from hydrogen_cyanide side left {
    hydrogen_cyanide
    <-> ec_1_14_17_4 [1.14.17.4] +1_aminocyclopropanecarboxylic_acid +ascorbate +o2 +l_dehydroascorbate +co2 +h2o
    ethene
  }

  branch from hydrogen_cyanide side right {
    hydrogen_cyanide
    <-> ec_1_14_19_52 [1.14.19.52] +l_cys_ian +fmnh2 +o2 +fmn +co2 +h2o +hplus
    camalexin
  }
}
