# Ingested from Rhea. The spine follows the carbon skeleton from
# 5-hydroperoxy-EPA to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 5-hydroperoxy-epa-to-h2o-null "5-hydroperoxy-EPA to H2O" {
  spacing 248

  spine at 0,0 {
    5_hydroperoxy_epa
    <-> . -h2o
    leukotriene_a5
    <-> . +h +h2o
    leukotriene_b5
    <-> . +h +adp +phosphate -leukotriene_b5 -h2o
    atp
  }

  branch from h2o side left {
    h2o
    <-> ec_1_10_3_4 [1.10.3.4] +3_hydroxy_4_methyl_anthranilate_pentapeptide_lac +o2
    actinomycin_d
  }

  branch from h2o side right {
    h2o
    <-> . +l_alanine +h +3_hydroxy_4_methylanthranilate
    3_hydroxy_4_methyl_d_kynurenine
  }

  branch from leukotriene_b5 side left {
    leukotriene_b5
    <-> . +h +o2
    5z_8z_11z_14z_17z_eicosapentaenoate
  }

  branch from atp side right {
    atp
    <-> ec_3_6_3_41 [3.6.3.41] +h +adp +phosphate +h2o
    heme
  }

  branch from atp side left {
    atp
    <-> . +h +adp +phosphate +h2o
    9z_octadecenoyl_coa
  }

  branch from 5_hydroperoxy_epa side right {
    5_hydroperoxy_epa
    <-> . +5z_8z_11z_14z_17z_eicosapentaenoate
    o2
  }

  branch from h2o side left {
    h2o
    <-> ec_1_10_3_4 [1.10.3.4] +actinocin +o2
    3_hydroxy_4_methylanthranilate
  }

  branch from h2o side right {
    h2o
    <-> . +n_acetylphosphinothricyl_l_alanyl_l_leucine +h +phosalacine
    acetate
  }

  branch from h side left {
    h
    <-> . +8_o_methyl_13_carboxynorjavanicin
    8_o_methyl_fusarubinlactone
  }

  branch from h side right {
    h
    <-> ec_1_13_11_4 [1.13.11.4] +2e_3_methyl_4_6_dioxohept_2_enedioate +o2
    4_methylgentisate
  }

  branch from adp side left {
    adp
    <-> . +l_alanine +l_histidine +atp +h +phosphate
    ala_his
  }

  branch from adp side right {
    adp
    <-> . +h +phosphate +atp +h2o
    pb
  }

  branch from phosphate side left {
    phosphate
    <-> ec_3_1_3_29 [3.1.3.29] +lyxose +h2o
    d_ribulose_5_phosphate
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_29 [3.1.3.29] +d_arabinose_5_phosphate +h2o
    2_3_4_5_tetrahydroxypentanal
  }

  branch from atp side left {
    atp
    <-> . +nadh +acetyl_coa +fadh2 +diphosphate +h +amp +tetradecanoate +coa +nad +h2o
    fad
  }

  branch from atp side right {
    atp
    <-> . +diphosphate +h +adp +l_glutamate +cob_ii_yrinate_diamide +cob_ii_yrinate +h2o
    l_glutamine
  }
}
