# Ingested from Rhea. The spine follows the carbon skeleton from
# 6-O-α-D-glucopyranosyl-D-fructofuranose to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 6-o-d-glucopyranosyl-d-to-h2o "6-O-α-D-glucopyranosyl-D-… to H2O" {
  spacing 216

  spine at 0,0 {
    6_o_d_glucopyranosyl_d_fructofuranose
    <-> ec_3_2_1_219 [3.2.1.219] +h2o -d_fructofuranose
    d_glucose
    <-> . +atp -adp -hplus
    d_glucose_6_phosphate
    <-> ec_5_3_1_9 [5.3.1.9]
    d_fructofuranose_6_phosphate
    <-> ec_2_4_1_246 [2.4.1.246] +gdp_d_mannose -gdp -hplus
    d_fructofuranosyl_d_mannopyranoside_6f_phosphat
    <-> ec_3_1_3_79 [3.1.3.79] +h2o -pi
    d_fructofuranosyl_d_mannopyranoside
    <-> ec_3_6_3_18 [3.6.3.18] +h +adp +phosphate -d_fructofuranosyl_d_mannopyranoside -h2o
    atp
  }
}
