# Ingested from Rhea. The spine follows the carbon skeleton from
# 6-sulfo-D-quinovose(1−) to thioacetate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 6-sulfo-d-quinovose-to-thioacetate-70775 "6-sulfo-D-quinovose to thioacetate" {
  spacing 228

  spine at 0,0 {
    6_sulfo_d_quinovose
    <-> ec_1_14_14_181 [1.14.14.181] +fmnh2 +o2 -fmn -sulfite -h2o -hplus
    6_dehydro_d_glucose
    <-> ec_1_8_5_5 [1.8.5.5] +1_4_benzoquinones +h2s +sulfite +hplus -hydroquinones
    trioxidosulfanidosulfate
    <-> ec_2_8_1_5 [2.8.1.5] +dithioerythritol -h2s -sulfite -hplus
    cis_1_2_dithiane_4_5_diol
    <-> ec_2_3_1_10 [2.3.1.10] +h2s +acetyl_coa -coa
    thioacetate
  }

  branch from fmn side left {
    fmn
    <-> . +fmnh2 +medermycin +o2 +h +h2o
    mederrhodin_a
  }

  branch from fmn side right {
    fmn
    <-> . +fmnh2 +dihydrokalafungin_dihydroquinone_form +o2 +h +h2o
    dhk_oh
  }
}
