# Ingested from Rhea. The spine follows the carbon skeleton from
# (6S)-5-formyl-5,6,7,8-tetrahydrofolate to L-glutamate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 6s-5-formyl-5-6-7-8-tet-to-l-glutamate-null "(6S)-5-formyl-5,6,7,8-tet… to L-glutamate" {
  spacing 296

  spine at 0,0 {
    6s_5_formyl_5_6_7_8_tetrahydrofolate
    <-> . +atp +h2o -h -adp -phosphate
    6r_10_formyltetrahydrofolate
    <-> . +l_glutamate -h2o
    10_formyltetrahydrofolate_glu_5
    <-> . +l_glutamate -h2o
    10_formyltetrahydrofolate_glu_6
    <-> . +l_glutamate -h2o
    10_formyltetrahydrofolate_glu_7
    <-> . +h +adp +phosphate -atp -l_glutamate
    10_formyltetrahydrofolate_glu_6
  }

  branch from h side left {
    h
    <-> . +2_hydroxy_3_carboxy_6_methoxy_hexa_2_4_dienoate +co2
    2_hydroxy_6_methoxy_hexa_2_4_dienoate
  }

  branch from h side right {
    h
    <-> . +2_hydroxy_3_carboxy_6_methoxy_hexa_2_4_dienoate +co2
    2_hydroxy_6_methoxy_hexa_2_4_dienoate
  }

  branch from adp side left {
    adp
    <-> . +adp_l_glycero_d_manno_heptose +glucosyl_heptosyl_2_kdo2_lipid_a_phosphate +h
    glucosyl_heptosyl_3_kdo2_lipid_a_phosphate
  }

  branch from adp side right {
    adp
    <-> ec_3_6_3_17 [3.6.3.17] +h +phosphate +atp +h2o
    alpha_d_galactose
  }

  branch from phosphate side left {
    phosphate
    <-> ec_2_4_2_2 [2.4.2.2] +2_deoxy_alpha_d_ribose_1_phosphate +thymine
    thymidine
  }

  branch from phosphate side right {
    phosphate
    <-> ec_6_3_1_9 [6.3.1.9] +glutathionylspermidine +atp +glutathione +h +adp
    trypanothione
  }

  branch from h2o side left {
    h2o
    <-> . +2_hydroxy_5_nitropenta_2_4_dienoate +h +acetate
    2_hydroxy_5_nitro_6_oxohepta_2_4_dienoate
  }

  branch from h2o side right {
    h2o
    <-> . +4_1_methyl_5_hydroxy_2_pyrrolidinyl_3_oxobutanoa
    ecgonone_methyl_ester
  }

  branch from atp side left {
    atp
    <-> ec_2_7_1_16 [2.7.1.16] +3s_4s_2_hydroxymethyl_oxolane_2_3_4_triol +h +adp
    l_ribulose_5_phosphate
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_47 [2.7.1.47] +h +adp +l_ribulose_5_phosphate
    lyxose
  }

  branch from l_glutamate side left {
    l_glutamate
    <-> . +h +glycine +h2o
    glycyl_glutamate
  }

  branch from l_glutamate side right {
    l_glutamate
    <-> . +s_2_carboxy_1_1_h_imidazol_4_yl_ethyl_l_cysteine +glycine +h2o
    s_2_carboxy_1_1h_imidazol_4_yl_ethyl_glutathione
  }

  branch from atp side left {
    atp
    <-> ec_2_7_1_101 [2.7.1.101] +d_tagatofuranose_6_phosphate +h +adp
    d_tagatopyranose
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_53 [2.7.1.53] +l_xylulose_5_phosphate +h +adp
    lyxulose
  }

  branch from h2o side left {
    h2o
    <-> . +4_1_methyl_5_hydroxy_2_pyrrolidinyl_3_oxobutanoa
    2_carbomethoxy_3_tropinone
  }

  branch from h2o side right {
    h2o
    <-> . +butanal +4_hydroxy_5_methyl_3_2h_furanone
    2e_2_butylidene_4_hydroxy_5_methyl_3_2h_furanon
  }

  branch from h side left {
    h
    <-> . +5_6_dihydroxy_3_methyl_2_oxo_1_2_dihydroquinolin +o2
    3_methyl_5_hydroxy_6_3_carboxy_3_oxopropenyl_1h
  }

  branch from h side right {
    h
    <-> . +o2 +3_methyl_5_hydroxy_6_3_carboxy_3_oxopropenyl_1h
    5_6_dihydroxy_3_methyl_2_oxo_1_2_dihydroquinolin
  }

  branch from adp side left {
    adp
    <-> ec_7_6_2_3 [7.6.2.3] +h +phosphate +atp +h2o
    3_glutathion_s_yl_3_methylhexan_1_ol
  }

  branch from adp side right {
    adp
    <-> . +adp_l_glycero_d_manno_heptose +heptosyl_kdo_2_lipid_a +h
    heptosyl_heptosyl_kdo2_lipida
  }

  branch from phosphate side left {
    phosphate
    <-> . +dihydroneopterin_phosphate +h2o
    dihydroneopterin
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_1 [3.1.3.1] +7_8_dihydroneopterin_3_triphosphate +h2o +h
    7_8_dihydroneopterin
  }

  branch from l_glutamate side left {
    l_glutamate
    <-> . +diphosphate +h +amp +nad +l_glutamine +atp +h2o
    deamino_nad
  }

  branch from l_glutamate side right {
    l_glutamate
    <-> . +diphosphate +hydrogenobyrinate_a_c_diamide +h +adp +l_glutamine +atp +h2o
    hydrogenobyrinate
  }
}
