# Ingested from Rhea. The spine follows the carbon skeleton from
# (6Z)-octadecenoyl-CoA(4−) to palmitoyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 6z-octadecenoyl-coa-to-palmitoyl-coa "(6Z)-octadecenoyl-CoA to palmitoyl-CoA" {
  spacing 152

  spine at 0,0 {
    6z_octadecenoyl_coa
    <-> . +fad +hplus -fadh2
    2e_6z_octadecadi_2_6_enoyl_coa
    <-> . +h2o
    3s_6z_3_hydroxyoctadec_6_enoyl_coa
    <-> . +nad -nadh -hplus
    6z_3_oxo_octadec_6_enoyl_coa
    <-> . +coa -acetyl_coa
    4z_hexadec_4_enoyl_coa
    <-> . +fad +hplus -fadh2
    2e_4z_hexadecadi_2_4_enoyl_coa
    <-> . +nadph +hplus -nadp
    3e_hexadec_3_enoyl_coa
    <-> .
    trans_hexadecenoyl_coa
    <-> . +nadh +hplus -nad
    palmitoyl_coa
  }

  branch from palmitoyl_coa side left {
    palmitoyl_coa
    <-> . +alanine +hplus +co2 +coa
    1_deoxy_3_dehydrosphinganine
  }
}
