# Ingested from Rhea. The spine follows the carbon skeleton from
# 7,7',9,9'-tetra-cis-lycopene to N1-citryl-N3-oct-2-enoyl-N3-hydroxy-1,3-diaminopropane; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 7-7-9-9-tetra-cis-lycop-to-n1-citryl-n3-oct-2-en "7,7',9,9'-tetra-cis-lycop… to N1-citryl-N3-oct-2-enoyl-…" {
  spacing 152

  spine at 0,0 {
    7_7_9_9_tetra_cis_lycopene
    <-> . +ubiquinol_10 -7_9_9_tri_cis_neurosporene
    ubiquinone_10
    <-> . +octanoyl_coa -ubiquinol_10
    2e_octenoyl_coa
    <-> . +n_3_aminopropyl_hydroxylamine -n3_oct_2_enoyl_n3_hydroxy_1_3_diaminopropane
    coa
    <-> . +citrate +atp +n3_oct_2_enoyl_n3_hydroxy_1_3_diaminopropane -h -amp -n1_citryl_n3_oct_2_enoyl_n3_hydroxy_1_3_diaminop
    diphosphate
  }
}
