# Ingested from Rhea. The spine follows the carbon skeleton from
# 7-methylmellein to L-phenylalanine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 7-methylmellein-to-l-phenylalanine "7-methylmellein to L-phenylalanine" {
  spacing 152

  spine at 0,0 {
    7_methylmellein
    <-> . +fmnh2 +o2 -fmn -h2o -hplus
    7_carboxymellein
    <-> . +l_phenylalanine +atp -adp -pi -hplus
    ochratoxin_b
    <-> . +fadh2 +chloride +o2 -fad -h2o
    ochratoxin_a
    <-> . +h2o -l_phenylalanine
    ochratoxin
  }
}
