# Ingested from Rhea. The spine follows the carbon skeleton from
# 9-cis-retinol to FMN(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 9-cis-retinol-to-fmn "9-cis-retinol to FMN" {
  spacing 152

  spine at 0,0 {
    9_cis_retinol
    <-> . +nad -nadh -hplus
    9_cis_retinal
    <-> . +nad +h2o -nadh -hplus
    9_cis_retinoate
    <-> . +fmnh2 +o2 -fmn -h2o -hplus
    9_cis_4_hydroxyretinoate
    <-> . +fmnh2 +o2 -fmn -h2o -hplus
    9_cis_4_oxoretinoate
  }
}
