# Ingested from Rhea. The spine follows the carbon skeleton from
# 9-cis-violaxanthin to FMNH2(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway 9-cis-violaxanthin-to-fmnh2 "9-cis-violaxanthin to FMNH2" {
  spacing 280

  spine at 0,0 {
    9_cis_violaxanthin
    <-> ec_1_13_11_51 [1.13.11.51] +o2 -2_cis_4_trans_xanthoxin
    3s_5r_6s_5_6_epoxy_3_hydroxy_5_6_dihydro_12_apo
    <-> ec_1_1_1_288 [1.1.1.288] +2_cis_4_trans_xanthoxin +nad -nadh -hplus
    abscisic_aldehyde
    <-> ec_1_2_3_14 [1.2.3.14] +o2 +h2o -h2o2 -hplus
    abscisate
    <-> ec_1_14_14_137 [1.14.14.137] +fmnh2 +o2 -fmn -h2o -hplus
    8_hydroxyabscisate
    <-> ec_1_17_7_3 [1.17.7.3] +2e_4_hydroxy_3_methylbut_2_enyl_diphosphate +fmn +h2o +hplus -fmnh2
    2_c_methyl_d_erythritol_2_4_cyclic_diphosphate
  }
}
