# Ingested from Rhea. The spine follows the carbon skeleton from
# acetoacetyl-CoA to T-2 toxin; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway acetoacetyl-coa-to-t-2-toxin "acetoacetyl-CoA to T-2 toxin" {
  spacing 264

  spine at 0,0 {
    acetoacetyl_coa
    <-> ec_2_8_3_9 [2.8.3.9] +3_methylbutanoate -acetoacetate
    3_methylbutanoyl_coa
    <-> . +3_acetylneosolaniol -coa
    3_acetyl_t_2_toxin
    <-> . +h2o -acetate -t_2_toxin
    h
  }

  branch from 3_methylbutanoyl_coa side left {
    3_methylbutanoyl_coa
    <-> ec_1_3_99_10 [1.3.99.10] +nadh +3_methylbut_2_enoyl_coa +h
    nad
  }

  branch from 3_methylbutanoyl_coa side right {
    3_methylbutanoyl_coa
    <-> . +ubiquinol_10 +3_methylbut_2_enoyl_coa
    ubiquinone_10
  }

  branch from coa side left {
    coa
    <-> ec_2_3_1_255 [2.3.1.255] +l_seryl_group +acetyl_coa
    n_terminal_n_acetyl_l_serine
  }

  branch from coa side right {
    coa
    <-> ec_2_3_1_255 [2.3.1.255] +acetyl_coa +l_threonyl_group
    n_acetyl_l_threonyl
  }

  branch from h side left {
    h
    <-> ec_1_1_1_1 [1.1.1.1] +nadh +2_oxohexane +nad
    r_2_hexanol
  }

  branch from h side right {
    h
    <-> ec_1_1_1_1 [1.1.1.1] +nadh +s_2_methylbutanal +nad
    s_2_methylbutan_1_ol
  }

  branch from acetate side left {
    acetate
    <-> ec_3_1_1_3 [3.1.1.3] +2_aminofluorene +h +h2o
    2_acetamidofluorene
  }

  branch from acetate side right {
    acetate
    <-> ec_2_3_1_190 [2.3.1.190] +acetoin +2_6_dichloroindophenol +h2o +h +acetaldehyde
    reduced_2_6_dichlorophenolindophenol
  }
}
