# Ingested from Rhea. The spine follows the carbon skeleton from
# acetoacetyl-CoA to (2E)-glutaconyl-CoA; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway acetoacetyl-coa-to-2e-glutaconyl-coa "acetoacetyl-CoA to (2E)-glutaconyl-CoA" {
  spacing 340

  spine at 0,0 {
    acetoacetyl_coa
    <-> ec_2_8_3_9 [2.8.3.9] +2_butenoic_acid +h -acetoacetate
    but_2_enoyl_coa
    <-> ec_6_4_1_4 [6.4.1.4] +hydrogencarbonate +atp -adp -2e_glutaconyl_coa -phosphate
    h
    <-> ec_2_8_3_12 [2.8.3.12] +glutarate +2e_glutaconyl_coa -trans_glutaconate
    glutaryl_coa
    <-> . +fad -h -2e_glutaconyl_coa
    fadh2
  }

  branch from but_2_enoyl_coa side left {
    but_2_enoyl_coa
    <-> ec_1_3_1_10 [1.3.1.10] +butanoyl_coa +h +nadp
    nadph
  }

  branch from but_2_enoyl_coa side right {
    but_2_enoyl_coa
    <-> ec_1_3_3_6 [1.3.3.6] +butanoyl_coa +h +o2
    h2o2
  }

  branch from h side left {
    h
    <-> ec_5_3_1_6 [5.3.1.6] +alpha_d_ribofuranose_5_phosphate
    l_ribulose_5_phosphate
  }

  branch from h side right {
    h
    <-> ec_3_6_3_6 [3.6.3.6] +adp +phosphate +atp
    h2o
  }

  branch from adp side left {
    adp
    <-> . +h +phosphate +atp +h2o
    cysteine
  }

  branch from adp side right {
    adp
    <-> . +h +phosphate +atp +h2o
    butanoyl_coa
  }

  branch from phosphate side left {
    phosphate
    <-> ec_3_1_3_27 [3.1.3.27] +h +1_2_dioctadecanoyl_sn_glycero_3_phospho_1_sn_gly +h2o
    pg_18_0_18_0
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_27 [3.1.3.27] +h +1_2_dipalmitoyl_sn_glycero_3_phospho_1_sn_glycer +h2o
    1_2_dihexadecanoyl_sn_glycero_3_phospho_1_sn_gly
  }

  branch from glutaryl_coa side left {
    glutaryl_coa
    <-> ec_2_3_1_16 [2.3.1.16] +acetyl_coa +coa
    3_oxo_6_carboxyhexanoyl_coa
  }

  branch from glutaryl_coa side right {
    glutaryl_coa
    <-> . +s_carnitine +h +glutarylcarnitine
    coa
  }

  branch from fadh2 side left {
    fadh2
    <-> . +sibiromycin_aglycon +h +fad
    5e_7s_8r_8_11_13_trihydroxy_12_methyl_5_propyli
  }

  branch from fadh2 side right {
    fadh2
    <-> ec_1_14_19_9 [1.14.19.9] +5_nitroindole +h +o2 +bromide +fad +h2o
    3_bromo_5_nitroindole
  }

  branch from h side left {
    h
    <-> ec_1_1_1_71 [1.1.1.71] +nadh +neoabietadienal +nad
    isopimara_7_15_dienol
  }

  branch from h side right {
    h
    <-> ec_1_1_1_71 [1.1.1.71] +nadh +palustradienal +isopimara_7_15_dienol
    nad
  }

  branch from but_2_enoyl_coa side left {
    but_2_enoyl_coa
    <-> ec_4_2_1_116 [4.2.1.116] +h +h2o
    3s_3_hydroxybutanoyl_coa
  }

  branch from hydrogencarbonate side right {
    hydrogencarbonate
    <-> . +h +atp +coa +nadph +nad +acetyl_coa +diphosphate +adp +nadp +amp +phosphate +h2o
    nadh
  }

  branch from hydrogencarbonate side left {
    hydrogencarbonate
    <-> . +putrescine +nh4 +h +h2o
    n_carbamoylputrescine
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_1 [2.7.1.1] +beta_d_fructose +h +adp
    6_o_phosphonohexopyranose
  }

  branch from atp side left {
    atp
    <-> ec_2_7_1_1 [2.7.1.1] +h +adp +6_o_phosphonohexopyranose
    beta_d_fructopyranose
  }

  branch from adp side right {
    adp
    <-> ec_2_7_1_1 [2.7.1.1] +h +atp +6_o_phosphonohexopyranose
    alpha_d_mannopyranose
  }

  branch from adp side left {
    adp
    <-> ec_2_7_1_1 [2.7.1.1] +h +atp +6_o_phosphonohexopyranose
    beta_d_glucose
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_27 [3.1.3.27] +pgp_16_1_9z_16_1_9z +h2o +h
    phosphatidylglycerol_dihexadec_9_enoyl_n_c16_1
  }

  branch from phosphate side left {
    phosphate
    <-> . +nadh +h +atp +2_4_substituted_furan_phosphate +adp +nad
    4_phosphooxymethyl_2_furancarboxaldehyde
  }

  branch from glutaryl_coa side right {
    glutaryl_coa
    <-> . +fad +fadh2 +h
    glutaconyl_coenzyme_a
  }

  branch from fad side left {
    fad
    <-> . +fadh2 +h +7_8_dihydropteroate
    6s_5_6_7_8_tetrahydropteroate
  }

  branch from fad side right {
    fad
    <-> . +nadh +acetyl_coa +fadh2 +3_s_hydroxy_pravastatin_tetranor_coa +h +o2 +coa +nad +h2o
    3_s_hydroxy_pravastatin_coa
  }
}
