# Ingested from Rhea. The spine follows the carbon skeleton from
# acetyl-CoA to NADP(+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway acetyl-coa-to-nadp "acetyl-CoA to NADP" {
  spacing 292

  spine at 0,0 {
    acetyl_coa
    <-> ec_2_8_3_12 [2.8.3.12] +2_butenoic_acid +h -acetate
    but_2_enoyl_coa
    <-> ec_1_3_1_44 [1.3.1.44] +nadh -h -nad
    butanoyl_coa
    <-> . +nadh +acetyl_coa +h -coa -nad -h2o
    2e_hexenoyl_coa
    <-> . +co2 +nadph -nadp
    butylmalonyl_coa
  }

  branch from acetate side left {
    acetate
    <-> ec_2_8_3_18 [2.8.3.18] +acetyl_coa +s_malate
    s_malyl_coa
  }

  branch from acetate side right {
    acetate
    <-> ec_2_8_3_18 [2.8.3.18] +acetyl_coa +2_methylbutanedioic_acid +h
    methylsuccinyl_coa
  }

  branch from butanoyl_coa side left {
    butanoyl_coa
    <-> ec_2_3_1_206 [2.3.1.206] +malonyl_coa +h +co2 +coa
    divarinol
  }

  branch from butanoyl_coa side right {
    butanoyl_coa
    <-> . +s_carnitine +coa
    o_butanoyl_l_carnitine
  }

  branch from h side left {
    h
    <-> . +kinetensin +h2o +kinetensin_1_3 +d_arginyl_l_histidyl_d_prolyl_d_tyrosyl_l_phenyl
    l_leucine
  }

  branch from h side right {
    h
    <-> . +adp +rosuvastatin_5s_lactone +phosphate +rosuvastatin_5s_lactone +h2o
    atp
  }

  branch from nad side left {
    nad
    <-> ec_1_1_1_307 [1.1.1.307] +nadh +alpha_d_xylose +h
    xylitol
  }

  branch from nad side right {
    nad
    <-> ec_1_1_1_307 [1.1.1.307] +nadh +h +xylitol
    beta_d_xylose
  }

  branch from coa side left {
    coa
    <-> . +cis_cis_cis_10_13_16_docosatrienoyl_coa +r_carnitine
    10z_13z_16z_docosatrienoylcarnitine
  }

  branch from coa side right {
    coa
    <-> . +acetyl_coa +nonanoyl_coa
    3_oxoundecanoyl_coenzyme_a
  }

  branch from h2o side left {
    h2o
    <-> . +l_leucine +l_histidine +l_phenylalanine
    phe_leu_his
  }

  branch from h2o side right {
    h2o
    <-> . +l_leucine +l_phenylalanine
    phenylalanyl_leucine
  }

  branch from nadp side left {
    nadp
    <-> . +diphyllin +h2o +h +nadph +justicidin_b
    o2
  }

  branch from nadp side right {
    nadp
    <-> . +4s_4_5_5_dimethylcyclohex_1_en_1_yl_cyclohex_1 +o2 +nadph +h2o
    zealexin_a1
  }
}
