# Ingested from Rhea. The spine follows the carbon skeleton from
# β-alaninium amide to D-pantetheine 4'-phosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway alaninium-amide-to-d-pantetheine-4-phosphate "β-alaninium amide to D-pantetheine 4'-phosphate" {
  spacing 340

  spine at 0,0 {
    alaninium_amide
    <-> ec_3_5_1_100 [3.5.1.100] +h2o -nh3
    alanine
    <-> ec_6_3_2_44 [6.3.2.44] +r_pantoate +atp -adp -pi -hplus
    r_pantothenate
    <-> ec_2_7_1_33 [2.7.1.33] +atp -adp -hplus
    r_4_phosphonatopantothenate
    <-> ec_6_3_2_5 [6.3.2.5] +cysteine +ctp -cytidine_5_monophosphate -ppi -hplus
    n_r_4_phosphonatopantothenoyl_l_cysteinate
    <-> ec_4_1_1_36 [4.1.1.36] +hplus -co2
    d_pantetheine_4_phosphate
    <-> ec_3_1_3_110 [3.1.3.110] +h2o -pi
    pantetheine
    <-> ec_2_7_1_34 [2.7.1.34] +atp -adp -hplus
    d_pantetheine_4_phosphate
  }

  branch from nh3 side left {
    nh3
    <-> . +s_isoleucinol +nad +h2o +nadh +hplus
    3s_1_hydroxy_3_methylpentan_2_one
  }

  branch from nh3 side right {
    nh3
    <-> . +s_methioninol +nad +h2o +nadh +hplus
    1_hydroxy_4_methythio_butan_2_one
  }

  branch from r_4_phosphonatopantothenate side left {
    r_4_phosphonatopantothenate
    <-> . +cysteamine +co2 +n_r_4_phosphopantothenoyl_l_cysteine +h2o
    h
  }

  branch from r_4_phosphonatopantothenate side right {
    r_4_phosphonatopantothenate
    <-> ec_6_3_2_5 [6.3.2.5] +cdp +h +n_r_4_phosphopantothenoyl_l_cysteine +phosphate +l_cysteine
    ctp
  }

  branch from cytidine_5_monophosphate side left {
    cytidine_5_monophosphate
    <-> . +n_acetyl_neuraminosyl_2_3_d_galactosyl_1_3_n_ace +cmp_n_acetyl_neuraminate +hplus
    n_acetyl_neuraminosyl_2_3_d_galactosyl_1_3_n_ace
  }

  branch from cytidine_5_monophosphate side right {
    cytidine_5_monophosphate
    <-> . +d_gal_1_3_d_galnac_1_3_d_gal_1_4_d_gal_1_4_d_gl +cmp_n_acetyl_neuraminate +hplus
    monosialyl_gb5
  }

  branch from ppi side left {
    ppi
    <-> . +linolenate +atp +coa +amp
    linolenoyl_coa
  }

  branch from ppi side right {
    ppi
    <-> . +icosanoate +atp +coa +amp
    icosanoyl_coa
  }

  branch from nh3 side left {
    nh3
    <-> . +nad +h2o +pyruvate +nadh +hplus
    d_alanine
  }

  branch from nh3 side right {
    nh3
    <-> . +hexan_1_aminium +nad +h2o +nadh +hplus
    hexanal
  }

  branch from r_pantoate side left {
    r_pantoate
    <-> . +nad +nadh +hplus
    2_dehydropantoate
  }

  branch from r_4_phosphonatopantothenate side right {
    r_4_phosphonatopantothenate
    <-> . +ctp +h +r_4_phosphopantothenoyl_cytidylate
    diphosphate
  }

  branch from cysteine side left {
    cysteine
    <-> . +alanine
    3_disulfanyl_l_alanine
  }

  branch from cysteine side right {
    cysteine
    <-> . +glyoxylate +glycine
    mercaptopyruvate
  }

  branch from ctp side left {
    ctp
    <-> . +kanamycin_a +ppi
    4_cytidylylkanamycin_a
  }

  branch from ctp side right {
    ctp
    <-> . +amikacin +ppi
    4_cytidylylamikacin
  }

  branch from cytidine_5_monophosphate side left {
    cytidine_5_monophosphate
    <-> . +d_gal_1_4_d_glcnac_1_3_d_gal_1_4_d_glc_1_1_cer +cmp_n_acetyl_neuraminate +hplus
    neu5ac_2_3_d_gal_1_4_d_glcnac_1_3_d_gal_1_4_d_g
  }

  branch from cytidine_5_monophosphate side right {
    cytidine_5_monophosphate
    <-> ec_3_1_4_17 [3.1.4.17] +h2o +hplus
    3_5_cyclic_cmp
  }

  branch from ppi side left {
    ppi
    <-> . +5_end_purine_ribonucleotide_5_triphosphate_4 +gdp +hplus
    5_5_triphosphoguanosine_purine_ribonucleotide_3
  }

  branch from ppi side right {
    ppi
    <-> . +r_lipoate +gtp +hplus
    r_lipoyl_gmp
  }
}
