# Ingested from Rhea. The spine follows the carbon skeleton from
# alpha-D-xylosyl-(1->6)-beta-D-glucosyl- (1->4)-beta-D-glucose to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway alpha-d-xylosyl-1-6-be-to-h2o "alpha-D-xylosyl-(1->6)-be… to H2O" {
  spacing 314

  spine at 0,0 {
    alpha_d_xylosyl_1_6_beta_d_glucosyl_1_4_beta_d_g
    <-> ec_3_2_1_150 [3.2.1.150] +d_xyl_1_6_d_xyl_1_6_d_glc_4_d_glc -h2o
    xxxg_xyloglucan_oligosaccharide
    <-> ec_3_2_1_23 [3.2.1.23] +d_galactopyranose -h2o
    xlxg_xyloglucan_oligosaccharide
    <-> ec_3_6_3_18 [3.6.3.18] +h +adp +phosphate -xlxg_xyloglucan_oligosaccharide -h2o
    atp
  }

  branch from xxxg_xyloglucan_oligosaccharide side left {
    xxxg_xyloglucan_oligosaccharide
    <-> ec_3_2_1_23 [3.2.1.23] +beta_d_galactose +h2o
    xllg_xyloglucan_oligosaccharide
  }

  branch from h2o side right {
    h2o
    <-> . +neocarrabiose +neocarrabiose_sulfate
    neocarratetraose_4_o_sulfate
  }

  branch from h2o side left {
    h2o
    <-> ec_4_2_3_38 [4.2.3.38] +diphosphate +alpha_bisabolol
    2e_6e_farnesyl_diphosphate
  }

  branch from atp side right {
    atp
    <-> . +l_leucine +demethylblasticidin_s +adp +phosphate
    l_leucyl_demethyl_blasticidin_s
  }

  branch from atp side left {
    atp
    <-> . +cytosinine +3s_beta_arginine +h +adp +phosphate
    demethylblasticidin_s
  }
}
