# Ingested from Rhea. The spine follows the carbon skeleton from
# alpha-D-ribofuranose 5-phosphate to phosphate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway alpha-d-ribofuranose-to-phosphate-null "alpha-D-ribofuranose… to phosphate" {
  spacing 260

  spine at 0,0 {
    alpha_d_ribofuranose_5_phosphate
    <-> ec_2_2_1_1 [2.2.1.1] +3_amino_3_deoxy_d_fructose_6_phosphate -iminoerythrose_4_phosphate -d_sedoheptulose_7_phosphate
    h
    <-> . +aldehydo_d_ribose_5_phosphate +d_sedoheptulose_7_phosphate -d_erythrose_4_phosphate
    octulose_8_phosphate
    <-> . -h
    aldehydo_octose_8_phosphate
    <-> .
    d_erythro_d_gluco_octose_8_phosphate
    <-> . +atp -h -adp
    d_erythro_d_gluco_octose_alpha_1_8_bisphosphate
    <-> . +h2o -phosphate
    d_erythro_alpha_d_gluco_octopyranose1_phosphate
  }

  branch from h side left {
    h
    <-> ec_1_1_1_19 [1.1.1.19] +d_glucuronate +nadph +nadp
    l_gulonate
  }

  branch from h side right {
    h
    <-> ec_3_2_2_14 [3.2.2.14] +alpha_d_ribofuranose_5_phosphate +nicotinamide +h2o
    beta_nicotinamide_d_ribonucleotide
  }

  branch from adp side left {
    adp
    <-> . +h +phosphate +atp +h2o
    l_methionine_s_s_oxide
  }

  branch from adp side right {
    adp
    <-> ec_2_7_1_60 [2.7.1.60] +n_acetyl_d_mannosamine +h +atp
    n_acetyl_d_mannosamine_6_phosphate
  }

  branch from phosphate side left {
    phosphate
    <-> ec_2_4_2_1 [2.4.2.1] +7h_purine +2_deoxy_alpha_d_ribose_1_phosphate
    2_deoxynebularine
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_1_3_62 [3.1.3.62] +1d_myo_inositol_1_3_4_5_6_pentakisphosphate +h2o
    1d_myo_inositol_hexakisphosphate
  }

  branch from alpha_d_ribofuranose_5_phosphate side left {
    alpha_d_ribofuranose_5_phosphate
    <-> ec_5_3_1_6 [5.3.1.6] +h
    d_ribulose_5_phosphate
  }

  branch from alpha_d_ribofuranose_5_phosphate side right {
    alpha_d_ribofuranose_5_phosphate
    <-> . +5_6_diamino_2_4_dihydroxypyrimidine +h +h2o
    5_amino_6_5_phosphoribosylaminouracil
  }

  branch from h side left {
    h
    <-> . +7z_10z_13z_16z_docosatetraenoyl_coa +h2o +coa
    7z_10z_13z_16z_docosatetraenoate
  }

  branch from h side right {
    h
    <-> . +15z_tetracosenoyl_coa +h2o +coa
    15z_tetracosenoate
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_23 [3.6.3.23] +h +adp +phosphate +h2o
    d_alanyl_d_alanine
  }

  branch from atp side right {
    atp
    <-> . +h +adp +phosphate +h2o
    aerobactin
  }

  branch from adp side left {
    adp
    <-> . +h +phosphate +atp +h2o
    aerobactin
  }

  branch from adp side right {
    adp
    <-> ec_3_6_3_33 [3.6.3.33] +h +phosphate +atp +h2o
    cbl
  }

  branch from h2o side left {
    h2o
    <-> . +2_amino_5_oxohexanoate
    1_pyrroline_2_methyl_5_carboxylate
  }

  branch from h2o side right {
    h2o
    <-> . +deoxyflexixanthin
    dihydroxydeoxyflexixanthin
  }

  branch from phosphate side left {
    phosphate
    <-> ec_2_4_2_1 [2.4.2.1] +7h_purine +alpha_d_ribose_1_phosphate
    nebularine
  }

  branch from phosphate side right {
    phosphate
    <-> ec_2_5_1_56 [2.5.1.56] +n_acetyl_d_mannosamine +phosphoenolpyruvate +h2o
    n_acetyl_beta_neuraminate
  }
}
