# Ingested from Rhea. The spine follows the carbon skeleton from
# an L-α-D-Hep-(1→5)-[α-Kdo-(2→4)]-α-Kdo-(2→6)-lipid A(6−) to an L-α-D-Hep-(1→7)-L-α-D-Hep-(1→3)-4-O-phospho-L-α-D-Hep-(1→5)-[α-Kdo-(2→4)]-α-Kdo-(2→6)-lipid A(8−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway an-l-d-hep-1-5-kdo-to-an-l-d-hep-1-7-l-d "an L-α-D-Hep-(1→5)-[α-Kdo… to an L-α-D-Hep-(1→7)-L-α-D-…" {
  spacing 232

  spine at 0,0 {
    an_l_d_hep_1_5_kdo_2_4_kdo_2_6_lipid_a
    <-> ec_2_4_99_24 [2.4.99.24] +adp_l_glycero_d_manno_heptose -adp -hplus
    an_l_d_hep_1_3_l_d_hep_1_5_kdo_2_4_kdo_2_6_lipid
    <-> ec_2_7_1_235 [2.7.1.235] +atp -adp -hplus
    an_l_d_hep_1_3_4_o_phospho_l_d_hep_1_5_kdo_2_4_k
    <-> ec_2_4_99_25 [2.4.99.25] +adp_l_glycero_d_manno_heptose -adp -hplus
    an_l_d_hep_1_7_l_d_hep_1_3_4_o_phospho_l_d_hep_1
  }
}
