# Ingested from Rhea. The spine follows the carbon skeleton from
# benzylpenicilloate(1−) to CoA; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway benzylpenicilloate-to-coa-null "benzylpenicilloate to CoA" {
  spacing 266

  spine at 0,0 {
    benzylpenicilloate
    <-> ec_3_5_2_6 [3.5.2.6] -h2o
    penicillin_g
    <-> ec_3_5_1_11 [3.5.1.11] +h2o -2_phenylacetate
    6_aminopenicillanate
    <-> . +phenylacetyl_coa -h -coa
    penicillin_g
  }

  branch from h2o side left {
    h2o
    <-> ec_3_3_2_8 [3.3.2.8] +1s_2s_4r_limonene_1_2_diol
    4r_limonene_1alpha_2alpha_epoxide
  }

  branch from h2o side right {
    h2o
    <-> . +udp +kanosamine +h
    udp_alpha_d_kanosamine
  }

  branch from 6_aminopenicillanate side left {
    6_aminopenicillanate
    <-> ec_3_5_1_11 [3.5.1.11] +amoxicillin +h2o
    d_4_hydroxyphenylglycine
  }

  branch from 6_aminopenicillanate side right {
    6_aminopenicillanate
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    atp
  }

  branch from 2_phenylacetate side left {
    2_phenylacetate
    <-> ec_1_14_13_84 [1.14.13.84] +acetophenone +o2 +nadph +h2o
    nadp
  }

  branch from 2_phenylacetate side right {
    2_phenylacetate
    <-> ec_3_1_1_1 [3.1.1.1] +phenol +h2o
    acetate
  }

  branch from h side left {
    h
    <-> ec_2_3_1_280 [2.3.1.280] +acetyl_coa +3_aminopropyl_phosphonic_acid +coa
    2_acetamidopropyl_phosphonate
  }

  branch from h side right {
    h
    <-> . +n_acetyl_d_glucosaminyl_n_acetyl_tunicaminyl_ura +udp +udp_n_acetyl_alpha_d_glucosamine
    n_acetyl_tunicaminyl_uracil
  }

  branch from coa side left {
    coa
    <-> ec_2_3_1_16 [2.3.1.16] +z_3_oxotetradec_7_enoyl_coa +cis_dodec_5_enoyl_coa
    acetyl_coa
  }

  branch from coa side right {
    coa
    <-> . +benzoyl_coa +z_3_hydroxypropyl_glucosinolate
    glucomalcommin
  }

  branch from h2o side left {
    h2o
    <-> . +glucose +s_4_hydroxymandelonitrile
    dhurrin
  }

  branch from h2o side right {
    h2o
    <-> . +4_nitroso_2_6_dinitrotoluene +nadp +h +nadph
    2_4_6_trinitrotoluene
  }

  branch from 2_phenylacetate side left {
    2_phenylacetate
    <-> ec_6_2_1_13 [6.2.1.13] +phenylacetyl_coa +phosphate +atp +coa
    adp
  }

  branch from phenylacetyl_coa side right {
    phenylacetyl_coa
    <-> ec_1_17_5_1 [1.17.5.1] +ubiquinone_8 +h2o +phenylglyoxylyl_coa
    ubiquinol_8
  }

  branch from phenylacetyl_coa side left {
    phenylacetyl_coa
    <-> ec_1_17_5_1 [1.17.5.1] +ubiquinone_10 +h2o +phenylglyoxylyl_coa
    ubiquinol_10
  }

  branch from h side right {
    h
    <-> . +co2 +2_oxopentanoate
    3_ethyl_2_oxosuccinate
  }

  branch from h side left {
    h
    <-> . +trimethylaminoacetone +co2
    3_dehydrocarnitine
  }

  branch from coa side right {
    coa
    <-> . +acetyl_coa +n_3_aminopropyl_hydroxylamine +h
    n_3_aminopropyl_n_hydroxyacetamide
  }

  branch from coa side left {
    coa
    <-> . +trans_4_coumaroyl_coa +r_3_4_hydroxyphenyl_lactate
    4_coumaroyl_4_hydroxyphenyllactate
  }
}
