# Ingested from Rhea. The spine follows the carbon skeleton from
# benzene to 4-methylcatechol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway benzene-to-4-methylcatechol "benzene to 4-methylcatechol" {
  spacing 322

  spine at 0,0 {
    benzene
    <-> ec_1_14_12_3 [1.14.12.3] +nadh +o2 +hplus -nad
    cis_cyclohexa_3_5_diene_1_2_diol
    <-> ec_1_3_1_19 [1.3.1.19] +nad -nadh -hplus
    catechol
    <-> ec_1_13_11_2 [1.13.11.2] +o2 -hplus
    2z_4e_2_hydroxy_6_oxohexa_2_4_dienoate
    <-> ec_3_7_1_9 [3.7.1.9] +h2o -formate -hplus
    2_oxopent_4_enoate
    <-> . +h +acetate -h2o
    2_hydroxy_5_methyl_6_oxohexa_2_4_dienoate
    <-> ec_1_13_11_2 [1.13.11.2] +h -4_methylcatechol
    o2
  }

  branch from catechol side left {
    catechol
    <-> ec_1_14_14_20 [1.14.14.20] +fadh2 +o2 +fad +h2o +hplus
    phenol
  }

  branch from catechol side right {
    catechol
    <-> . +2_ethoxyphenol +fadh2 +o2 +fad +h2o +hplus
    acetaldehyde
  }

  branch from 2_oxopent_4_enoate side left {
    2_oxopent_4_enoate
    <-> .
    2_keto_4_pentenoate
  }

  branch from 2_oxopent_4_enoate side right {
    2_oxopent_4_enoate
    <-> . +h2o
    s_4_hydroxy_2_oxopentanoate
  }

  branch from formate side left {
    formate
    <-> ec_4_1_99_5 [4.1.99.5] +octadecanal +nadph +o2 +hplus +nadp +h2o
    heptadecane
  }

  branch from formate side right {
    formate
    <-> ec_1_14_14_154 [1.14.14.154] +14_methyl_steroid +fmnh2 +o2 +fmn +h2o +hplus
    14_steroid
  }

  branch from 2_hydroxy_5_methyl_6_oxohexa_2_4_dienoate side left {
    2_hydroxy_5_methyl_6_oxohexa_2_4_dienoate
    <-> . +o2 +h
    3_methylcatechol
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_21 [3.6.3.21] +h +adp +phosphate +atp
    l_histidine
  }

  branch from h2o side left {
    h2o
    <-> . +2_oxoglutarate +nh4
    4_oxoglutaramate
  }

  branch from o2 side right {
    o2
    <-> ec_1_14_15_4 [1.14.15.4] +h +21_hydroxyprogesterone +nadph +corticosterone +h2o
    nadp
  }

  branch from o2 side left {
    o2
    <-> . +h +21_hydroxyprogesterone +nadph +nadp +h2o
    aldosterone
  }

  branch from 4_methylcatechol side right {
    4_methylcatechol
    <-> ec_1_14_12_14 [1.14.12.14] +nadh +toluene_4_sulfonate +o2 +nad
    sulfite
  }

  branch from 4_methylcatechol side left {
    4_methylcatechol
    <-> ec_1_13_11_1 [1.13.11.1] +o2
    3_methyl_cis_cis_muconic_acid
  }
}
