# Ingested from Rhea. The spine follows the carbon skeleton from
# benzoate to 2,3',4,6-tetrahydroxybenzophenone(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway benzoate-to-2-3-4-6-tetrahydroxybenz "benzoate to 2,3',4,6-tetrahydroxybenz…" {
  spacing 244

  spine at 0,0 {
    benzoate
    <-> . +atp +hplus -ppi
    benzoyl_amp
    <-> . +coa -amp -hplus
    benzoyl_coa
    <-> ec_1_14_13_58 [1.14.13.58] +nadph +o2 +hplus -nadp -h2o
    3_hydroxybenzoyl_coa
    <-> ec_2_3_1_151 [2.3.1.151] +malonyl-coa +hplus -co2 -coa
    2_3_4_6_tetrahydroxybenzophenone
  }

  branch from benzoyl_coa side left {
    benzoyl_coa
    <-> . +ethanol +coa
    benzyl_acetate
  }

  branch from benzoyl_coa side right {
    benzoyl_coa
    <-> . +hexan_2_ol +coa
    hexan_2_yl_benzoate
  }
}
