# Ingested from Rhea. The spine follows the carbon skeleton from
# biotinate sulfoxide(1−) to 3-cyanopyridine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway biotinate-sulfoxide-to-3-cyanopyridine "biotinate sulfoxide to 3-cyanopyridine" {
  spacing 256

  spine at 0,0 {
    biotinate_sulfoxide
    <-> . +nadh +hplus -nad -h2o
    biotinate
    <-> ec_6_3_4_15 [6.3.4.15] +l_lysinium +atp -amp -ppi -hplus
    biotinyl_l_lysine
    <-> . +nad +h2o -nicotinamide -l_lysinium
    2_o_biotinyl_adp_d_ribose
    <-> . +nicotinamide -h2o
    3_cyanopyridine
  }

  branch from biotinate side left {
    biotinate
    <-> . +atp +hplus +ppi
    biotinyl_5_amp
  }

  branch from ppi side right {
    ppi
    <-> ec_4_2_3_25 [4.2.3.25] +gpp +h2o
    s_linalool
  }

  branch from nicotinamide side left {
    nicotinamide
    <-> . +n6_propanoyl_l_lysine +nad +h2o +l_lysinium
    3_o_propanoyl_adp_d_ribose
  }

  branch from l_lysinium side right {
    l_lysinium
    <-> ec_1_4_3_13 [1.4.3.13] +o2 +h2o +h2o2 +nh3
    l_allysine
  }
}
