# Ingested from Rhea. The spine follows the carbon skeleton from
# butanal to 3-oxopentanoate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway butanal-to-3-oxopentanoate-null "butanal to 3-oxopentanoate" {
  spacing 208

  spine at 0,0 {
    butanal
    <-> ec_1_1_1_71 [1.1.1.71] +h +nadph -butan_2_ol
    nadp
    <-> . +butan_2_ol +iron -fe2 -hplus
    butan_2_one
    <-> ec_6_4_1_6 [6.4.1.6] +hco3 +atp +h2o -amp -pi -hplus
    3_oxopentanoate
  }

  branch from h side left {
    h
    <-> . +d_glucuronate +propranolol +h2o
    propranolol_glucuronide
  }

  branch from h side right {
    h
    <-> . +cmp +phosphatidylserine_dihexadec_9_enoyl_n_c16_1 +l_serine
    cdp_1_2_di_9z_hexadecenoyl_sn_glycerol
  }
}
