# Ingested from Rhea. The spine follows the carbon skeleton from
# carbamoyl phosphate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway carbamoyl-phosphate-to-h2o "carbamoyl phosphate to H2O" {
  spacing 180

  spine at 0,0 {
    carbamoyl_phosphate
    <-> . -cyanate -phosphate
    h
    <-> ec_4_2_1_104 [4.2.1.104] +cyanate +h2o
    carbamate
    <-> ec_3_5_1_110 [3.5.1.110] +h +z_2_methyl_3_aminoperacrylic_acid -h2o
    z_2_methylureidoperacrylic_acid
  }
}
