# Ingested from Rhea. The spine follows the carbon skeleton from
# chloroacetaldehyde to NAD(+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway chloroacetaldehyde-to-nad-null "chloroacetaldehyde to NAD" {
  spacing 292

  spine at 0,0 {
    chloroacetaldehyde
    <-> ec_1_1_2_8 [1.1.2.8] +h +pyrroloquinoline_quinol -pyrroloquinoline_quinone
    2_chloroethanol
    <-> . +myo_inositol +pyrroloquinoline_quinone -pyrroloquinoline_quinol -2d_2_3_5_4_6_pentahydroxycyclohexanone
    h
    <-> ec_1_1_1_18 [1.1.1.18] +nadh +2d_2_3_5_4_6_pentahydroxycyclohexanone -nad
    myo_inositol
  }

  branch from h side left {
    h
    <-> . +indole_carboxyl_tetrahydro_thiazole +h2o
    s_indole_l_cysteine
  }

  branch from h side right {
    h
    <-> . +4_methoxyglucobrassicin +h2o +beta_d_glucose
    4_methoxy_3_indolylmethyl_glucosinolate_aglycone
  }

  branch from myo_inositol side left {
    myo_inositol
    <-> ec_3_1_3_25 [3.1.3.25] +phosphate +h2o
    d_glucose_6_phosphate
  }

  branch from myo_inositol side right {
    myo_inositol
    <-> . +5_dehydro_2_deoxy_d_gluconate +h +nadph
    nadp
  }

  branch from nad side left {
    nad
    <-> ec_1_6_5_2 [1.6.5.2] +nadh +h +2_decaprenyl_6_methoxy_1_4_benzoquinone
    2_decaprenyl_6_methoxyhydroquinone
  }

  branch from nad side right {
    nad
    <-> ec_1_6_5_2 [1.6.5.2] +2_methoxy_3_methyl_6_all_trans_nonaprenylhydroqu +nadh +h
    2_nonaprenyl_3_methyl_6_methoxy_1_4_benzoquinone
  }

  branch from h side left {
    h
    <-> . +terpinene
    alpha_terpinyl_cation
  }

  branch from h side right {
    h
    <-> . +alpha_terpinyl_cation
    phellandrene
  }

  branch from myo_inositol side left {
    myo_inositol
    <-> . +h +nadph +nadp
    scyllo_inosose
  }

  branch from myo_inositol side right {
    myo_inositol
    <-> . +phosphate +h2o
    1d_myo_inositol_hexakisphosphate
  }

  branch from nadh side left {
    nadh
    <-> ec_1_6_5_2 [1.6.5.2] +demethylmenaquinone_7 +h +nad
    2_demethylmenaquinol_7
  }

  branch from nadh side right {
    nadh
    <-> ec_1_6_5_2 [1.6.5.2] +2_demethylmenaquinone_9 +h +nad
    2_demethylmenaquinol_9
  }

  branch from nad side left {
    nad
    <-> ec_1_6_5_2 [1.6.5.2] +nadh +2_demethylmenaquinone_10 +h
    2_demethylmenaquinol_10
  }

  branch from nad side right {
    nad
    <-> ec_1_6_5_2 [1.6.5.2] +nadh +2_demethylmenaquinone_11 +h
    2_demethylmenaquinol_11
  }
}
