# Ingested from Rhea. The spine follows the carbon skeleton from
# CMP to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway cmp-to-h2o "CMP to H2O" {
  spacing 340

  spine at 0,0 {
    cmp
    <-> ec_2_4_99_13 [2.4.99.13] +h +alpha_kdo_2_4_alpha_kdo_2_6_lipid_iva_p_putida -alpha_kdo_2_6_lipid_iva_p_putida
    cmp_3_deoxy_alpha_d_manno_octulosonic_acid
    <-> ec_2_4_99_13 [2.4.99.13] +alpha_kdo_2_6_lipid_iva_e_coli -alpha_kdo_2_4_alpha_kdo_2_6_lipid_iva_e_coli -h
    cmp
    <-> . +alpha_kdo_2_4_alpha_kdo_2_6_lipid_iva_e_coli +h +adp +phosphate -atp -h2o
    alpha_kdo_2_4_alpha_kdo_2_6_lipid_iva_e_coli
  }

  branch from cmp_3_deoxy_alpha_d_manno_octulosonic_acid side left {
    cmp_3_deoxy_alpha_d_manno_octulosonic_acid
    <-> ec_2_4_99_12 [2.4.99.12] +cmp +h +alpha_kdo_2_6_lipid_iva_p_putida
    lipid_iva_p_putida
  }

  branch from cmp_3_deoxy_alpha_d_manno_octulosonic_acid side right {
    cmp_3_deoxy_alpha_d_manno_octulosonic_acid
    <-> ec_2_4_99_12 [2.4.99.12] +cmp +alpha_kdo_2_6_lipid_iva_brucella +h
    lipid_iva_brucella
  }

  branch from cmp side left {
    cmp
    <-> ec_2_7_8_5 [2.7.8.5] +phosphatidylglycerophosphate_dioctadecanoyl_n_c1 +cdp_1_2_dioctadecanoylglycerol
    sn_glycerol_3_phosphate
  }

  branch from cmp side right {
    cmp
    <-> ec_3_6_1_26 [3.6.1.26] +dimyristoyl_phosphatidic_acid +h2o
    cdp_1_2_ditetradecanoylglycerol
  }

  branch from h side left {
    h
    <-> ec_1_3_1_33 [1.3.1.33] +chlorophyllide_a +nadp +protochlorophyllide
    nadph
  }

  branch from h side right {
    h
    <-> ec_2_3_2_15 [2.3.2.15] +glu_cys_n_gly +glutathione +glu_cys_n_1_gly
    glycine
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_14 [3.6.3.14] +h +adp +phosphate +h2o
    pmf
  }

  branch from atp side right {
    atp
    <-> . +h +adp +phosphate +h2o
    butane_1_sulfonate
  }

  branch from h2o side left {
    h2o
    <-> ec_1_3_3_9 [1.3.3.9] +h +loganate +o2 +nadph +nadp
    secologanate
  }

  branch from h2o side right {
    h2o
    <-> . +15_stemmadenine
    tabersonine
  }
}
