# Ingested from Rhea. The spine follows the carbon skeleton from
# Cobyrinate to NADPH; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway cobyrinate-to-nadph-null "Cobyrinate to NADPH" {
  spacing 152

  spine at 0,0 {
    cobyrinate
    <-> .
    cobalt_precorrin_8
    <-> . +s_adenosyl_l_homocysteine +co2 +h -cobalt_dihydro_precorrin_6
    s_adenosyl_l_methionine
    <-> . +cobalt_dihydro_precorrin_6 +nadp -h -nadph
    cobalt_precorrin_6
  }
}
