# Ingested from Rhea. The spine follows the carbon skeleton from
# coenzyme B(3−) to dTDP(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway coenzyme-b-to-dtdp "coenzyme B to dTDP" {
  spacing 272

  spine at 0,0 {
    coenzyme_b
    <-> ec_1_8_98_6 [1.8.98.6] +coenzyme_m +di_sulfido_diiron +co2 -formate -di_sulfido_diiron
    com_s_s_cob
    <-> . +ctp +formate +hplus -co2 -h2o
    dctp
    <-> ec_3_5_4_30 [3.5.4.30] +h2o -nh3 -ppi
    dump
    <-> ec_2_1_1_45 [2.1.1.45] +methylene_thf -dtmp
    dhf
    <-> . +dtmp +gtp -gdp
    dtdp
  }

  branch from di_sulfido_diiron side left {
    di_sulfido_diiron
    <-> ec_1_14_15_9 [1.14.15.9] +spirilloxanthin +di_sulfido_diiron +o2 +hplus +h2o
    2_oxospirilloxanthin
  }

  branch from dctp side right {
    dctp
    <-> . +h2o +pi +hplus
    2_deoxycytosine_5_monophosphate
  }

  branch from nh3 side left {
    nh3
    <-> ec_4_3_1_24 [4.3.1.24] +l_phenylalanine
    trans_cinnamate
  }

  branch from ppi side right {
    ppi
    <-> ec_3_1_7_6 [3.1.7.6] +fpp +h2o
    2_trans_6_trans_farnesol
  }
}
