# Ingested from Rhea. The spine follows the carbon skeleton from
# coniferin to formaldehyde; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway coniferin-to-formaldehyde "coniferin to formaldehyde" {
  spacing 192

  spine at 0,0 {
    coniferin
    <-> ec_3_2_1_126 [3.2.1.126] +h2o -glucose
    coniferol
    <-> ec_1_1_1_194 [1.1.1.194] +nadp -nadph -hplus
    coniferyl_aldehyde
    <-> ec_1_2_1_68 [1.2.1.68] +nadp +h2o -nadph -hplus
    trans_ferulate
    <-> ec_4_1_1_102 [4.1.1.102] +hplus -co2
    2_methoxy_4_vinylphenol
    <-> ec_1_13_11_94 [1.13.11.94] +o2 -formaldehyde
    vanillin
  }
}
