# Ingested from Rhea. The spine follows the carbon skeleton from
# D-allothreonine zwitterion to L-methionine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-allothreonine-to-l-methionine "D-allothreonine to L-methionine" {
  spacing 294

  spine at 0,0 {
    d_allothreonine
    <-> ec_4_1_2_42 [4.1.2.42] -glycine
    acetaldehyde
    <-> ec_1_2_1_4 [1.2.1.4] +nadp +h2o -nadph -hplus
    acetate
    <-> ec_1_1_1_319 [1.1.1.319] +trans_anol +nadp -nadph
    trans_coumaryl_acetate
    <-> ec_1_1_1_318 [1.1.1.318] +nadph -acetate -nadp
    chavicol
    <-> ec_2_1_1_146 [2.1.1.146] +sam -sah -hplus
    estragole
    <-> ec_2_1_1_146 [2.1.1.146] +s_adenosyl_l_homocysteine +h -chavicol
    s_s_adenosyl_l_methionine
    <-> ec_2_5_1_63 [2.5.1.63] +fluoride -l_methionine
    5_deoxy_5_fluoroadenosine
  }

  branch from glycine side left {
    glycine
    <-> ec_3_5_1_58 [3.5.1.58] +n_benzyloxycarbonylglycinate +h2o +hplus +co2
    benzyl_alcohol
  }

  branch from glycine side right {
    glycine
    <-> ec_3_5_3_2 [3.5.3.2] +guanidinoacetic_acid +h2o
    urea
  }

  branch from acetate side left {
    acetate
    <-> ec_3_5_1_108 [3.5.1.108] +udp_3_o_3r_hydroxyacyl_n_acetyl_d_glucosamine +h2o
    udp_3_o_3r_hydroxyacyl_d_glucosamine
  }

  branch from acetate side right {
    acetate
    <-> . +h2o +h2o2 +hplus
    peracetic_acid
  }

  branch from trans_coumaryl_acetate side left {
    trans_coumaryl_acetate
    <-> ec_2_3_1_224 [2.3.1.224] +acetyl_coa +trans_p_coumaryl_alcohol
    coa
  }

  branch from trans_coumaryl_acetate side right {
    trans_coumaryl_acetate
    <-> . +h2o +h +acetate
    trans_p_coumaryl_alcohol
  }

  branch from chavicol side left {
    chavicol
    <-> ec_3_2_1_161 [3.2.1.161] +d_apiofuranosyl_1_6_d_glucopyranose +h2o
    furcatin
  }

  branch from acetate side right {
    acetate
    <-> ec_1_2_2_2 [1.2.2.2] +ubiquinone_8 +pyruvate +h2o +ubiquinol_8
    co2
  }

  branch from acetate side left {
    acetate
    <-> . +l_asparagine +h +h2o
    n_acetyl_l_asparagine
  }

  branch from nadp side right {
    nadp
    <-> . +h +25r_3alpha_7alpha_12alpha_trihydroxy_5beta_chol +nadph +h2o
    25r_3alpha_7alpha_12alpha_trihydroxy_5beta_chol
  }

  branch from nadp side left {
    nadp
    <-> ec_1_14_14_1 [1.14.14.1] +4_hydroxytolbutamide +h2o +h +o2 +nadph
    tolbutamide
  }

  branch from sah side right {
    sah
    <-> ec_2_1_1_70 [2.1.1.70] +8_hydroxyfurocoumarin +sam +hplus
    8_methoxyfurocoumarin
  }

  branch from sah side left {
    sah
    <-> ec_2_1_1_100 [2.1.1.100] +s_2e_6e_farnesyl_l_cysteinate +sam
    s_2e_6e_farnesyl_l_cysteine_methyl_ester
  }

  branch from s_s_adenosyl_l_methionine side right {
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_49 [2.1.1.49] +s_adenosyl_l_homocysteine +h +n_methylpyrazole
    1h_pyrazole
  }

  branch from s_s_adenosyl_l_methionine side left {
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_11 [2.1.1.11] +s_adenosyl_l_homocysteine +magnesium_protoporphyrin_monomethyl_ester
    magnesium_protoporphyrin
  }

  branch from l_methionine side right {
    l_methionine
    <-> ec_3_6_3_22 [3.6.3.22] +h +adp +phosphate +h2o
    atp
  }

  branch from l_methionine side left {
    l_methionine
    <-> . +diphosphate +indol_3_yl_acetyl_l_methionine +h +amp +atp
    indol_3_yl_acetate
  }
}
