# Ingested from Rhea. The spine follows the carbon skeleton from
# D-arabinitol to N6-acetyl-L-lysine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-arabinitol-to-n6-acetyl-l-lysine "D-arabinitol to N6-acetyl-L-lysine" {
  spacing 208

  spine at 0,0 {
    d_arabinitol
    <-> ec_1_1_1_287 [1.1.1.287] +nadp -nadph -hplus
    d_ribulose
    <-> ec_2_7_1_16 [2.7.1.16] +atp -adp -hplus
    ru5p
    <-> ec_5_1_3_1 [5.1.3.1]
    x5p
    <-> ec_4_1_2_9 [4.1.2.9] +pi -g3p -h2o
    acetyl_phosphate
    <-> ec_2_3_1_32 [2.3.1.32] +l_lysinium -pi -hplus
    n6_acetyl_l_lysine
  }
}
