# Ingested from Rhea. The spine follows the carbon skeleton from
# β-D-galactosyl-N-(dodecanoyl)sphingosine to FMN(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-galactosyl-n-dodecan-to-fmn "β-D-galactosyl-N-(dodecan… to FMN" {
  spacing 152

  spine at 0,0 {
    d_galactosyl_n_dodecanoyl_sphingosine
    <-> . +cholesterol -n_dodecanoylsphingosine
    cholesteryl_d_galactoside
    <-> . +n_dodecanoylsphingosine +h2o -sphingosine
    dodecanoate
    <-> . +fmnh2 +o2 -fmn -h2o -hplus
    9_hydroxylaurate
  }

  branch from cholesteryl_d_galactoside side left {
    cholesteryl_d_galactoside
    <-> . +n_acyl_d_galactosylsphingosine +cholesterol
    n_acylsphingosine
  }

  branch from n_dodecanoylsphingosine side right {
    n_dodecanoylsphingosine
    <-> . +d_glucosyl_n_dodecanoyl_sphingosine +cholesterol
    cholesteryl_d_glucoside
  }

  branch from fmn side left {
    fmn
    <-> ec_1_14_19_73 [1.14.19.73] +s_scoulerine +fmnh2 +o2 +h2o +hplus
    s_nandinine
  }
}
