# Ingested from Rhea. The spine follows the carbon skeleton from
# β-D-GalNAc-(1→3)-α-D-Gal-(1→3)-[α-L-Fuc-(1→2)]-β-D-Gal-(1→4)-β-D-GlcNAc to β-D-galactosyl-(1→3)-[N-acetyl-β-D-glucosaminyl-(1→6)]-N-acetyl-α-D-galactosaminide; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-galnac-1-3-d-gal-to-d-galactosyl-1-3-n-a "β-D-GalNAc-(1→3)-α-D-Gal-… to β-D-galactosyl-(1→3)-[N-a…" {
  spacing 152

  spine at 0,0 {
    d_galnac_1_3_d_gal_1_3_l_fuc_1_2_d_gal_1_4_d_gl
    <-> . +h2o -n_acetyl_d_galactosamine
    d_gal_1_3_l_fuc_1_2_d_gal_1_4_d_glcnac
    <-> . +h2o -d_galactopyranose
    l_fucosyl_1_2_d_galactosyl_1_3_n_acetyl_d_gluco
    <-> . +h2o -l_fucopyranose
    d_galactosyl_1_3_n_acetyl_d_galactosaminide
    <-> . +udpglcnac -udp -hplus
    d_galactosyl_1_3_n_acetyl_d_glucosaminyl_1_6_n
  }

  branch from n_acetyl_d_galactosamine side left {
    n_acetyl_d_galactosamine
    <-> ec_3_2_1_217 [3.2.1.217] +o_n_acetyl_d_galactosaminyl_l_serine +h2o
    l_serine
  }

  branch from l_fucosyl_1_2_d_galactosyl_1_3_n_acetyl_d_gluco side right {
    l_fucosyl_1_2_d_galactosyl_1_3_n_acetyl_d_gluco
    <-> . +udp_d_galactose +udp +hplus
    d_gal_1_3_l_fuc_1_2_d_gal_1_3_d_glcnac
  }

  branch from d_galactosyl_1_3_n_acetyl_d_galactosaminide side left {
    d_galactosyl_1_3_n_acetyl_d_galactosaminide
    <-> . +gdp_l_fucose +gdp +hplus
    l_fuc_1_2_d_gal_1_3_d_galnac
  }
}
