# Ingested from Rhea. The spine follows the carbon skeleton from
# α-D-GalNAc-(1→3)-[α-L-Fuc-(1→2)]-β-D-Gal-(1→3)-α-D-GalNAc-(1→3)-[α-L-Fuc-(1→2)]-β-D-Gal-(1→4)-β-D-GlcNAc to α-L-fucosyl-(1→2)-β-D-galactosyl-(1→4)-[α-L-fucosyl-(1→3)]-N-acetyl-β-D-glucosaminide; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-galnac-1-3-l-fuc-to-l-fucosyl-1-2-d-gal "α-D-GalNAc-(1→3)-[α-L-Fuc… to α-L-fucosyl-(1→2)-β-D-gal…" {
  spacing 194

  spine at 0,0 {
    d_galnac_1_3_l_fuc_1_2_d_gal_1_3_d_galnac_1_3_l
    <-> . +h2o -n_acetyl_d_galactosamine
    l_fuc_1_2_d_gal_1_3_d_galnac_1_3_l_fuc_1_2_d_ga
    <-> . +h2o -l_fucopyranose
    d_gal_1_3_d_galnac_1_3_l_fuc_1_2_d_gal_1_4_d_gl
    <-> . +h2o -d_galactopyranose
    d_galnac_1_3_l_fuc_1_2_d_gal_1_4_d_glcnac
    <-> . +h2o -n_acetyl_d_galactosamine
    l_fucosyl_1_2_d_galactosyl_1_4_n_acetyl_d_gluco
    <-> . +gdp_l_fucose -gdp -hplus
    l_fucosyl_1_2_d_galactosyl_1_4_l_fucosyl_1_3_n
  }

  branch from n_acetyl_d_galactosamine side left {
    n_acetyl_d_galactosamine
    <-> . +o2 +h2o2
    n_acetyl_d_galactosamino_1_5_lactone
  }

  branch from n_acetyl_d_galactosamine side right {
    n_acetyl_d_galactosamine
    <-> ec_3_2_1_217 [3.2.1.217] +o_n_acetyl_d_galactosaminyl_l_serine +h2o
    l_serine
  }

  branch from l_fucopyranose side left {
    l_fucopyranose
    <-> ec_3_2_1_51 [3.2.1.51] +n_acetyl_d_hexosamine +h2o
    l_fucp_1_3_d_glcpnac
  }

  branch from d_galnac_1_3_l_fuc_1_2_d_gal_1_4_d_glcnac side right {
    d_galnac_1_3_l_fuc_1_2_d_gal_1_4_d_glcnac
    <-> . +l_fucosyl_1_2_d_galactosyl_1_4_n_acetyl_d_gluco +udp +hplus
    udp_n_acetyl_d_galactosamine
  }

  branch from d_galactopyranose side left {
    d_galactopyranose
    <-> . +d_galp_1_6_d_manp_1_4_d_manp_1_4_d_manp +h2o
    d_manp_1_4_d_manp_1_4_d_manp
  }

  branch from d_galactopyranose side right {
    d_galactopyranose
    <-> . +d_manp_1_4_d_galp_1_6_d_manp_1_4_d_manp_1_4_d_m +h2o
    d_manp_1_4_d_manp_1_4_d_manp_1_4_d_manp
  }

  branch from l_fucosyl_1_2_d_galactosyl_1_4_n_acetyl_d_gluco side left {
    l_fucosyl_1_2_d_galactosyl_1_4_n_acetyl_d_gluco
    <-> . +udp_d_galactose +udp +hplus
    d_gal_1_3_l_fuc_1_2_d_gal_1_4_d_glcnac
  }
}
