# Ingested from Rhea. The spine follows the carbon skeleton from
# β-D-Gal-(1→4)-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-β-D-Glc-(1↔1')-Cer to β-D-Gal-(1→4)-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-[α-L-Fuc-(1→3)]-β-D-GlcNAc-(1→3)-β-D-Gal-(1→4)-β-D-Glc-Cer; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-gal-1-4-d-glcnac-to-d-gal-1-4-d-glcnac-58464 "β-D-Gal-(1→4)-β-D-GlcNAc-… to β-D-Gal-(1→4)-β-D-GlcNAc-…" {
  spacing 188

  spine at 0,0 {
    d_gal_1_4_d_glcnac_1_3_d_gal_1_4_d_glc_1_1_cer
    <-> . +udpglcnac -udp -hplus
    n_acetyl_d_glucosaminyl_1_3_d_galactosyl_1_4_n_a
    <-> . +udp_d_galactose -udp -hplus
    d_gal_1_4_d_glcnac_1_3_d_gal_1_4_d_glcnac_1_3_d
    <-> . +gdp_l_fucose -gdp -hplus
    d_gal_1_4_d_glcnac_1_3_d_gal_1_4_l_fuc_1_3_d_gl
  }

  branch from udpglcnac side left {
    udpglcnac
    <-> . +d_galp_1_3_d_galpnac_1_3_d_galp_1_4_d_galp_1_4 +udp +hplus
    d_gal_1_3_d_glcnac_1_6_d_galnac_1_3_d_gal_1_4_d
  }

  branch from udpglcnac side right {
    udpglcnac
    <-> . +n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_glcnac +udp +hplus
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_glcnac_chebi_233673
  }

  branch from udp_d_galactose side left {
    udp_d_galactose
    <-> . +an_n4_neu5ac_2_3_d_gal_1_4_d_glcnac_1_2_d_man_1 +udp +hplus
    n4_neu5ac_2_3_d_gal_1_4_d_glcnac_1_2_d_man_1_3_d
  }

  branch from udp_d_galactose side right {
    udp_d_galactose
    <-> . +n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_4_neu5ac_2 +udp +hplus
    n4_d_gal_1_4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_4
  }

  branch from gdp_l_fucose side left {
    gdp_l_fucose
    <-> . +n_acetyl_neuraminosyl_2_3_d_galactosyl_1_4_n_ace +gdp +hplus
    n_acetyl_neuraminosyl_2_3_d_galactosyl_1_4_l_fuc
  }

  branch from gdp_l_fucose side right {
    gdp_l_fucose
    <-> . +n_acetylneuraminyl_2_3_d_galactosyl_1_4_n_acety +gdp +hplus
    n_acetylneuraminosyl_2_3_d_galactosyl_1_4_l_fuc
  }
}
