# Ingested from Rhea. The spine follows the carbon skeleton from
# D-glucaro-1,4-lactone(1−) to O-sinapoylglucarolactone; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-glucaro-1-4-lactone-to-o-sinapoylglucarolacton "D-glucaro-1,4-lactone to O-sinapoylglucarolactone" {
  spacing 294

  spine at 0,0 {
    d_glucaro_1_4_lactone
    <-> . +h2o -h
    d_glucarate
    <-> . +h -h2o
    d_glucaro_1_5_lactone
    <-> ec_2_3_1_132 [2.3.1.132] +h +e_sinapoyl_coa -o_sinapoylglucarolactone
    coa
  }

  branch from d_glucarate side left {
    d_glucarate
    <-> ec_4_2_1_40 [4.2.1.40] +h2o
    2_dehydro_3_deoxy_d_glucarate
  }

  branch from d_glucarate side right {
    d_glucarate
    <-> ec_1_1_1_203 [1.1.1.203] +nadh +h +nad +h2o
    beta_d_glucuronate
  }

  branch from h side left {
    h
    <-> . +co2 +c31_phthiodiolenone_a
    c32_carboxyphthiodiolenone
  }

  branch from h side right {
    h
    <-> . +c36_phenolphthiodiolone_a +nadph +nadp
    c36_phenolphthiotriol_a
  }

  branch from d_glucaro_1_5_lactone side left {
    d_glucaro_1_5_lactone
    <-> ec_1_1_1_203 [1.1.1.203] +nad +nadh +hplus
    d_glucuronate
  }

  branch from h2o side right {
    h2o
    <-> . +2_aminobenzoylacetate +h +o2 +nadph +nadp
    2_hydroxylamino_benzoylacetate
  }

  branch from h2o side left {
    h2o
    <-> . +beta_d_galactose +d_fructofuranose
    lactulose
  }

  branch from coa side right {
    coa
    <-> . +acetyl_coa +tryptoquialanol
    tryptoquialanine_a
  }

  branch from coa side left {
    coa
    <-> . +benzoyl_coa +pyrrothine
    benzoyl_pyrrothine
  }
}
