# Ingested from Rhea. The spine follows the carbon skeleton from
# β-D-Manp-(1→4)-D-GlcpNAc to N-acetyl-α-D-galactosamine 1-phosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-manp-1-4-d-glcpnac-to-n-acetyl-d-galactosamin "β-D-Manp-(1→4)-D-GlcpNAc to N-acetyl-α-D-galactosamin…" {
  spacing 280

  spine at 0,0 {
    d_manp_1_4_d_glcpnac
    <-> ec_2_4_1_320 [2.4.1.320] +pi -n_acetyl_d_glucosamine
    d_mannose_1_phosphate
    <-> ec_5_4_2_8 [5.4.2.8]
    d_mannopyranose_6_phosphate
    <-> ec_5_3_1_8 [5.3.1.8]
    d_fructofuranose_6_phosphate
    <-> ec_2_6_1_16 [2.6.1.16] +glutamine -glutamate
    glucosamine6p
    <-> ec_5_1_3_42 [5.1.3.42]
    d_galactosamine_6_phosphate
    <-> ec_5_4_2_13 [5.4.2.13]
    d_galactosamine_1_phosphate
    <-> ec_2_3_1_276 [2.3.1.276] +acetyl_coa -coa -hplus
    n_acetyl_d_galactosamine_1_phosphate
  }

  branch from d_mannose_1_phosphate side left {
    d_mannose_1_phosphate
    <-> ec_2_7_7_69 [2.7.7.69] +gdp_d_glucose +gdp_d_mannose
    g1p
  }

  branch from n_acetyl_d_glucosamine side right {
    n_acetyl_d_glucosamine
    <-> ec_2_7_1_162 [2.7.1.162] +atp +adp +hplus
    n_acetyl_d_glucosamine_1_phosphate
  }

  branch from d_mannopyranose_6_phosphate side left {
    d_mannopyranose_6_phosphate
    <-> ec_2_7_1_191 [2.7.1.191] +d_mannopyranose +n_phosphonato_l_histidine
    l_histidine
  }

  branch from glucosamine6p side right {
    glucosamine6p
    <-> ec_2_7_1_147 [2.7.1.147] +adp +amp +hplus
    2_ammonio_2_deoxy_d_glucopyranose
  }
}
