# Ingested from Rhea. The spine follows the carbon skeleton from
# D-threonate to (4-alkanoyl-5-oxo-2,5-dihydrofuran-3-yl)methyl phosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-threonate-to-4-alkanoyl-5-oxo-2-5-dih "D-threonate to (4-alkanoyl-5-oxo-2,5-dih…" {
  spacing 212

  spine at 0,0 {
    d_threonate
    <-> ec_2_7_1_219 [2.7.1.219] +atp -adp -hplus
    4_o_phosphonato_d_threonate
    <-> ec_1_1_1_408 [1.1.1.408] +nad -co2 -nadh
    dhap
    <-> . +o_s_3_oxo_medium_chain_acyl_pantetheine_4_phosph -holo-acp
    2_oxo_3_phosphooxy_propyl_medium_chain_3_oxoalka
    <-> . -h2o
    4_alkanoyl_5_oxo_2_5_dihydrofuran_3_yl_methyl_p
  }

  branch from 4_o_phosphonato_d_threonate side left {
    4_o_phosphonato_d_threonate
    <-> . +nad +nadh +hplus
    s_2_hydroxy_3_oxo_4_phosphonatooxy_butanoate
  }

  branch from holo-acp side right {
    holo-acp
    <-> ec_1_2_1_80 [1.2.1.80] +long_chain_fatty_aldehyde +nad +nadh +hplus
    o_s_long_chain_fatty_acyl_pantetheine_4_phosphor
  }

  branch from 4_alkanoyl_5_oxo_2_5_dihydrofuran_3_yl_methyl_p side left {
    4_alkanoyl_5_oxo_2_5_dihydrofuran_3_yl_methyl_p
    <-> ec_1_3_1_113 [1.3.1.113] +nadp +nadph +hplus
    3s_4r_4_alkanoyl_5_oxooxolan_3_yl_methyl_phosph
  }
}
