# Ingested from Rhea. The spine follows the carbon skeleton from
# D-threo-3-methylmalic acid to O2; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-threo-3-methylmalic-acid-to-o2 "D-threo-3-methylmalic acid to O2" {
  spacing 218

  spine at 0,0 {
    d_threo_3_methylmalic_acid
    <-> . -h -h2o
    2_methylmaleate
    <-> ec_3_7_1_23 [3.7.1.23] +h +pyruvate -h2o
    2e_2_methyl_4_6_dioxohept_2_enedioate
    <-> ec_1_13_11_4 [1.13.11.4] +h -o2
    3_methylgentisate
  }

  branch from 2_methylmaleate side left {
    2_methylmaleate
    <-> ec_3_7_1_23 [3.7.1.23] +h +pyruvate +h2o
    2e_3_methyl_4_6_dioxohept_2_enedioate
  }

  branch from h side right {
    h
    <-> . +nadh +3_4_dihydroxyphthalate +nad
    phthalate_3_4_cis_dihydrodiol
  }

  branch from h side left {
    h
    <-> ec_5_5_1_1 [5.5.1.1] +3_methylmuconolactone
    3_methyl_cis_cis_muconic_acid
  }

  branch from h2o side right {
    h2o
    <-> ec_1_14_14_1 [1.14.14.1] +4_hydroxymethyl_nitrosoamino_1_3_pyridinyl_1_but +nadp +h +o2 +nadph
    4_n_nitrosomethylamino_1_3_pyridyl_butan_1_one
  }

  branch from h2o side left {
    h2o
    <-> ec_1_14_14_1 [1.14.14.1] +alpha_3_hydroxymethyl_nitrosoamino_propyl_3_pyri +nadp +h +o2 +nadph
    4_methylnitrosamino_1_3_pyridyl_1_butanol
  }

  branch from 3_methylgentisate side right {
    3_methylgentisate
    <-> ec_1_14_13_24 [1.14.13.24] +nadh +3_hydroxy_5_methyl_benzoate +h +o2 +h2o
    nad
  }

  branch from 3_methylgentisate side left {
    3_methylgentisate
    <-> ec_1_13_11_4 [1.13.11.4] +h +o2
    4_hydroxy_3_methyl_6_oxo_hepta_2_4_dienedioic_ac
  }

  branch from o2 side right {
    o2
    <-> ec_1_14_14_1 [1.14.14.1] +7_hydroxymethyl_12_methylbenz_a_anthracene +nadp +h2o +h +7_12_dimethyltetraphene
    nadph
  }

  branch from o2 side left {
    o2
    <-> ec_1_14_14_1 [1.14.14.1] +7_12_dimethylbenz_a_anthracene_5_6_oxide +nadp +h2o +h +nadph
    7_12_dimethyltetraphene
  }
}
