# Ingested from Rhea. The spine follows the carbon skeleton from
# D-valine zwitterion to (2S)-2-hydroxy-3-methylbutanenitrile; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway d-valine-to-2s-2-hydroxy-3-methylbu-78203 "D-valine to (2S)-2-hydroxy-3-methylbu…" {
  spacing 246

  spine at 0,0 {
    d_valine
    <-> . +o2 +h2o -h2o2 -nh3
    kiv
    <-> ec_4_1_1_72 [4.1.1.72] +hplus -co2
    isobutyraldehyde
    <-> . +hydrogen_cyanide
    2s_2_hydroxy_3_methylbutanenitrile
  }

  branch from isobutyraldehyde side left {
    isobutyraldehyde
    <-> ec_1_2_1_5 [1.2.1.5] +nadh +h +butanoate +h2o
    nad
  }

  branch from isobutyraldehyde side right {
    isobutyraldehyde
    <-> ec_4_1_2_10 [4.1.2.10] +cyanide +h
    r_2_hydroxy_3_methybutanenitrile
  }

  branch from isobutyraldehyde side left {
    isobutyraldehyde
    <-> ec_1_1_1_1 [1.1.1.1] +h +nadph +nadp
    isobutanol
  }

  branch from hydrogen_cyanide side right {
    hydrogen_cyanide
    <-> . +formylthiophene
    2r_2_hydroxy_2_thiophen_2_yl_acetonitrile
  }

  branch from hydrogen_cyanide side left {
    hydrogen_cyanide
    <-> . +3_formylthiophene
    2s_2_hydroxy_2_thiophen_3_yl_acetonitrile
  }
}
