# Ingested from Rhea. The spine follows the carbon skeleton from
# deamido-NAD(2−) to dehydroalanine residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway deamido-nad-to-dehydroalanine "deamido-NAD to dehydroalanine" {
  spacing 280

  spine at 0,0 {
    deamido_nad
    <-> ec_2_5_1_143 [2.5.1.143] +hco3 -amp -hplus
    pyridinium_3_5_biscarboxylate_mononucleotide
    <-> . +atp +hplus -ppi
    5_carboxy_1_5_o_phosphono_d_ribofuranosyl_pyridi
    <-> . +l_cysteine -amp -hplus
    s_5_carboxy_1_5_o_phosphono_d_ribofuranosyl_pyri
    <-> . -pyridinium_3_carboxylate_5_thiocarboxylate_monon -hplus
    dehydroalanine
    <-> . +pyridinium_3_carboxylate_5_thiocarboxylate_monon +atp +hplus -ppi
    1_5_o_phosphono_d_ribofuranosyl_5_sulfanylcarbon
    <-> . +l_cysteine -amp -hplus
    s_1_5_o_phosphono_d_ribofuranosyl_5_sulfanylcarb
    <-> . -dehydroalanine -hplus
    pyridinium_3_5_bisthiocarboxylate_mononucleotide
  }

  branch from ppi side left {
    ppi
    <-> . +nicotinate +atp +coa +amp
    nicotinyl_coa
  }

  branch from pyridinium_3_5_bisthiocarboxylate_mononucleotide side right {
    pyridinium_3_5_bisthiocarboxylate_mononucleotide
    <-> ec_4_99_1_12 [4.99.1.12] +ni_ii_pyridinium_3_5_bisthiocarboxylate_mononucl
    nickel
  }
}
