# Ingested from Rhea. The spine follows the carbon skeleton from
# deoxycholoyl-CoA(4−) to 12α-hydroxy-3-oxochola-4,6-dien-24-oyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway deoxycholoyl-coa-to-12-hydroxy-3-oxochola-4 "deoxycholoyl-CoA to 12α-hydroxy-3-oxochola-4,…" {
  spacing 236

  spine at 0,0 {
    deoxycholoyl_coa
    <-> ec_1_1_1_395 [1.1.1.395] +nad -nadh -hplus
    3_oxodeoxycholoyl_coa
    <-> ec_1_3_1_114 [1.3.1.114] +nad -nadh -hplus
    12_hydroxy_3_oxochol_4_en_24_oyl_coa
    <-> ec_1_3_1_114 [1.3.1.114] +nad -nadh -hplus
    12_hydroxy_3_oxochola_4_6_dien_24_oyl_coa
  }
}
