# Ingested from Rhea. The spine follows the carbon skeleton from
# deoxycylindrospermopsin zwitterion to S-succinyl-L-cysteine(2−) residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway deoxycylindrospermopsin-to-s-succinyl-l-cysteine "deoxycylindrospermopsin to S-succinyl-L-cysteine(2−)" {
  spacing 230

  spine at 0,0 {
    deoxycylindrospermopsin
    <-> ec_1_14_11_70 [1.14.11.70] +akg +o2 -succinate -co2
    cylindrospermopsin
    <-> ec_1_3_2_4 [1.3.2.4] +iron +succinate -fe2 -hplus
    fumarate
    <-> . +l_cysteine
    s_succinyl_l_cysteine_2
  }

  branch from cylindrospermopsin side left {
    cylindrospermopsin
    <-> ec_1_14_11_70 [1.14.11.70] +2_oxoglutarate +deoxycylindrospermopsin +o2 +succinate
    co2
  }

  branch from succinate side right {
    succinate
    <-> . +5_methylcytidine_5_monophosphate_1 +akg +o2 +co2 +h2o
    5_formyl_cmp_1
  }

  branch from succinate side left {
    succinate
    <-> . +l_proline +akg +o2 +co2
    trans_3_hydroxy_l_proline
  }
}
