# Ingested from Rhea. The spine follows the carbon skeleton from
# diaminobutyryl-citryl-ethanolamino-alpha-ketoglutarate to AMP; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway diaminobutyryl-citryl-eth-to-amp-null "diaminobutyryl-citryl-eth… to AMP" {
  spacing 308

  spine at 0,0 {
    diaminobutyryl_citryl_ethanolamino_alpha_ketoglu
    <-> . +diphosphate +h +amp -atp -diaminobutyryl_citryl_ethanolamine
    2_oxoglutarate
    <-> . +diphosphate +h +amp +diaminobutyryl_citryl_ethanolamine -l_2_4_diaminobutanoate -o_citryl_ethanolamine
    atp
    <-> . +l_leucine +l_threonine +6_methyloctanoyl_coa +l_2_4_diaminobutanoate -polymyxin_a -h -coa -amp
    diphosphate
  }

  branch from 2_oxoglutarate side left {
    2_oxoglutarate
    <-> ec_1_14_11_1 [1.14.11.1] +r_carnitine +co2 +succinate +4_trimethylamino_butanoate
    o2
  }

  branch from 2_oxoglutarate side right {
    2_oxoglutarate
    <-> ec_1_14_20_4 [1.14.20.4] +o2 +2r_3s_4s_leucoanthocyanidin +succinate +4s_2_3_dehydroflavan_3_4_diol +h2o
    co2
  }

  branch from atp side left {
    atp
    <-> . +h +adp +phosphate +h2o
    7_hydroxy_3_alpha_iso_pravastatin
  }

  branch from atp side right {
    atp
    <-> . +alpha_d_galactose_6_phosphate +adp +h
    beta_d_galactose
  }

  branch from l_2_4_diaminobutanoate side left {
    l_2_4_diaminobutanoate
    <-> . +diphosphate +h +ferribactin +amp +h2o +l_lysine +l_threonine +atp +l_serine +l_arginine +l_glutamate +l_tyrosine
    n5_formyl_n5_hydroxy_l_ornithine
  }

  branch from l_2_4_diaminobutanoate side right {
    l_2_4_diaminobutanoate
    <-> . +diphosphate +h +amp +n5_2_4_diaminobutanoate_n1_citryl_n3_decanoyl_n3 +atp
    n1_citryl_n3_decanoyl_n3_hydroxy_1_3_diaminoprop
  }

  branch from diphosphate side left {
    diphosphate
    <-> . +alpha_ylangene
    2e_6e_farnesyl_diphosphate
  }

  branch from diphosphate side right {
    diphosphate
    <-> . +2e_6e_farnesyl_diphosphate
    cyperene
  }

  branch from h side left {
    h
    <-> . +udp +epicatechin_3_o_glucoside +epicatechin
    udp_alpha_d_glucose
  }

  branch from h side right {
    h
    <-> . +udp +glc_aatgal_pp_undecaprenol +udp_alpha_d_glucose
    2_acetamido_4_amino_2_4_6_trideoxy_alpha_d_galac
  }

  branch from coa side left {
    coa
    <-> ec_2_3_3_13 [2.3.3.13] +acetyl_coa +h +2_oxopentanoate +h2o
    2_propylmalate
  }

  branch from coa side right {
    coa
    <-> ec_2_3_1_185 [2.3.1.185] +acetyl_coa +tropine
    acetylpseudotropine
  }

  branch from amp side left {
    amp
    <-> . +7z_hexadecenoyl_coa +diphosphate +h +atp +coa
    7_palmitoleic_acid
  }

  branch from amp side right {
    amp
    <-> . +diphosphate +trans_9_octadecenoyl_coa +atp +coa
    9e_octadecenoate
  }

  branch from diphosphate side left {
    diphosphate
    <-> . +2e_6e_farnesyl_diphosphate
    rotundene
  }

  branch from diphosphate side right {
    diphosphate
    <-> . +2e_6e_farnesyl_diphosphate
    sesquisabinene
  }

  branch from h side left {
    h
    <-> . +udp +glc_galnac_p_gro_p_mannac_glcnac_pp_undecaprenol +udp_alpha_d_glucose
    galnac_p_gro_p_mannac_glcnac_pp_undecaprenol
  }

  branch from h side right {
    h
    <-> . +udp +glc_galnac_p_glc_galnac_p_gro_p_mannac_glcnac_pp +udp_alpha_d_glucose
    galnac_p_glc_galnac_p_gro_p_mannac_glcnac_pp_und
  }

  branch from amp side left {
    amp
    <-> . +11z_eicosenoyl_coa +diphosphate +atp +coa
    11z_eicosenoate
  }

  branch from amp side right {
    amp
    <-> . +henicosanoic_acid +atp +coa +diphosphate +h
    heneicosanoyl_coenzyme_a
  }

  branch from 2_oxoglutarate side left {
    2_oxoglutarate
    <-> ec_1_14_20_4 [1.14.20.4] +h +o2 +2r_3s_4s_leucoanthocyanidin +co2 +succinate +h2o
    3_hydroxy_2_phenylchromenylium
  }

  branch from 2_oxoglutarate side right {
    2_oxoglutarate
    <-> . +h +alpha_kdo_2_4_alpha_kdo_2_6_lipid_a_e_coli +o2 +co2 +s_2_hydroxymyristate_modified_lipid_a
    succinate
  }

  branch from atp side left {
    atp
    <-> . +h +adp +phosphate +h2o
    acetylcholine
  }

  branch from atp side right {
    atp
    <-> . +h +adp +phosphate +h2o
    acetaminophen_glutathione_conjugate
  }

  branch from l_leucine side left {
    l_leucine
    <-> . +l_alanine +l_asparagine +h2o
    alanyl_asparaginyl_leucine
  }

  branch from l_leucine side right {
    l_leucine
    <-> . +l_arginine +l_phenylalanine +h2o
    arginyl_leucyl_phenylalanine
  }
}
