# Ingested from Rhea. The spine follows the carbon skeleton from
# dichlorocarbene to phosphate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway dichlorocarbene-to-phosphate "dichlorocarbene to phosphate" {
  spacing 192

  spine at 0,0 {
    dichlorocarbene
    <-> . +h2o -carbon_monoxide -chloride
    h
    <-> ec_4_1_99_17 [4.1.99.17] +5_deoxyadenosine +4_amino_2_methyl_5_phosphooxymethyl_pyrimidine +formate +carbon_monoxide +l_methionine -s_adenosyl_l_methionine
    5_amino_1_5_phospho_beta_d_ribosyl_imidazole
    <-> . +co2 +atp +h2o -adp -5_amino_1_5_phospho_d_ribosyl_imidazole_4_carbox -phosphate
    h
  }
}
