# Ingested from Rhea. The spine follows the carbon skeleton from
# dioleoyl phosphatidic acid to 1-octanoyl-2-oleoyl-sn-glycerol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway dioleoyl-phosphatidic-acid-to-1-octanoyl-2-oleoy "dioleoyl phosphatidic acid to 1-octanoyl-2-oleoyl-sn-gl…" {
  spacing 268

  spine at 0,0 {
    dioleoyl_phosphatidic_acid
    <-> ec_2_7_1_107 [2.7.1.107] +adp -atp -1_2_dioleoyl_sn_glycerol
    h
    <-> . +1_2_dioleoyl_sn_glycerol +h2o -oleate -hplus
    2_oleoylglycerol
    <-> . +octanoyl_coa -coa
    1_octanoyl_2_oleoyl_sn_glycerol
  }

  branch from h side left {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    clavulanate
  }

  branch from h side right {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    phenazine_1_carboxylate
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    2_hydroxyphenazine
  }

  branch from atp side right {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    piericidin_a
  }

  branch from 2_oleoylglycerol side left {
    2_oleoylglycerol
    <-> . +atp +adp +hplus
    2_oleoyl_sn_glycero_3_phosphate
  }

  branch from 2_oleoylglycerol side right {
    2_oleoylglycerol
    <-> . +myristoyl_coa +coa
    1_myristoyl_2_oleoylglycerol
  }

  branch from adp side left {
    adp
    <-> ec_3_6_3_44 [3.6.3.44] +h +phosphate +atp +h2o
    thiolactomycin
  }

  branch from adp side right {
    adp
    <-> ec_3_6_3_44 [3.6.3.44] +h +phosphate +atp +h2o
    myxothiazol
  }

  branch from h side left {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    polymyxin_b1
  }

  branch from h side right {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    borrelidin
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    amiclenomycin
  }

  branch from atp side right {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    penem_cgp31608
  }

  branch from 2_oleoylglycerol side left {
    2_oleoylglycerol
    <-> . +palmitoyl_coa +coa
    1_palmitoyl_2_oleoylglycerol
  }

  branch from 2_oleoylglycerol side right {
    2_oleoylglycerol
    <-> . +stearoyl_coa +coa
    1_stearoyl_2_oleoylglycerol
  }

  branch from octanoyl_coa side left {
    octanoyl_coa
    <-> . +fad +hplus +fadh2
    trans_oct_2_enoyl_coa
  }

  branch from octanoyl_coa side right {
    octanoyl_coa
    <-> . +2_o_d_glucosyl_1_6_d_glucosyl_d_glycerate +coa
    2_o_6_o_octanoyl_d_glucosyl_1_6_d_glucosyl_d_gly
  }
}
