# Ingested from Rhea. The spine follows the carbon skeleton from
# diphosphate to laudanine(1+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway diphosphate-to-laudanine "diphosphate to laudanine" {
  spacing 276

  spine at 0,0 {
    diphosphate
    <-> ec_2_7_7_46 [2.7.7.46] +2_adenylylgentamicin_a -atp -gentamicin_a
    h
    <-> . +s_adenosyl_l_homocysteine +gentamicin_a -3_amino_3_deoxygentamicin_a2
    s_adenosyl_l_methionine
    <-> ec_2_1_1_291 [2.1.1.291] +s_reticuline -h -laudanine
    s_adenosyl_l_homocysteine
  }

  branch from h side left {
    h
    <-> . +9z_12z_octadecadienoate +h2o2 +z_z_1_8_11_heptadecatriene +h2o
    co2
  }

  branch from h side right {
    h
    <-> . +udp +beta_d_galactosyl_1_4_alpha_d_galactosyl_1_3_n_n +alpha_d_galactosyl_1_3_n_n_diacetyl_alpha_d_baci
    udp_alpha_d_galactose
  }

  branch from atp side left {
    atp
    <-> . +s_adenosyl_l_homocysteine +diphosphate +co2 +dieckmann_product +nadp +coa +amp +h2o +s_adenosyl_l_methionine +h +l_serine +nadph
    malonyl_coa
  }

  branch from atp side right {
    atp
    <-> ec_2_7_1_166 [2.7.1.166] +alpha_kdo8n_2_6_lipid_iva +h +adp
    4_o_phospho_alpha_kdo8n_2_6_lipid_iva
  }

  branch from gentamicin_a side left {
    gentamicin_a
    <-> ec_2_7_1_190 [2.7.1.190] +gdp +gentamicin_a_2_phosphate +h
    gtp
  }

  branch from gentamicin_a side right {
    gentamicin_a
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +atp
    h2o
  }

  branch from s_adenosyl_l_methionine side left {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +h +patulitrin
    quercetagitrin
  }

  branch from s_adenosyl_l_methionine side right {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +3_4_5_o_trimethylmyricetin_3_7_diolate +h
    3_4_dimethylmyricetin
  }

  branch from s_adenosyl_l_homocysteine side left {
    s_adenosyl_l_homocysteine
    <-> . +h +gentamicin_c2b +s_adenosyl_l_methionine
    gentamicin_c1a
  }

  branch from s_adenosyl_l_homocysteine side right {
    s_adenosyl_l_homocysteine
    <-> . +7_4_dihydroxy_8_methoxyflavone +s_adenosyl_l_methionine
    4_8_dihydroxyflavone_7_olate
  }
}
