# Ingested from Rhea. The spine follows the carbon skeleton from
# ditrans,polycis-undecaprenol to AMP 3'-end(1−) residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway ditrans-polycis-undecapre-to-amp-3-end-1-28122 "ditrans,polycis-undecapre… to AMP 3'-end(1−)" {
  spacing 340

  spine at 0,0 {
    ditrans_polycis_undecaprenol
    <-> ec_2_7_1_66 [2.7.1.66] +atp -adp -hplus
    ditrans_polycis_undecaprenyl_phosphate
    <-> ec_2_7_8_13 [2.7.8.13] +udp_n_acetyl_d_muramoyl_l_alanyl_d_glutamyl_l_ly -ump
    undecaprenyldiphosphonato_n_acetylmuramoyl_l_ala
    <-> ec_2_4_1_227 [2.4.1.227] +udpglcnac -udp -hplus
    lipid_ii
    <-> ec_6_3_5_13 [6.3.5.13] +glutamine +atp +h2o -glutamate -adp -pi -hplus
    undecaprenyldiphospho_n_acetyl_n_acetylglucosami
    <-> ec_2_3_2_16 [2.3.2.16] +3_glycyladenylyl_zwitterionic_group -amp_3_end_1 -hplus
    undecaprenyldiphospho_n_acetyl_n_acetylglucosami_chebi_62234
    <-> ec_2_3_2_17 [2.3.2.17] +3_glycyladenylyl_zwitterionic_group -amp_3_end_1 -hplus
    undecaprenyldiphospho_n_acetyl_n_acetylglucosami_chebi_62235
    <-> ec_2_3_2_18 [2.3.2.18] +3_glycyladenylyl_zwitterionic_group -amp_3_end_1 -hplus
    undecaprenyldiphospho_n_acetyl_n_acetylglucosami_chebi_62236
  }

  branch from ditrans_polycis_undecaprenyl_phosphate side left {
    ditrans_polycis_undecaprenyl_phosphate
    <-> . +alpha_d_man_1_2_alpha_d_man_1_2_beta_d_man_1_3_g +beta_d_glc_pp_und +h
    alpha_d_man_1_2_alpha_d_man_1_2_beta_d_man_1_3_a
  }

  branch from ditrans_polycis_undecaprenyl_phosphate side right {
    ditrans_polycis_undecaprenyl_phosphate
    <-> . +alpha_d_man_1_2_alpha_d_man_1_2_beta_d_man_1_3_g +beta_d_glc_pp_und +h
    alpha_d_man_1_2_alpha_d_glc_1_4_alpha_d_man_1_2
  }

  branch from lipid_ii side left {
    lipid_ii
    <-> . +atp +adp
    undecaprenyldiphosphonato_n_acetyl_n_acetylgluco
  }

  branch from amp_3_end_1 side right {
    amp_3_end_1
    <-> ec_3_1_1_96 [3.1.1.96] +3_d_aspartyl_adenylyl_1_group +h2o +hplus
    d_aspartate
  }

  branch from amp_3_end_1 side left {
    amp_3_end_1
    <-> ec_3_1_1_96 [3.1.1.96] +3_d_tryptophyl_adenylyl_1_group +h2o
    d_tryptophan
  }

  branch from udp_n_acetyl_d_muramoyl_l_alanyl_d_glutamyl_l_ly side right {
    udp_n_acetyl_d_muramoyl_l_alanyl_d_glutamyl_l_ly
    <-> . +h2o +d_alanine
    udp_n_acetyl_d_muramoyl_l_alanyl_d_glutamyl_l_ly_chebi_232760
  }

  branch from udpglcnac side left {
    udpglcnac
    <-> ec_4_2_1_135 [4.2.1.135] +h2o
    udp_2_acetamido_2_6_dideoxy_d_xylo_hex_4_ulose
  }

  branch from udpglcnac side right {
    udpglcnac
    <-> ec_2_7_1_176 [2.7.1.176] +atp +adp +hplus
    udp_n_acetyl_d_glucosamine_3_phosphate
  }

  branch from glutamine side left {
    glutamine
    <-> . +alanine +atp +adp +pi +hplus
    ala_gln
  }

  branch from 3_glycyladenylyl_zwitterionic_group side right {
    3_glycyladenylyl_zwitterionic_group
    <-> . +acetyl_coa +coa +hplus
    3_n_acetylglycyl_adenylyl
  }

  branch from amp_3_end_1 side left {
    amp_3_end_1
    <-> . +3_l_threonyl_adenylyl_1_group +h2o
    threonine
  }

  branch from amp_3_end_1 side right {
    amp_3_end_1
    <-> . +3_l_seryl_adenylyl_1_group +h2o
    serine
  }
}
