# Ingested from Rhea. The spine follows the carbon skeleton from
# divinyl chlorophyllide a to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway divinyl-chlorophyllide-a-to-h2o "divinyl chlorophyllide a to H2O" {
  spacing 340

  spine at 0,0 {
    divinyl_chlorophyllide_a
    <-> ec_1_3_1_33 [1.3.1.33] +nadp -nadph -divinylprotochlorophyllide
    h
    <-> . +nadh +divinylprotochlorophyllide -13_1_oxo_mg_protoporphyrin_ix_13_monomethyl_este
    nad
    <-> ec_1_14_13_81 [1.14.13.81] +nadp +13_1_oxo_mg_protoporphyrin_ix_13_monomethyl_este +h2o -nadph -13_1_hydroxy_mg_protoporphyrin_ix_13_monomethyl
    o2
    <-> . +nadh +h +13_1_hydroxy_mg_protoporphyrin_ix_13_monomethyl -nad -h2o
    mg_protoporphyrin_ix_13_monomethyl_ester
    <-> ec_1_14_13_81 [1.14.13.81] +h +o2 +nadph -13_1_hydroxy_mg_protoporphyrin_ix_13_monomethyl -h2o
    nadp
  }

  branch from h side left {
    h
    <-> ec_1_14_13_53 [1.14.13.53] +formononetin +o2 +nadph +nadp +h2o
    2_hydroxyformononetin
  }

  branch from h side right {
    h
    <-> ec_1_14_13_89 [1.14.13.89] +biochanin_a +o2 +nadph +nadp +h2o
    2_hydroxybiochanin_a
  }

  branch from nadph side left {
    nadph
    <-> ec_1_14_13_36 [1.14.13.36] +h +trans_4_coumaroylshikimate +o2 +nadp +h2o
    5_o_e_caffeoyl_shikimate
  }

  branch from nadph side right {
    nadph
    <-> . +rifamycin_b +h +nadp
    rifamycin_o
  }

  branch from divinylprotochlorophyllide side left {
    divinylprotochlorophyllide
    <-> ec_1_3_1_75 [1.3.1.75] +h +nadph +nadp
    protochlorophyllide
  }

  branch from nad side right {
    nad
    <-> ec_1_2_1_32 [1.2.1.32] +nadh +h +2e_4z_2_hydroxymuconate +h2o
    2_hydroxymuconic_semialdehyde
  }

  branch from nad side left {
    nad
    <-> ec_1_14_13_3 [1.14.13.3] +nadh +h +4_hydroxyphenylacetate +o2 +h2o
    3_4_dihydroxyphenylacetate
  }

  branch from o2 side right {
    o2
    <-> ec_1_14_11_15 [1.14.11.15] +gibberellin_a4 +co2 +succinate +2_oxoglutarate
    gibberellin_a9
  }

  branch from o2 side left {
    o2
    <-> ec_1_14_11_13 [1.14.11.13] +gibberellin_a4 +2_oxoglutarate +co2 +succinate
    gibberellin_a34
  }

  branch from h2o side right {
    h2o
    <-> ec_3_1_1_83 [3.1.1.83] +3s_6s_6_isopropenyl_3_methyloxepan_2_one
    5r_6_hydroxy_5_isopropenyl_2_methylhexanoate
  }

  branch from h2o side left {
    h2o
    <-> ec_1_14_13_89 [1.14.13.89] +daidzein +h +o2 +nadph +nadp
    2_hydroxydaidzein
  }

  branch from nadp side right {
    nadp
    <-> ec_1_14_13_84 [1.14.13.84] +4_hydroxyacetophenone +o2 +nadph +h2o
    4_hydroxyphenylacetate
  }

  branch from nadp side left {
    nadp
    <-> ec_1_14_13_85 [1.14.13.85] +6as_11as_2_dimethylallyl_3_6a_9_trihydroxyptero +h +o2 +nadph +h2o
    glyceollin_ii
  }
}
