# Ingested from Rhea. The spine follows the carbon skeleton from
# ent-kaur-16-ene to NADPH; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway ent-kaur-16-ene-to-nadph "ent-kaur-16-ene to NADPH" {
  spacing 152

  spine at 0,0 {
    ent_kaur_16_ene
    <-> ec_1_14_13_78 [1.14.13.78] +h +o2 +nadph -ent_kaur_16_en_19_oate -h2o
    nadp
    <-> ec_1_14_13_79 [1.14.13.79] +h +ent_kaur_16_en_19_oate +o2 +nadph -nadp -h2o
    gibberellin_a12
    <-> . +2_oxoglutarate +o2 -succinate -gibberellin_a14
    co2
    <-> . +gibberellin_a14 +nadp +h2o -o2 -nadph
    gibberellin_a14_aldehyde
  }
}
