# Ingested from Rhea. The spine follows the carbon skeleton from
# ethyl methyl sulfide to N-acetyl-L-methionine(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway ethyl-methyl-sulfide-to-n-acetyl-l-methionine "ethyl methyl sulfide to N-acetyl-L-methionine" {
  spacing 248

  spine at 0,0 {
    ethyl_methyl_sulfide
    <-> . +hydrogen_donor -methanethiol -hydrogen_acceptor
    ethane
    <-> ec_2_1_1_251 [2.1.1.251] +methanethiol +coenzyme_m -h2s -hplus
    methyl_com
    <-> . +o_succinyl_l_homoserinate +h2s -succinate
    homocysteine
    <-> ec_2_1_1_10 [2.1.1.10] +sam -sah -hplus
    methionine
    <-> . +acetyl_coa -coa -hplus
    n_acetyl_l_methionine
  }
}
