# Ingested from Rhea. The spine follows the carbon skeleton from
# FMNH2 to phosphate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway fmnh2-to-phosphate "FMNH2 to phosphate" {
  spacing 296

  spine at 0,0 {
    fmnh2
    <-> ec_1_3_8_16 [1.3.8.16] +h +3_1_carboxyvinyloxy_anthranilate -2s_2_amino_4_deoxychorismate
    fmn
    <-> ec_2_7_1_42 [2.7.1.42] +glucose -h -riboflavin
    alpha_d_glucose_1_phosphate
    <-> ec_2_4_1_392 [2.4.1.392] +aldehydo_d_glucuronate -phosphate
    beta_d_glucosyl_1_3_d_glucuronate
  }
}
