# Ingested from Rhea. The spine follows the carbon skeleton from
# galactitol to 5-dehydro-D-fructose; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway galactitol-to-5-dehydro-d-fructose "galactitol to 5-dehydro-D-fructose" {
  spacing 258

  spine at 0,0 {
    galactitol
    <-> ec_1_1_1_406 [1.1.1.406] +nad -nadh -hplus
    keto_l_tagatose
    <-> .
    keto_l_sorbose
    <-> ec_1_1_1_123 [1.1.1.123] +nadp -nadph -hplus
    5_dehydro_d_fructose
  }

  branch from keto_l_tagatose side left {
    keto_l_tagatose
    <-> ec_1_1_1_12 [1.1.1.12] +nadh +h +nad
    l_altritol
  }
}
