# Ingested from Rhea. The spine follows the carbon skeleton from
# GDP to beta-D-Gal-(1->4)-[alpha-L-Fuc-(1->3)]-alpha-D-GlcNAc-(1->2)-[alpha-D,D-Hep-(1->3)]3-alpha-D-Glu-(1->3)-[alpha-D-Glu-(1->6)]3-alpha-D,D-Hep-(1->3)-beta-L-Fuc-(1->3)-alpha-D-GlcNAc-diphospho-ditrans,octacis-undecaprenol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway gdp-to-beta-d-gal-1-4-alpha "GDP to beta-D-Gal-(1->4)-[alpha-…" {
  spacing 336

  spine at 0,0 {
    gdp
    <-> ec_2_4_1_152 [2.4.1.152] +beta_d_gal_1_4_alpha_l_fuc_1_3_alpha_d_glcnac_1 +h -beta_d_gal_1_4_alpha_d_glcnac_1_2_beta_d_gal_1_4
    gdp_beta_l_fucose
    <-> ec_2_4_1_38 [2.4.1.38] +udp +beta_d_gal_1_4_alpha_d_glcnac_1_2_beta_d_gal_1_4 +h -alpha_d_glcnac_1_2_beta_d_gal_1_4_alpha_l_fuc_1
    udp_alpha_d_galactose
    <-> . +udp +alpha_d_glcnac_1_2_beta_d_gal_1_4_alpha_l_fuc_1 +h -beta_d_gal_1_4_alpha_l_fuc_1_3_alpha_d_glcnac_1_mnxm1560188
    udp_n_acetyl_alpha_d_glucosamine
  }
}
