# Ingested from Rhea. The spine follows the carbon skeleton from
# GDP to α-D-mannosyl-(1→3)-N-acetyl-α-D-galctosaminyl-1-diphospho-ditrans,octacis-undecaprenol(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway gdp-to-d-mannosyl-1-3-n-acet "GDP to α-D-mannosyl-(1→3)-N-acet…" {
  spacing 214

  spine at 0,0 {
    gdp
    <-> ec_2_4_1_341 [2.4.1.341] +alpha_l_col_1_2_beta_d_gal_1_3_beta_d_glcnac_1_3 +h -gdp_l_colitose
    beta_d_gal_1_3_beta_d_glcnac_1_3_alpha_d_gal_1_3
    <-> . +udp +h -beta_d_glcnac_1_3_alpha_d_gal_1_3_galnac_pp_und
    udp_alpha_d_galactose
    <-> . +udp +beta_d_glcnac_1_3_alpha_d_gal_1_3_galnac_pp_und +h -alpha_d_gal_1_3_alpha_d_galnac_pp_und
    udp_n_acetyl_alpha_d_glucosamine
    <-> . +udp +alpha_d_gal_1_3_alpha_d_galnac_pp_und +h -n_acetyl_d_galactosaminyl_1_diphospho_ditrans_po
    udp_alpha_d_galactose
    <-> . +n_acetyl_d_galactosaminyl_1_diphospho_ditrans_po +gdp_d_mannose -gdp -hplus
    d_mannosyl_1_3_n_acetyl_d_galctosaminyl_1_dipho
  }

  branch from gdp_l_colitose side left {
    gdp_l_colitose
    <-> ec_1_1_1_356 [1.1.1.356] +nadp +nadph +hplus
    gdp_4_dehydro_3_6_dideoxy_d_mannose
  }

  branch from udp_alpha_d_galactose side right {
    udp_alpha_d_galactose
    <-> ec_2_4_1_241 [2.4.1.241] +udp +h +1_18_3_2_16_2_digalactosyldiacylglycerol
    1_18_3_2_16_2_monogalactosyldiacylglycerol
  }

  branch from udp_alpha_d_galactose side left {
    udp_alpha_d_galactose
    <-> ec_2_4_1_241 [2.4.1.241] +udp +h +1_18_2_2_16_3_digalactosyldiacylglycerol
    1_9z_12z_octadecadienoyl_2_7z_10z_13z_hexadecatr
  }

  branch from udp_n_acetyl_alpha_d_glucosamine side right {
    udp_n_acetyl_alpha_d_glucosamine
    <-> . +udp +n_n_diacetylchitobiosyldiphosphodolichol_human_u +h
    n_acetyl_d_glucosaminyldiphosphodolichol_human_u
  }

  branch from alpha_d_gal_1_3_alpha_d_galnac_pp_und side left {
    alpha_d_gal_1_3_alpha_d_galnac_pp_und
    <-> . +udp_n_acetyl_alpha_d_galactosamine +udp +h
    beta_d_galnac_1_4_alpha_d_gal_1_3_alpha_d_galnac
  }
}
