# Ingested from Rhea. The spine follows the carbon skeleton from
# gibberellin A53(2−) to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway gibberellin-a53-to-succinate "gibberellin A53 to succinate" {
  spacing 180

  spine at 0,0 {
    gibberellin_a53
    <-> . +akg +o2 +hplus -succinate -co2 -h2o
    gibberellin_a20
    <-> ec_1_14_11_15 [1.14.11.15] +akg +o2 -succinate -co2
    gibberellin_a1
    <-> ec_1_14_11_13 [1.14.11.13] +akg +o2 -succinate -co2
    gibberellin_a8
  }

  branch from gibberellin_a20 side left {
    gibberellin_a20
    <-> ec_2_1_1_275 [2.1.1.275] +sam +sah
    gibberellin_a20_methyl_ester
  }

  branch from succinate side right {
    succinate
    <-> . +l_proline +akg +o2 +co2
    trans_3_hydroxy_l_proline
  }

  branch from gibberellin_a1 side left {
    gibberellin_a1
    <-> . +sam +sah
    gibberellin_a1_methyl_ester
  }
}
