# Ingested from Rhea. The spine follows the carbon skeleton from
# gibberellin A53(2−) to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway gibberellin-a53-to-succinate "gibberellin A53 to succinate" {
  spacing 180

  spine at 0,0 {
    gibberellin_a53
    <-> . +akg +o2 +hplus -succinate -co2 -h2o
    gibberellin_a20
    <-> ec_1_14_11_15 [1.14.11.15] +akg +o2 -succinate -co2
    gibberellin_a1
    <-> ec_1_14_11_13 [1.14.11.13] +akg +o2 -succinate -co2
    gibberellin_a8
  }

  branch from gibberellin_a20 side left {
    gibberellin_a20
    <-> . +o2 +hplus +co2 +h2o
    gibberellin_a19
  }

  branch from succinate side right {
    succinate
    <-> ec_1_14_11_73 [1.14.11.73] +l_argininium +akg +o2 +co2
    3r_3_hydroxy_l_argininium
  }
}
