# Ingested from Rhea. The spine follows the carbon skeleton from
# ginsenoside Re to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway ginsenoside-re-to-h2o-40763 "ginsenoside Re to H2O" {
  spacing 212

  spine at 0,0 {
    ginsenoside_re
    <-> ec_3_2_1_194 [3.2.1.194] +h2o -l_rhamnopyranose
    ginsenoside_rg1
    <-> . +l_rhamnopyranose
    l_rhamnofuranose
    <-> .
    beta_l_rhamnose
    <-> ec_3_2_1_40 [3.2.1.40] +quercetin -h2o
    quercitrin
  }

  branch from l_rhamnofuranose side left {
    l_rhamnofuranose
    <-> .
    alpha_l_rhamnose
  }

  branch from beta_l_rhamnose side right {
    beta_l_rhamnose
    <-> ec_3_2_1_40 [3.2.1.40] +tilianin +h2o
    linarin
  }

  branch from quercitrin side left {
    quercitrin
    <-> . +udp +quercetin_3_o_rhamnoside_7_o_glucoside
    udp_alpha_d_glucose
  }

  branch from quercitrin side right {
    quercitrin
    <-> . +quercetin_3_o_rhamnoside_7_o_glucoside +udp_alpha_d_glucose
    udp
  }

  branch from h2o side left {
    h2o
    <-> ec_1_14_13_69 [1.14.13.69] +nadh +h +o2 +ethene +nad
    oxirane
  }

  branch from h2o side right {
    h2o
    <-> . +nadh +o2 +2_6_dichlorophenol +nad
    2_6_dichloro_4_hydroxyphenolate
  }

  branch from quercetin side left {
    quercetin
    <-> ec_1_14_13_21 [1.14.13.21] +luteolin +h +o2 +nadph +h2o
    nadp
  }

  branch from quercetin side right {
    quercetin
    <-> . +udp +h +udp_alpha_d_glucose
    quercetin_4_o_d_glucopyranoside
  }

  branch from h2o side left {
    h2o
    <-> . +2_succinylbenzoate +h
    spirodilactone
  }

  branch from h2o side right {
    h2o
    <-> . +2_2_bis_4_chlorophenyl_ethanol
    unsym_bis_4_chlorophenyl_ethylene
  }
}
