# Ingested from Rhea. The spine follows the carbon skeleton from
# glutathione disulfide to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway glutathione-disulfide-to-h2o "glutathione disulfide to H2O" {
  spacing 308

  spine at 0,0 {
    glutathione_disulfide
    <-> ec_1_11_1_12 [1.11.1.12] +4s_hdohe +h2o -glutathione
    4s_hpdha
    <-> ec_1_13_11_34 [1.13.11.34] -o2
    4z_7z_10z_13z_16z_19z_docosahexaenoate
    <-> . +h +adp +phosphate -4z_7z_10z_13z_16z_19z_docosahexaenoate -h2o
    atp
  }

  branch from glutathione side left {
    glutathione
    <-> . +z_1_glutathion_s_yl_n_hydroxy_omega_methylsulfa +h2o
    6_methylthiohexanonitrile_oxide
  }

  branch from glutathione side right {
    glutathione
    <-> . +z_1_glutathion_s_yl_n_hydroxy_omega_methylsulfa +h2o
    1_methylsulfanyl_7_aci_nitroheptane
  }

  branch from o2 side left {
    o2
    <-> . +4_coumaroyl_3_4_dihydroxyphenyllactate +nadp +h2o +h +4_coumaroyl_4_hydroxyphenyllactate
    nadph
  }

  branch from o2 side right {
    o2
    <-> . +24z_ethylidene_cholest_5_en_3beta_22s_diol +nadp +h2o +h +nadph
    isofucosterol
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_1 [3.6.3.1] +h +adp +phosphate +h2o
    1_9z_octadecenoyl_2_9z_12z_15z_octadecatrienoyl
  }

  branch from atp side right {
    atp
    <-> ec_3_6_3_1 [3.6.3.1] +h +adp +phosphate +h2o
    pc_18_2_9z_12z_18_3_9z_12z_15z
  }

  branch from h2o side left {
    h2o
    <-> ec_3_3_2_10 [3.3.2.10] +1_2_dihydroxypropyl_benzene
    trans_2_methylstyrene_7_8_oxide
  }

  branch from h2o side right {
    h2o
    <-> ec_2_1_2_1 [2.1.2.1] +glycine +5_10_methylenetetrahydropteroyl_hexa_l_glutamate +tetrahydropteroyl_hexa_l_glutamate
    l_serine
  }
}
