# Ingested from Rhea. The spine follows the carbon skeleton from
# glycine to monochlorobimane; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway glycine-to-monochlorobimane "glycine to monochlorobimane" {
  spacing 260

  spine at 0,0 {
    glycine
    <-> ec_3_4_13_23 [3.4.13.23] +cys_s_bimane -h2o
    s_bimane_l_cysteinylglycine
    <-> ec_3_4_19_13 [3.4.19.13] +l_glutamate -h2o
    glutathion_s_yl_bimane
    <-> ec_2_5_1_18 [2.5.1.18] +h +chloride -monochlorobimane
    glutathione
  }

  branch from h2o side left {
    h2o
    <-> . +h +adp +tricosanoate +phosphate +tricosanoate
    atp
  }

  branch from h2o side right {
    h2o
    <-> . +h +adp +phosphate +atp
    cerotic_acid_d3
  }

  branch from glutathion_s_yl_bimane side left {
    glutathion_s_yl_bimane
    <-> . +h +phosphate +atp +h2o
    adp
  }

  branch from glutathion_s_yl_bimane side right {
    glutathion_s_yl_bimane
    <-> ec_3_4_17_25 [3.4.17.25] +glycine +h2o
    gamma_glutamylcysteine_s_yl_bimane
  }

  branch from glutathione side left {
    glutathione
    <-> . +dopaminechrome_keto_form
    4_s_glutathionyl_5_6_dihydroxyindoline
  }

  branch from glutathione side right {
    glutathione
    <-> ec_1_8_5_7 [1.8.5.7] +glutathione_disulfide +h +2_6_dichloro_4_hydroxyphenolate
    2_6_dichloro_3_glutathion_s_yl_hydroquinone
  }
}
