# Ingested from Rhea. The spine follows the carbon skeleton from
# guanosine 5'-monophosphate(1−) residue to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway guanosine-5-monophosphat-to-succinate-23548 "guanosine 5'-monophosphat… to succinate" {
  spacing 248

  spine at 0,0 {
    guanosine_5_monophosphate_1
    <-> ec_2_1_1_171 [2.1.1.171] +sam -sah -hplus
    n2_methylguanosine_5_monophosphate_1
    <-> . +sam -sah -hplus
    n2_n2_dimethylguanosine_5_monophosphate_1
    <-> . +akg +o2 -formaldehyde -succinate -co2
    guanosine_5_monophosphate_1
  }
}
