# Ingested from Rhea. The spine follows the carbon skeleton from
# hexadecanoate ester to trans-hexadec-2-enal; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway hexadecanoate-ester-to-trans-hexadec-2-enal "hexadecanoate ester to trans-hexadec-2-enal" {
  spacing 180

  spine at 0,0 {
    hexadecanoate_ester
    <-> . +h2o -palmitate -hplus
    aliphatic_alcohol
    <-> . +palmitate +nadh +hplus -nad -h2o
    hexadecanal
    <-> ec_1_3_1_27 [1.3.1.27] +nadp -nadph -hplus
    hexadecenal
  }

  branch from palmitate side left {
    palmitate
    <-> . +1_hexadecanoyl_sn_glycero_3_phosphoethanolamine +h2o +hplus
    2_ammonioethyl_2r_2_3_dihydroxypropyl_phosphate
  }

  branch from palmitate side right {
    palmitate
    <-> . +1_hexadecanoyl_2_9z_12z_octadecadienoyl_sn_glyce +h2o +hplus
    2_linoleoyl_sn_glycero_3_phosphocholine
  }

  branch from hexadecanal side left {
    hexadecanal
    <-> ec_1_1_1_164 [1.1.1.164] +nad +nadh +hplus
    hexadecan_1_ol
  }

  branch from hexadecanal side right {
    hexadecanal
    <-> ec_1_2_1_n2 [1.2.1.n2] +nadp +coa +nadph +hplus
    palmitoyl_coa
  }
}
