# Ingested from Rhea. The spine follows the carbon skeleton from
# hexan-1-ol to hexanoate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway hexan-1-ol-to-hexanoate "hexan-1-ol to hexanoate" {
  spacing 152

  spine at 0,0 {
    hexan_1_ol
    <-> . +nadp -nadph -hplus
    hexanal
    <-> . +o2 +h2o -h2o2 -hplus
    hexanoate
  }
}
