# Ingested from Rhea. The spine follows the carbon skeleton from
# isopentenyl diphosphate(3−) to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway isopentenyl-diphosphate-to-h2o "isopentenyl diphosphate to H2O" {
  spacing 340

  spine at 0,0 {
    ipp
    <-> ec_2_5_1_92 [2.5.1.92] +dmapp -ppi
    2_cis_6_cis_farnesyl_diphosphate
    <-> ec_4_2_3_50 [4.2.3.50] -ppi
    santalene
    <-> . +h +o2 +nadph -alpha_santal_10_en_12_ol -h2o
    nadp
  }

  branch from 2_cis_6_cis_farnesyl_diphosphate side left {
    2_cis_6_cis_farnesyl_diphosphate
    <-> . +ppi
    germacrene_c
  }

  branch from 2_cis_6_cis_farnesyl_diphosphate side right {
    2_cis_6_cis_farnesyl_diphosphate
    <-> . +ppi
    germacrene_a
  }

  branch from ppi side left {
    ppi
    <-> . +fpp
    cadinene
  }

  branch from ppi side right {
    ppi
    <-> . +gpp
    sabinene
  }

  branch from nadp side left {
    nadp
    <-> ec_1_1_1_71 [1.1.1.71] +s_citronellol +h +nadph
    r_citronellal
  }

  branch from nadp side right {
    nadp
    <-> ec_1_1_1_71 [1.1.1.71] +2e_geranial +h +nadph
    thujan_3_ol
  }

  branch from h2o side left {
    h2o
    <-> ec_3_6_3_17 [3.6.3.17] +h +adp +d_talopyranose +phosphate +d_talopyranose
    atp
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_17 [3.6.3.17] +h +adp +phosphate +atp
    d_xylulofuranose
  }
}
