# Ingested from Rhea. The spine follows the carbon skeleton from
# isovaleryl-CoA(4−) to CoA; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway isovaleryl-coa-to-coa "isovaleryl-CoA to CoA" {
  spacing 158

  spine at 0,0 {
    isovaleryl_coa
    <-> . +carnitine -coa
    isovaleryl_l_carnitine
    <-> . +coa -3_methylbutanoyl_coa
    s_carnitine
    <-> . +malonyl_coa +3_methylbutanoyl_coa +h -6_4_methyl_2_oxopentyl_4_hydroxy_2_pyrone -coa
    co2
  }

  branch from carnitine side left {
    carnitine
    <-> . +5e_tetradecenoyl_coa +coa
    5e_tetradecenoyl_l_carnitine
  }
}
