# Ingested from Rhea. The spine follows the carbon skeleton from
# isoxazolin-5-one to N4-acetylcytidine 5'-monophosphate(1−) residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway isoxazolin-5-one-to-n4-acetylcytidine-22112 "isoxazolin-5-one to N4-acetylcytidine…" {
  spacing 290

  spine at 0,0 {
    isoxazolin_5_one
    <-> ec_2_5_1_118 [2.5.1.118] +o_acetyl_l_serine -acetate -hplus
    3_5_oxoisoxazolin_2_yl_l_alanine
    <-> . +acetate +atp +hplus -ppi
    acetyl_amp
    <-> . +cytidine_5_monophosphate_1 -amp -hplus
    n4_acetylcytidine_5_monophosphate_1
  }

  branch from acetyl_amp side left {
    acetyl_amp
    <-> ec_6_2_1_1 [6.2.1.1] +coa +h +amp_mnxm728294
    acetyl_coa
  }

  branch from ppi side right {
    ppi
    <-> ec_4_2_3_105 [4.2.3.105] +gpp
    tricyclene
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_106 [4.2.3.106] +gpp
    e_ocimene
  }

  branch from ppi side right {
    ppi
    <-> . +gpp
    car_3_ene
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_123 [4.2.3.123] +fpp
    sesquiphellandrene
  }

  branch from cytidine_5_monophosphate_1 side right {
    cytidine_5_monophosphate_1
    <-> ec_2_1_1_186 [2.1.1.186] +sam +sah +hplus
    2_o_methylcytidine_5_monophosphate_1
  }

  branch from cytidine_5_monophosphate_1 side left {
    cytidine_5_monophosphate_1
    <-> ec_2_1_1_191 [2.1.1.191] +sam +sah +hplus
    5_methylcytidine_5_monophosphate_1
  }
}
