# Ingested from Rhea. The spine follows the carbon skeleton from
# ITP to D-mannitol 1-phosphate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway itp-to-d-mannitol-1-phosphate "ITP to D-mannitol 1-phosphate" {
  spacing 152

  spine at 0,0 {
    itp
    <-> ec_2_7_1_1 [2.7.1.1] +d_sorbitol -h -d_mannitol_1_phosphate
    idp
    <-> . +h +nadp +d_mannitol_1_phosphate -nadph
    l_sorbose_1_phosphate
    <-> . +nadh -nad -d_mannitol_1_phosphate
    h
  }
}
