# Ingested from Rhea. The spine follows the carbon skeleton from
# ITP(4−) to diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway itp-to-diphosphate "ITP to diphosphate" {
  spacing 208

  spine at 0,0 {
    itp
    <-> ec_3_6_1_8 [3.6.1.8] +h2o -ppi -hplus
    imp
    <-> ec_1_1_1_205 [1.1.1.205] +nad +h2o -nadh -hplus
    xmp
    <-> ec_6_3_5_2 [6.3.5.2] +glutamine +atp +h2o -gmp -amp -ppi -hplus
    glutamate
  }
}
