# Ingested from Rhea. The spine follows the carbon skeleton from
# (-)-Jasmonoyl-L-isoleucine to diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway jasmonoyl-l-isoleucine-to-diphosphate "(-)-Jasmonoyl-L-isoleucine to diphosphate" {
  spacing 234

  spine at 0,0 {
    jasmonoyl_l_isoleucine
    <-> . -n_7_isojasmonyl_l_isoleucinate
    h
    <-> ec_3_5_1_127 [3.5.1.127] +n_7_isojasmonyl_l_isoleucinate +h2o -isoleucine
    7_isojasmonate
    <-> . +isoleucine +atp -amp -ppi -hplus
    n_7_isojasmonyl_l_isoleucinate
  }

  branch from h side left {
    h
    <-> . +s_adenosyl_l_homocysteine +l_leucyl_arginomycin +l_leucyl_demethylarginomycin
    s_adenosyl_l_methionine
  }

  branch from h side right {
    h
    <-> . +s_adenosyl_l_homocysteine +l_leucyl_blasticidin_s +s_adenosyl_l_methionine
    l_leucyl_demethyl_blasticidin_s
  }

  branch from n_7_isojasmonyl_l_isoleucinate side left {
    n_7_isojasmonyl_l_isoleucinate
    <-> . +nadph +o2 +hplus +nadp +h2o
    n_12_hydroxy_7_isojasmonyl_l_isoleucinate
  }

  branch from n_7_isojasmonyl_l_isoleucinate side right {
    n_7_isojasmonyl_l_isoleucinate
    <-> . +diphosphate +h +amp +l_isoleucine +jasmonate
    atp
  }

  branch from 7_isojasmonate side left {
    7_isojasmonate
    <-> .
    jasmonate
  }

  branch from ppi side right {
    ppi
    <-> . +o_orsellinate +fpp
    ilicicolinate_b
  }

  branch from ppi side left {
    ppi
    <-> . +5_methylorsellinate +atp +nadph +hplus +amp +nadp
    2_4_dihydroxy_5_6_dimethylbenzaldehyde
  }
}
