# Ingested from Rhea. The spine follows the carbon skeleton from
# L-arogenate(1−) to 1,4-benzosemiquinone; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway l-arogenate-to-1-4-benzosemiquinone "L-arogenate to 1,4-benzosemiquinone" {
  spacing 244

  spine at 0,0 {
    l_arogenate
    <-> ec_2_6_1_78 [2.6.1.78] +oxaloacetate -aspartate
    1s_4s_prephenate
    <-> ec_1_3_1_12 [1.3.1.12] +nad -co2 -nadh
    3_4_hydroxyphenyl_pyruvate
    <-> ec_1_13_11_46 [1.13.11.46] +o2 -co2
    s_4_hydroxymandelate
    <-> ec_1_1_3_19 [1.1.3.19] +o2 +hplus -h2o2 -co2
    4_hydroxybenzaldehyde
    <-> ec_1_2_1_96 [1.2.1.96] +nadp +h2o -nadph -hplus
    4_hydroxybenzoate
    <-> ec_1_14_13_64 [1.14.13.64] +nadph +o2 +hplus -co2 -nadp -h2o
    quinol
    <-> ec_1_10_3_2 [1.10.3.2] +o2 -h2o
    1_4_benzosemiquinone
  }

  branch from 1s_4s_prephenate side left {
    1s_4s_prephenate
    <-> ec_4_1_1_100 [4.1.1.100] +hplus +co2
    4r_3_4_dihydro_4_hydroxyphenylpyruvate
  }

  branch from aspartate side right {
    aspartate
    <-> ec_1_4_3_16 [1.4.3.16] +o2 +h2o2
    iminoaspartate
  }

  branch from s_4_hydroxymandelate side left {
    s_4_hydroxymandelate
    <-> ec_1_14_16_6 [1.14.16.6] +s_mandelate +sapropterin +o2 +h2o
    bh2
  }

  branch from 4_hydroxybenzaldehyde side right {
    4_hydroxybenzaldehyde
    <-> ec_4_1_2_61 [4.1.2.61] +h2o +acetyl_coa
    trans_4_coumaroyl_coa
  }
}
