# Ingested from Rhea. The spine follows the carbon skeleton from
# L-cystine zwitterion to diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway l-cystine-to-diphosphate "L-cystine to diphosphate" {
  spacing 152

  spine at 0,0 {
    l_cystine
    <-> ec_4_4_1_35 [4.4.1.35] +h2o -pyruvate -nh3
    3_disulfanyl_l_alanine
    <-> . +cysteine -alanine
    3_trisulfanyl_l_alanine
    <-> . +amp_3_end_1 +atp -amp -ppi
    3_s_disulfanyl_l_cysteinyl_adenylyl_zwitterionic
  }
}
