# Ingested from Rhea. The spine follows the carbon skeleton from
# L-serine residue to 10-hydroxypalmitate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway l-serine-to-10-hydroxypalmitate "L-serine to 10-hydroxypalmitate" {
  spacing 264

  spine at 0,0 {
    l_serine
    <-> ec_2_3_1_250 [2.3.1.250] +palmitoleoyl_coa -coa
    o_9z_hexadecenoyl_l_serine
    <-> ec_3_1_1_98 [3.1.1.98] +h2o -palmitoleate -hplus
    l_serine
    <-> . +palmitoleate +h2o
    10_hydroxypalmitate
  }

  branch from l_serine side left {
    l_serine
    <-> ec_2_7_11_1 [2.7.11.1] +atp +adp +hplus
    o_phospho_l_serine_2
  }

  branch from palmitoleoyl_coa side right {
    palmitoleoyl_coa
    <-> . +ketosphinganine +coa +hplus
    n_palmitoleoyl_3_ketodihydrosphingosine
  }
}
