# Ingested from Rhea. The spine follows the carbon skeleton from
# L-serine zwitterion to S-adenosyl-L-homocysteine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway l-serine-to-s-adenosyl-l-homocysteine-67324 "L-serine to S-adenosyl-L-homocysteine" {
  spacing 164

  spine at 0,0 {
    serine
    <-> . +malonyl-coa +acetyl_coa +sam +atp +nadph +hplus -amp -sah -co2 -ppi -nadp -coa -h2o
    5s_3_2e_6r_8e_10e_12e_2_6_dimethyltetradeca_2_8
    <-> .
    trichosetin
    <-> . +sam -sah -hplus
    equisetin
  }

  branch from malonyl-coa side left {
    malonyl-coa
    <-> . +l_pipecolic_acid +nadph +hplus +co2 +nadp +coa +h2o
    1s_8as_octahydroindolizin_1_ol
  }

  branch from malonyl-coa side right {
    malonyl-coa
    <-> . +kaempferol_3_o_d_glucoside +coa
    kaempferol_3_o_6_o_malonyl_d_glucoside
  }
}
