# Ingested from Rhea. The spine follows the carbon skeleton from
# L-vinylglycine zwitterion to CoA; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway l-vinylglycine-to-coa-null "L-vinylglycine to CoA" {
  spacing 152

  spine at 0,0 {
    l_vinylglycine
    <-> ec_4_4_1_43 [4.4.1.43]
    2e_2_aminobut_2_enoic_acid
    <-> ec_4_4_1_43 [4.4.1.43] +h2o
    l_homoserine
    <-> . +acetyl_coa -h -coa
    acetylhomoserine
  }
}
