# Ingested from Rhea. The spine follows the carbon skeleton from
# leukotriene C4(2−) to 20-hydroxy-leukotriene E4(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway leukotriene-c4-to-20-hydroxy-leukotriene-e4-3156 "leukotriene C4 to 20-hydroxy-leukotriene E4" {
  spacing 212

  spine at 0,0 {
    leukotriene_c4
    <-> ec_3_4_19_14 [3.4.19.14] +h2o -glutamate
    leukotriene_d4
    <-> . +h2o -glycine
    leukotriene_e4
    <-> ec_1_14_13_34 [1.14.13.34] +nadph +o2 +hplus -nadp -h2o
    20_hydroxy_leukotriene_e4
  }

  branch from glycine side left {
    glycine
    <-> . +myristoyl_coa +coa +hplus
    n_myristoylglycinate
  }

  branch from glycine side right {
    glycine
    <-> . +lauroyl_coa +coa +hplus
    n_dodecanoylglycinate
  }

  branch from glycine side left {
    glycine
    <-> . +linoleoyl_coa +coa +hplus
    n_linoleoylglycine
  }

  branch from glycine side right {
    glycine
    <-> ec_4_3_2_11 [4.3.2.11] +3r_3_carboxylmethyl_amino_fatty_acid +holo-acp +hplus +h2o
    o_s_2e_2_enoylpantetheine_4_phosphoryl_l_serine
  }
}
