# Ingested from Rhea. The spine follows the carbon skeleton from
# long-chain fatty acyl-CoA(4−) to long-chain fatty acyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway long-chain-fatty-acyl-coa-to-long-chain-fatty-ac "long-chain fatty acyl-CoA to long-chain fatty acyl-CoA" {
  spacing 262

  spine at 0,0 {
    long_chain_fatty_acyl_coa
    <-> ec_1_2_1_84 [1.2.1.84] +nadph +hplus -nadp -coa
    long_chain_primary_fatty_alcohol
    <-> ec_1_1_3_20 [1.1.3.20] +o2 -h2o2
    long_chain_fatty_aldehyde
    <-> ec_1_2_1_50 [1.2.1.50] +nadp +coa -nadph -hplus
    long_chain_fatty_acyl_coa
  }

  branch from long_chain_fatty_acyl_coa side left {
    long_chain_fatty_acyl_coa
    <-> . +acetyl_coa +coa
    long_chain_3_oxo_fatty_acyl_coa
  }
}
