# Ingested from Rhea. The spine follows the carbon skeleton from
# luteolin to apiforol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway luteolin-to-apiforol "luteolin to apiforol" {
  spacing 218

  spine at 0,0 {
    luteolin
    <-> . +nadp +h2o -o2 -nadph
    s_eriodictyol
    <-> ec_1_14_13_21 [1.14.13.21] +nadp +h2o -o2 -2s_naringenin -nadph
    h
    <-> ec_1_1_1_234 [1.1.1.234] +2s_naringenin +nadph -apiforol
    nadp
  }

  branch from o2 side left {
    o2
    <-> . +2_trans_6_cis_dodeca_2_6_dienoyl_coa +h2o2 +h
    cis_6_dodecenoyl_coenzyme_a
  }

  branch from o2 side right {
    o2
    <-> . +hydroxy_torasemide +h2o
    torasemide_carboxylic_acid
  }

  branch from nadph side left {
    nadph
    <-> ec_1_1_1_348 [1.1.1.348] +h +3r_2_hydroxyisoflavanone +nadp
    4r_4_2_dihydroxyisoflavan
  }

  branch from nadph side right {
    nadph
    <-> ec_1_1_1_270 [1.1.1.270] +h +3_oxosteroid +nadp
    3beta_hydroxysteroid
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    deoxycholic_acid_3_glucuronide
  }

  branch from h side right {
    h
    <-> . +adp +n_desisopropyl_fluvastatin +phosphate +n_desisopropyl_fluvastatin +h2o
    atp
  }

  branch from 2s_naringenin side left {
    2s_naringenin
    <-> . +nadh +h +nad
    phloretin
  }

  branch from nadp side right {
    nadp
    <-> ec_1_1_1_170 [1.1.1.170] +co2 +h +3_oxosteroid +nadph
    3beta_hydroxysteroid_4alpha_carboxylate
  }

  branch from nadp side left {
    nadp
    <-> . +delta_anaerubin +h +nadph
    anaerobilin
  }

  branch from apiforol side right {
    apiforol
    <-> . +apigeninidin +co2 +succinate +h2o +h +o2
    2_oxoglutarate
  }

  branch from apiforol side left {
    apiforol
    <-> . +co2 +succinate +h2o +2_oxoglutarate +o2
    apigeninidin
  }
}
