# Ingested from Rhea. The spine follows the carbon skeleton from
# maltoheptaose to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway maltoheptaose-to-h2o "maltoheptaose to H2O" {
  spacing 212

  spine at 0,0 {
    maltoheptaose
    <-> . +h2o -beta_d_fructose
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    <-> . +h2o -d_glucose
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    <-> . +h2o -d_glucose
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp
    <-> ec_3_2_1_1 [3.2.1.1] +h +4_nitrophenol -h2o
    p_nitrophenylmaltotetraoside
  }

  branch from d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g side left {
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    <-> . +glucose +h2o
    maltopentaose
  }

  branch from d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g side right {
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    <-> ec_2_4_1_25 [2.4.1.25] +glucose +d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    d_maltose
  }

  branch from beta_d_fructose side left {
    beta_d_fructose
    <-> ec_3_1_3_11 [3.1.3.11] +d_fructofuranose_1_phosphate +h2o
    phosphate
  }

  branch from beta_d_fructose side right {
    beta_d_fructose
    <-> . +maltoheptaose +h2o
    maltononaose
  }

  branch from d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g side left {
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    <-> . +o2 +h2o2
    d_maltopentaono_1_5_lactone
  }

  branch from d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g side right {
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_g
    <-> ec_2_4_1_25 [2.4.1.25] +d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp +d_maltose
    glucose
  }

  branch from d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp side left {
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp
    <-> ec_2_4_1_25 [2.4.1.25] +d_maltose +glucose
    d_glcp_1_4_d_glcp_1_4_d_glcp
  }

  branch from d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp side right {
    d_glcp_1_4_d_glcp_1_4_d_glcp_1_4_d_glcp
    <-> ec_3_6_3_18 [3.6.3.18] +h +adp +phosphate +h2o
    atp
  }

  branch from h2o side left {
    h2o
    <-> ec_1_14_13_37 [1.14.13.37] +allocryptopine +nadp +o2 +nadph
    s_cis_n_methylcanadine
  }

  branch from h2o side right {
    h2o
    <-> ec_3_2_1_128 [3.2.1.128] +glycyrrhetinate +h +2_beta_d_glucuronosyl_d_glucuronate
    glycyrrhizinate
  }
}
