# Ingested from Rhea. The spine follows the carbon skeleton from
# methyl sulfate(1−) to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway methyl-sulfate-to-succinate "methyl sulfate to succinate" {
  spacing 236

  spine at 0,0 {
    methyl_sulfate
    <-> ec_3_1_6_16 [3.1.6.16] +h2o -sulfate -hplus
    methanol
    <-> ec_1_1_2_7 [1.1.2.7] +iron -fe2 -hplus
    formaldehyde
    <-> ec_4_1_2_43 [4.1.2.43] +ru5p
    d_arabino_hex_3_ulose_6_phosphate
    <-> ec_5_3_1_27 [5.3.1.27]
    d_fructofuranose_6_phosphate
    <-> ec_2_7_1_11 [2.7.1.11] +atp -adp -hplus
    f16bp
    <-> ec_4_1_2_13 [4.1.2.13] -dhap
    g3p
    <-> ec_2_5_1_66 [2.5.1.66] +arginine -pi -hplus
    n2_2_carboxyethyl_l_arginine_dizwitterion
    <-> ec_6_3_3_4 [6.3.3.4] +atp -amp -ppi -hplus
    deoxyamidinoproclavaminic_acid
    <-> ec_1_14_11_21 [1.14.11.21] +akg +o2 -succinate -co2
    amidinoproclavaminic_acid
  }

  branch from methanol side left {
    methanol
    <-> ec_1_14_14_117 [1.14.14.117] +8_o_methyldihydrosterigmatocystin +fmnh2 +o2 +fmn +co2 +h2o +hplus
    aflatoxin_b2
  }

  branch from sulfate side right {
    sulfate
    <-> ec_3_1_6_2 [3.1.6.2] +dehydroepiandrosterone_sulfate +h2o +hplus
    dehydroepiandrosterone
  }

  branch from formaldehyde side left {
    formaldehyde
    <-> ec_1_14_11_32 [1.14.11.32] +codeine +akg +o2 +succinate +co2
    morphine
  }

  branch from d_fructofuranose_6_phosphate side right {
    d_fructofuranose_6_phosphate
    <-> ec_1_1_1_140 [1.1.1.140] +nad +nadh +hplus
    d_glucitol_6_phosphate
  }
}
