# Ingested from Rhea. The spine follows the carbon skeleton from
# myo-inositol to cytidine 5'-monophosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway myo-inositol-to-cytidine-5-monophosphate "myo-inositol to cytidine 5'-monophosphate" {
  spacing 260

  spine at 0,0 {
    myo_inositol
    <-> ec_2_7_1_64 [2.7.1.64] +atp -adp -hplus
    1d_myo_inositol_3_phosphate
    <-> ec_2_7_7_74 [2.7.7.74] +ctp +hplus -ppi
    cdp_1l_myo_inositol
    <-> ec_2_7_8_34 [2.7.8.34] +1d_myo_inositol_3_phosphate -cytidine_5_monophosphate -hplus
    bis_1l_myo_inositol_3_1_phosphate_1_phosphate
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_128 [4.2.3.128] +fpp
    cubebene
  }

  branch from cytidine_5_monophosphate side right {
    cytidine_5_monophosphate
    <-> ec_2_4_99_15 [2.4.99.15] +kdo_2_lipid_iva +cmp_3_deoxy_d_manno_octulosonate +hplus
    kdo_3_lipid_iva
  }
}
