# Ingested from Rhea. The spine follows the carbon skeleton from
# myo-inositol phosphate(2−) to 2D-2,3,5/4,6-pentahydroxycyclohexanone; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway myo-inositol-phosphate-to-2d-2-3-5-4-6-pentahydr "myo-inositol phosphate to 2D-2,3,5/4,6-pentahydroxy…" {
  spacing 184

  spine at 0,0 {
    myo_inositol_phosphate
    <-> ec_3_1_3_25 [3.1.3.25] +h2o -pi
    myo_inositol
    <-> ec_1_1_1_18 [1.1.1.18] +nad -nadh -hplus
    myo_2_inosose
    <-> ec_5_3_99_11 [5.3.99.11]
    2d_2_3_5_4_6_pentahydroxycyclohexanone
  }
}
