# Ingested from Rhea. The spine follows the carbon skeleton from
# myo-inositol to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway myo-inositol-to-h2o "myo-inositol to H2O" {
  spacing 228

  spine at 0,0 {
    myo_inositol
    <-> . +galactopinitol_b -5d_5_o_methyl_chiro_inositol
    galactinol
    <-> . +melibiose -2r_3r_4s_5s_6r_6_2s_3r_4s_5r_6r_3_4_5_trihydrox
    myo_inositol
    <-> ec_3_2_1_26 [3.2.1.26] +d_fructofuranose +2r_3r_4s_5s_6r_6_2s_3r_4s_5r_6r_3_4_5_trihydrox -h2o
    stachyose
    <-> . +sucrose
    raffinose
    <-> ec_3_6_3_18 [3.6.3.18] +h +adp +phosphate -raffinose -h2o
    atp
  }

  branch from galactinol side left {
    galactinol
    <-> . +myo_inositol +5d_5_o_methyl_chiro_inositol
    galactopinitol_a
  }

  branch from galactinol side right {
    galactinol
    <-> . +myo_inositol +galactopinitol_a
    ciceritol
  }

  branch from 5d_5_o_methyl_chiro_inositol side left {
    5d_5_o_methyl_chiro_inositol
    <-> . +myo_inositol +galactopinitol_a
    alpha_d_galactosyl_1_3_1d_myo_inositol
  }

  branch from myo_inositol side right {
    myo_inositol
    <-> ec_3_2_1_22 [3.2.1.22] +alpha_d_galactosyl_1_3_1d_myo_inositol +h2o
    alpha_d_galactose
  }

  branch from myo_inositol side left {
    myo_inositol
    <-> ec_2_7_8_11 [2.7.8.11] +cmp +h +dipalmitoyl_l_1_phosphatidyl_inositol
    cdp_dipalmitoyl_sn_glycerol
  }

  branch from 2r_3r_4s_5s_6r_6_2s_3r_4s_5r_6r_3_4_5_trihydrox side right {
    2r_3r_4s_5s_6r_6_2s_3r_4s_5r_6r_3_4_5_trihydrox
    <-> ec_3_2_1_22 [3.2.1.22] +melibiose +h2o
    beta_d_galactose
  }

  branch from h2o side left {
    h2o
    <-> . +l_histidine +l_serine +l_tryptophan
    seryl_tryptophanyl_histidine
  }

  branch from h2o side right {
    h2o
    <-> . +l_threonine +l_arginine +l_tyrosine
    threonyl_arginyl_tyrosine
  }

  branch from raffinose side left {
    raffinose
    <-> ec_2_4_1_166 [2.4.1.166] +sucrose
    3f_alpha_d_galactosylraffinose
  }

  branch from raffinose side right {
    raffinose
    <-> . +sucrose +stellariose
    1_f_alpha_d_galactosylraffinose
  }

  branch from atp side left {
    atp
    <-> ec_6_2_1_53 [6.2.1.53] +l_proline +h +l_prolyl_adenylate
    diphosphate
  }

  branch from atp side right {
    atp
    <-> ec_6_3_2_2 [6.3.2.2] +l_alanine +l_glutamate +h +adp +phosphate
    gamma_l_glutamyl_d_alanine
  }
}
