# Ingested from Rhea. The spine follows the carbon skeleton from
# myo-inositol phosphate(2−) to planteose; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway myo-inositol-phosphate-to-planteose-24056 "myo-inositol phosphate to planteose" {
  spacing 280

  spine at 0,0 {
    myo_inositol_phosphate
    <-> ec_3_1_3_25 [3.1.3.25] +h2o -pi
    myo_inositol
    <-> ec_2_4_1_123 [2.4.1.123] +udp_d_galactose -udp -hplus
    d_galactosyl_1_3_1d_myo_inositol
    <-> ec_2_4_1_82 [2.4.1.82] +sucrose -myo_inositol
    raffinose
    <-> ec_2_4_1_166 [2.4.1.166] -sucrose
    1f_d_galactosylraffinose
    <-> ec_2_4_1_167 [2.4.1.167] +sucrose +udp_d_galactose -udp -hplus
    planteose
  }

  branch from raffinose side left {
    raffinose
    <-> . +h2o +sucrose
    d_galactopyranose
  }

  branch from sucrose side right {
    sucrose
    <-> ec_2_7_1_211 [2.7.1.211] +n_phosphonato_l_histidine +l_histidine
    sucrose_6g_phosphate
  }

  branch from udp_d_galactose side left {
    udp_d_galactose
    <-> ec_2_4_1_303 [2.4.1.303] +n_acetyl_d_glucosaminyl_1_diphospho_ditrans_poly +udp +hplus
    d_gal_1_3_d_glcnac_diphospho_ditrans_octacis_un
  }

  branch from udp_d_galactose side right {
    udp_d_galactose
    <-> ec_2_4_1_304 [2.4.1.304] +n_acetyl_d_glucosaminyl_1_diphospho_ditrans_poly +udp +hplus
    d_gal_1_4_d_glcnac_diphospho_ditrans_octacis_un
  }
}
