# Ingested from Rhea. The spine follows the carbon skeleton from
# N-(1,2-saturated very-long-chain fatty acyl)-(R)-4-hydroxysphingoid base to cytidine 5'-monophosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n-1-2-saturated-to-cytidine-5-monophosphate "N-(1,2-saturated… to cytidine 5'-monophosphate" {
  spacing 280

  spine at 0,0 {
    n_1_2_saturated_very_long_chain_fatty_acyl_r_4_h
    <-> ec_1_14_18_6 [1.14.18.6] +fe2 +o2 +hplus -iron -h2o
    n_r_2_hydroxy_very_long_chain_fatty_acyl_r_4_hyd
    <-> ec_2_7_1_227 [2.7.1.227] +1_phosphatidyl_1d_myo_inositol -dag
    1d_myo_inositol_1_phospho_n_r_2_hydroxy_very_lon
    <-> ec_2_4_1_370 [2.4.1.370] +gdp_d_mannose -gdp -hplus
    d_mannosyl_1_6_1d_myo_inositol_1_phospho_n_r_2
    <-> ec_2_7_1_228 [2.7.1.228] +1_phosphatidyl_1d_myo_inositol -dag
    d_mannosyl_6_1d_myo_inositol_phospho_1_6_1d_myo
    <-> ec_2_7_8_2 [2.7.8.2] +cdp_choline +dag -cytidine_5_monophosphate -hplus
    phosphatidylcholine
  }

  branch from 1d_myo_inositol_1_phospho_n_r_2_hydroxy_very_lon side left {
    1d_myo_inositol_1_phospho_n_r_2_hydroxy_very_lon
    <-> . +udp_d_glucuronate +udp +hplus
    d_glucuronosyl_1_6_1d_myo_inositol_1_phospho_n
  }

  branch from dag side right {
    dag
    <-> . +1_phosphatidyl_1d_myo_inositol +n_acylsphingosine
    n_acylsphingosine_1d_myo_inositol
  }

  branch from phosphatidylcholine side left {
    phosphatidylcholine
    <-> . +3_acyl_sn_glycerol +1_3_diacyl_sn_glycerol
    acyl_sn_glycero_3_phosphocholine
  }

  branch from cytidine_5_monophosphate side right {
    cytidine_5_monophosphate
    <-> . +d_galactosyl_1_3_n_acetyl_neuraminosyl_2_6_n_ac +cmp_n_acetyl_neuraminate +hplus
    n_acetyl_neuraminosyl_2_3_d_galactosyl_1_3_n_ace
  }
}
