# Ingested from Rhea. The spine follows the carbon skeleton from
# N-acetyl-beta-neuraminate 9-phosphate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n-acetyl-beta-neuraminate-to-h2o "N-acetyl-beta-neuraminate… to H2O" {
  spacing 216

  spine at 0,0 {
    n_acetyl_beta_neuraminate_9_phosphate
    <-> ec_3_1_3_29 [3.1.3.29] +h2o -phosphate
    n_acetyl_alpha_neuraminate
    <-> ec_2_7_7_43 [2.7.7.43] +ctp -diphosphate
    cmp_n_acetyl_beta_neuraminate
    <-> ec_1_14_18_2 [1.14.18.2] +nadh +h +o2 -nad -h2o
    cmp_n_glycoloyl_beta_neuraminate
  }
}
