# Ingested from Rhea. The spine follows the carbon skeleton from
# α-N-acetylneuraminosyl-(2→3)-[β-D-galactosyl-(1→3)-N-acetyl-β-D-galactosaminyl-(1→4)]-β-D-galactosyl-(1→4)-β-D-glucosyl-(1↔1')-ceramide(1−) to trimethylamine N-oxide; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n-acetylneuraminosyl-2-to-trimethylamine-n-oxid "α-N-acetylneuraminosyl-(2… to trimethylamine N-oxide" {
  spacing 188

  spine at 0,0 {
    n_acetylneuraminosyl_2_3_d_galactosyl_1_3_n_ace
    <-> . +gdp_l_fucose -gdp -hplus
    l_fuc_1_2_d_gal_1_3_d_glcnac_1_4_neu5ac_2_3_d_g
    <-> . +h2o -n_acylsphingoid
    l_fucp_1_2_d_galp_1_3_d_galpnac_1_4_neup5ac_2_3
    <-> . +n_acylsphingoid +phosphatidylcholine -dag
    sphingomyelin
    <-> . -choline
    n_acyl_sphingosyl_1_3_cyclicphosphate
    <-> ec_4_3_99_4 [4.3.99.4] +choline -acetaldehyde
    trimethylammonium
    <-> ec_1_14_13_148 [1.14.13.148] +nadph +o2 -nadp -h2o
    trimethylamine_n_oxide
  }

  branch from gdp_l_fucose side left {
    gdp_l_fucose
    <-> . +neu5ac_2_3_d_gal_1_4_d_glcnac_1_3_d_gal_1_4_d_g +gdp +hplus
    neu5ac_2_3_d_gal_1_4_l_fuc_1_3_d_glcnac_1_3_d_g
  }

  branch from gdp_l_fucose side right {
    gdp_l_fucose
    <-> . +d_galactosyl_1_3_n_acetyl_d_glucosaminyl_1_3_d +gdp +hplus
    l_fucosyl_1_2_d_galactosyl_1_3_n_acetyl_d_gluco
  }
}
