# Ingested from Rhea. The spine follows the carbon skeleton from
# N-acetyl-β-D-galactosaminyl-(1→4)-[α-N-acetylneuraminyl-(2→3)]-β-D-galactosyl-(1→4)-β-D-glucosyl-(1↔1)-ceramide(1−) to N-acetyl-β-D-galactosaminyl-(1→4)-[α-N-acetylneuraminosyl-(2→3)]-β-D-galactosyl-(1→3)-N-acetyl-β-D-galactosaminyl-(1→4)-[α-N-acetylneuraminosyl-(2→3)]-β-D-galactosyl-(1→4)-β-D-glucosyl-(1↔1')-ceramide(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n-acetyl-d-galactosamin-to-n-acetyl-d-galactosam "N-acetyl-β-D-galactosamin… to N-acetyl-β-D-galactosamin…" {
  spacing 152

  spine at 0,0 {
    n_acetyl_d_galactosaminyl_1_4_n_acetylneuraminyl
    <-> . +udp_d_galactose -udp -hplus
    n_acetylneuraminosyl_2_3_d_galactosyl_1_3_n_ace
    <-> . +cmp_n_acetyl_neuraminate -cytidine_5_monophosphate -hplus
    n_acetylneuraminosyl_2_3_d_galactosyl_1_3_n_ace
    <-> . +udp_n_acetyl_d_galactosamine -udp -hplus
    n_acetyl_d_galactosaminyl_1_4_n_acetylneuraminos
  }

  branch from n_acetylneuraminosyl_2_3_d_galactosyl_1_3_n_ace side left {
    n_acetylneuraminosyl_2_3_d_galactosyl_1_3_n_ace
    <-> . +cmp_n_acetyl_9_o_acetylneuraminate +cytidine_5_monophosphate +hplus
    n_acetyl_9_o_acetylneuraminosyl_2_3_d_galactosy
  }

  branch from cytidine_5_monophosphate side right {
    cytidine_5_monophosphate
    <-> . +n_acetylneuraminyl_2_3_d_galactosyl_1_4_n_acety +cmp_n_acetyl_neuraminate +hplus
    n_acetylneuraminyl_2_8_n_acetylneuraminyl_2_3_d
  }
}
