# Ingested from Rhea. The spine follows the carbon skeleton from
# N-lauroyl-1,2-dioleoyl-sn-glycero-3-phosphoethanolamine(1−) to diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n-lauroyl-1-2-dioleoyl-sn-to-diphosphate "N-lauroyl-1,2-dioleoyl-sn… to diphosphate" {
  spacing 200

  spine at 0,0 {
    n_lauroyl_1_2_dioleoyl_sn_glycero_3_phosphoethan
    <-> . +h2o -1_2_dioleoyl_sn_glycero_3_phosphate -hplus
    n_dodecanoyl_ethanolamine
    <-> . +h2o -ethanolaminium
    dodecanoate
    <-> . +atp +coa -amp -ppi
    lauroyl_coa
  }

  branch from dodecanoate side left {
    dodecanoate
    <-> . +nadh +hplus +nad +h2o
    dodecanal
  }

  branch from dodecanoate side right {
    dodecanoate
    <-> ec_1_14_14_130 [1.14.14.130] +fmnh2 +o2 +fmn +h2o +hplus
    7_hydroxylaurate
  }

  branch from ethanolaminium side left {
    ethanolaminium
    <-> . +1_hexadecanoyl_sn_glycero_3_phosphoethanolamine +h2o +hplus
    1_palmitoyl_sn_glycerol_3_phosphate
  }

  branch from ethanolaminium side right {
    ethanolaminium
    <-> . +1_myristoyl_sn_glycero_3_phosphoethanolamine
    1_myristoyl_sn_glycero_2_3_cyclic_phosphate
  }

  branch from lauroyl_coa side left {
    lauroyl_coa
    <-> . +fad +hplus +fadh2
    trans_dodec_2_enoyl_coa
  }

  branch from lauroyl_coa side right {
    lauroyl_coa
    <-> . +acetyl_coa +coa
    3_oxotetradecanoyl_coa
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_95 [4.2.3.95] +fpp
    cuprenene
  }

  branch from ppi side right {
    ppi
    <-> ec_4_2_3_94 [4.2.3.94] +fpp
    curcumene
  }
}
