# Ingested from Rhea. The spine follows the carbon skeleton from
# N-methylputrescinium(2+) to 4-methylaminobutanal; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n-methylputrescinium-to-4-methylaminobutanal "N-methylputrescinium to 4-methylaminobutanal" {
  spacing 152

  spine at 0,0 {
    n_methylputrescinium
    <-> . +o2 +h2o -h2o2 -nh3
    4_methylammoniobutanal
    <-> . -h2o
    1_methylpyrrolinium
    <-> . +3_oxoglutarate +hplus -co2
    4_1_methylpyrrolidin_2_yl_3_oxobutanoate
    <-> . +co2 +h -1_methylpyrrolinium
    3_oxoglutaric_acid
    <-> . +1_methylpyrrolinium +h2o
    4_methylaminobutanal
  }
}
