# Ingested from Rhea. The spine follows the carbon skeleton from
# N1-acetylsperminium(3+) to ammonium; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n1-acetylsperminium-to-ammonium "N1-acetylsperminium to ammonium" {
  spacing 188

  spine at 0,0 {
    n1_acetylsperminium
    <-> . +o2 +h2o -3_ammoniopropanal -h2o2
    n1_acetylspermidinium
    <-> . +o2 +h2o -trimethylenediaminium -h2o2
    4_acetamidobutanal
    <-> . +nad +h2o -nadh -hplus
    4_acetamidobutanoate
    <-> ec_3_5_1_63 [3.5.1.63] +h2o -acetate
    gaba
    <-> . +o2 +h2o -h2o2 -nh3
    4_oxobutanoate
  }

  branch from 4_oxobutanoate side left {
    4_oxobutanoate
    <-> ec_1_1_1_n11 [1.1.1.n11] +nadp +nadph +hplus
    4_hydroxybutyrate
  }

  branch from nh3 side right {
    nh3
    <-> . +l_alaninamide +h2o
    alanine
  }
}
