# Ingested from Rhea. The spine follows the carbon skeleton from
# N2-(4-aminobutanoyl)-L-ornithine(1+) to succinyl-CoA(5−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n2-4-aminobutanoyl-l-or-to-succinyl-coa "N2-(4-aminobutanoyl)-L-or… to succinyl-CoA" {
  spacing 264

  spine at 0,0 {
    n2_4_aminobutanoyl_l_ornithine
    <-> ec_3_4_13_4 [3.4.13.4] +h2o -ornithine
    gaba
    <-> ec_2_6_1_96 [2.6.1.96] +glyoxylate -glycine
    4_oxobutanoate
    <-> ec_1_2_1_76 [1.2.1.76] +nadp +coa -nadph -hplus
    succinyl_coa
  }
}
