# Ingested from Rhea. The spine follows the carbon skeleton from
# N4-[α-D-Man-(1→2)-α-D-Man-(1→2)-α-D-Man-(1→3)-[α-D-Man-(1→2)-α-D-Man-(1→3)-[α-D-Man-(1→2)-α-D-Man-(1→6)]-α-D-Man-(1→6)]-β-D-Man-(1→4)-β-D-GlcNAc-(1→4)-β-D-GlcNAc]-L-Asn residue to mannosylinositol-1-phosphophytoceramide(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n4-d-man-1-2-d-man-to-mannosylinositol-1-phosph "N4-[α-D-Man-(1→2)-α-D-Man… to mannosylinositol-1-phosph…" {
  spacing 280

  spine at 0,0 {
    n4_d_man_1_2_d_man_1_2_d_man_1_3_d_man_1_2_d_man
    <-> ec_3_2_1_209 [3.2.1.209] +h2o -d_mannose
    n4_d_manp_1_2_d_manp_1_2_d_manp_1_3_d_manp_1_3_d
    <-> ec_3_2_1_113 [3.2.1.113] +h2o -d_mannose
    n_man_1_3_man_1_3_man_1_6_man_1_6_man_1_4_glcnac
    <-> . +inositol_1_phosphophytoceramide +d_mannose -h2o
    mannosylinositol_1_phosphophytoceramide
  }

  branch from d_mannose side left {
    d_mannose
    <-> . +n4_d_man_1_2_d_man_1_2_d_man_1_3_d_man_1_2_d_man +h2o
    n4_d_man_1_2_d_man_1_3_d_man_1_2_d_man_1_3_d_man
  }

  branch from mannosylinositol_1_phosphophytoceramide side right {
    mannosylinositol_1_phosphophytoceramide
    <-> . +inositol_1_phosphophytoceramide +gdp +hplus
    gdp_d_mannose
  }
}
