# Ingested from Rhea. The spine follows the carbon skeleton from
# N4-{β-D-GlcNAc-(1→2)-α-D-Man-(1→3)-[β-D-GlcNAc-(1→4)]-[β-D-Gal-(1→4)-β-D-GlcNAc-(1→2)-α-D-Man-(1→6)]-β-D-Man-(1→4)-β-D-GlcNAc-(1→4)-β-D-GlcNAc}-L-Asn to cytidine 5'-monophosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n4-d-glcnac-1-2-d-to-cytidine-5-monophosphate "N4-{β-D-GlcNAc-(1→2)-α-D-… to cytidine 5'-monophosphate" {
  spacing 164

  spine at 0,0 {
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_4_d_gal_1_4
    <-> . +cmp_n_acetyl_neuraminate -cytidine_5_monophosphate -hplus
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_4_neu5ac_2
    <-> . +udp_d_galactose -udp -hplus
    n4_d_gal_1_4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_4
    <-> . +cmp_n_acetyl_neuraminate -cytidine_5_monophosphate -hplus
    n4_neu5ac_2_3_d_gal_1_4_d_glcnac_1_2_d_man_1_3_d
  }

  branch from udp_d_galactose side left {
    udp_d_galactose
    <-> . +n_acetyl_d_glucosaminide +udp +hplus
    d_galactosyl_1_3_n_acetyl_d_glucosaminide
  }

  branch from udp_d_galactose side right {
    udp_d_galactose
    <-> . +o_n_acetyl_d_galactosaminyl_l_serine +udp +hplus
    o3_d_galactosyl_1_3_n_acetyl_d_galactosaminyl_l
  }
}
