# Ingested from Rhea. The spine follows the carbon skeleton from
# N6,N6,O-tridemethylpuromycin to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway n6-n6-o-tridemethylpuromy-to-h2o "N6,N6,O-tridemethylpuromy… to H2O" {
  spacing 236

  spine at 0,0 {
    n6_n6_o_tridemethylpuromycin
    <-> . +h2o -3_amino_3_deoxyadenosine
    l_tyrosine
    <-> . +h +3_amino_3_deoxyadenosine +phosphate -h2o
    3_amino_3_deoxy_amp
    <-> . +diphosphate -h2o
    3_amino_3_deoxyatp
  }

  branch from l_tyrosine side left {
    l_tyrosine
    <-> . +co2 +nadp +e_4_hydroxyphenylacetaldehyde_oxime +h2o +h +nadph
    o2
  }

  branch from l_tyrosine side right {
    l_tyrosine
    <-> ec_1_14_16_1 [1.14.16.1] +5_6_7_8_tetrahydrobiopterin +o2 +l_phenylalanine +h2o
    tetrahydrobiopterin_4a_carbinolamine
  }

  branch from h2o side left {
    h2o
    <-> ec_3_6_3_39 [3.6.3.39] +h +adp +phosphate +atp
    octyl_6_o_d_galactofuranosyl_d_glucopyranoside
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_39 [3.6.3.39] +h +adp +octyl_alpha_d_mannopyranoside +phosphate +octyl_alpha_d_mannopyranoside
    atp
  }

  branch from h2o side left {
    h2o
    <-> ec_3_6_3_39 [3.6.3.39] +h +adp +phosphate +atp
    octyl_alpha_d_galactopyranoside
  }

  branch from h2o side right {
    h2o
    <-> ec_3_6_3_39 [3.6.3.39] +h +adp +phosphate +atp
    octyl_2_acetamido_2_deoxy_alpha_d_glucopyranosid
  }

  branch from l_tyrosine side left {
    l_tyrosine
    <-> ec_1_14_16_1 [1.14.16.1] +5_6_7_8_tetrahydrobiopterin +o2 +l_phenylalanine
    4as_6r_4a_hydroxy_l_erythro_5_6_7_8_tetrahydrob
  }

  branch from l_tyrosine side right {
    l_tyrosine
    <-> ec_3_4_11_1 [3.4.11.1] +l_leucine +h2o
    leu_tyr
  }

  branch from h side left {
    h
    <-> ec_3_6_3_42 [3.6.3.42] +adp +phosphate +atp +h2o
    cellotetraose
  }

  branch from h side right {
    h
    <-> ec_3_6_3_42 [3.6.3.42] +adp +phosphate +atp +h2o
    cellopentaose
  }

  branch from phosphate side left {
    phosphate
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +atp +h2o
    cephalosporin_c
  }

  branch from phosphate side right {
    phosphate
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +atp +h2o
    terpentecin
  }

  branch from diphosphate side left {
    diphosphate
    <-> ec_4_2_3_9 [4.2.3.9] +germacrene_a +h
    farnesyl_diphosphate
  }

  branch from diphosphate side right {
    diphosphate
    <-> . +undecaprenyl_diphosphate +h +ipp
    all_trans_decaprenyl_diphosphate
  }
}
