# Ingested from Rhea. The spine follows the carbon skeleton from
# NADH to CDP-D-arabinitol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway nadh-to-cdp-d-arabinitol-null "NADH to CDP-D-arabinitol" {
  spacing 308

  spine at 0,0 {
    nadh
    <-> . +2r_3r_4s_5s_1_3_4_5_tetrahydroxy_6_oxohexan_2_a -nad
    2_amino_2_deoxy_d_mannitol
    <-> . +h +phosphate -h2o
    2_amino_2_deoxy_mannitol_6_phosphate
    <-> . +2_oxoglutarate -keto_d_fructose_6_phosphate
    l_glutamate
    <-> ec_2_2_1_1 [2.2.1.1] +d_glyceraldehyde_3_phosphate +keto_d_fructose_6_phosphate -d_erythrose_4_phosphate
    d_xylulose_5_phosphate
    <-> . +ctp +h -cdp_d_xylulose
    diphosphate
    <-> . +h +nadph +cdp_d_xylulose -cdp_d_arabinitol
    nadp
  }

  branch from nad side left {
    nad
    <-> . +nadh +acetyl_coa +fadh2 +h +coa +9z_12z_octadecadienoyl_coa +h2o
    fad
  }

  branch from nad side right {
    nad
    <-> . +nadh +acetyl_coa +fadh2 +h +fad +coa +h2o
    8z_11z_icosadienoyl_coa
  }

  branch from h2o side left {
    h2o
    <-> . +l_aspartate +l_cysteine +l_phenylalanine
    cystyl_aspartyl_phenylalanine
  }

  branch from h2o side right {
    h2o
    <-> . +l_cysteine
    cystyl_cysteine
  }

  branch from l_glutamate side left {
    l_glutamate
    <-> . +l_leucine +h2o
    glutamyl_leucine
  }

  branch from l_glutamate side right {
    l_glutamate
    <-> . +l_histidine +l_methionine +h2o
    glutamyl_methioninyl_histidine
  }

  branch from keto_d_fructose_6_phosphate side left {
    keto_d_fructose_6_phosphate
    <-> . +beta_d_fructose +phosphoenolpyruvate
    pyruvate
  }

  branch from keto_d_fructose_6_phosphate side right {
    keto_d_fructose_6_phosphate
    <-> .
    beta_d_glucose_6_phosphate
  }

  branch from diphosphate side left {
    diphosphate
    <-> ec_2_5_1_87 [2.5.1.87] +di_trans_poly_cis_decaprenyl_diphosphate +ipp
    2e_6e_farnesyl_diphosphate
  }

  branch from diphosphate side right {
    diphosphate
    <-> . +h +amp +11z_octadecenoyl_coa +coa +vaccenic_acid
    atp
  }

  branch from nadp side left {
    nadp
    <-> . +h +nadph +3_oxoheneicosanoyl_coenzyme_a
    3_hydroxyheneicosanoyl_coenzyme_a
  }

  branch from nadp side right {
    nadp
    <-> . +h +nadph +2e_henicosenoyl_coa
    heneicosanoyl_coenzyme_a
  }

  branch from nadh side left {
    nadh
    <-> . +acetyl_coa +fadh2 +h +fad +coa +nad +h2o
    5z_8z_11z_eicosatrienoyl_coenzyme_a
  }

  branch from nadh side right {
    nadh
    <-> . +acetyl_coa +fadh2 +h +fad +coa +nad +h2o
    7z_10z_13z_16z_docosatetraenoyl_coa
  }

  branch from nad side left {
    nad
    <-> . +nadh +acetyl_coa +fadh2 +h +fad +coa +h2o
    4z_7z_10z_13z_16z_docosapentaenoyl_coa
  }

  branch from nad side right {
    nad
    <-> . +nadh +acetyl_coa +fadh2 +h +fad +coa +h2o
    11z_14z_icosadienoyl_coa
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    3beta_16alpha_dihydroxy_androst_5_en_17_one
  }

  branch from h side right {
    h
    <-> . +adp +phosphate +atp +h2o
    trans_cis_cis_2_11_14_eicosatrienoic_acid
  }

  branch from phosphate side left {
    phosphate
    <-> . +h +adp +atp +h2o
    31_o_desmethyl_19_hydroxy_37_39_epoxy_tacrolimus
  }

  branch from phosphate side right {
    phosphate
    <-> . +h +adp +atp +h2o
    17_estradiol_3_o_d_glucuronide
  }

  branch from h2o side left {
    h2o
    <-> . +l_glutamine +l_cysteine +l_methionine
    cystyl_glutaminyl_methionine
  }

  branch from h2o side right {
    h2o
    <-> . +l_leucine +l_threonine +l_cysteine
    cystyl_leucyl_threonine
  }

  branch from 2_oxoglutarate side left {
    2_oxoglutarate
    <-> ec_1_1_1_42 [1.1.1.42] +co2 +nadph +nadp
    d_erythro_isocitrate
  }

  branch from 2_oxoglutarate side right {
    2_oxoglutarate
    <-> ec_1_1_1_286 [1.1.1.286] +nadh +d_erythro_isocitrate +nad
    co2
  }

  branch from l_glutamate side left {
    l_glutamate
    <-> . +l_methionine +h2o
    glutamyl_methionine
  }

  branch from l_glutamate side right {
    l_glutamate
    <-> . +l_lysine +l_threonine +h2o
    glutamyl_threonyl_lysine
  }
}
