# Ingested from Rhea. The spine follows the carbon skeleton from
# NADH to D-Allulose 6-phosphate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway nadh-to-d-allulose-6-phosphate-null "NADH to D-Allulose 6-phosphate" {
  spacing 332

  spine at 0,0 {
    nadh
    <-> ec_1_1_1_12 [1.1.1.12] +d_allulose +h -nad
    d_sorbitol_13_c6
    <-> ec_1_1_1_21 [1.1.1.21] +nadp -d_allose -nadph
    h
    <-> . +d_allose
    d_allopyranose
    <-> ec_2_7_1_1 [2.7.1.1] +h +atp -6_o_phosphonohexopyranose
    adp
    <-> ec_5_3_1_6 [5.3.1.6] +6_o_phosphonohexopyranose
    d_allulose_6_phosphate
  }

  branch from nad side left {
    nad
    <-> ec_1_1_1_71 [1.1.1.71] +nadh +neoabietadienal +h
    palustradienol
  }

  branch from nad side right {
    nad
    <-> ec_1_1_1_71 [1.1.1.71] +nadh +neoabietadienal +h
    isopimara_7_15_dienol
  }

  branch from h side left {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    bleomycin_a2
  }

  branch from h side right {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    bleomycin_b2
  }

  branch from nadph side left {
    nadph
    <-> ec_1_1_1_71 [1.1.1.71] +h +phellandral +nadp
    nerol
  }

  branch from nadph side right {
    nadph
    <-> ec_1_1_1_71 [1.1.1.71] +h +11r_dihydroartemisinic_aldehyde +nadp
    drimenol
  }

  branch from d_allopyranose side left {
    d_allopyranose
    <-> .
    d_galactofuranose
  }

  branch from adp side right {
    adp
    <-> ec_3_6_3_44 [3.6.3.44] +h +phosphate +atp +h2o
    avilamycin_a
  }

  branch from adp side left {
    adp
    <-> ec_3_6_3_44 [3.6.3.44] +h +phosphate +atp +h2o
    colistin_b
  }

  branch from 6_o_phosphonohexopyranose side right {
    6_o_phosphonohexopyranose
    <-> ec_2_7_1_1 [2.7.1.1] +h +atp +adp
    alpha_d_glucose
  }

  branch from 6_o_phosphonohexopyranose side left {
    6_o_phosphonohexopyranose
    <-> ec_2_7_1_1 [2.7.1.1] +h +atp +adp
    beta_d_fructose
  }

  branch from nadh side right {
    nadh
    <-> ec_1_1_1_71 [1.1.1.71] +h +isopimara_7_15_dienol +nad
    palustradienal
  }

  branch from nadh side left {
    nadh
    <-> ec_1_1_1_71 [1.1.1.71] +h +dehydroabietadienal +nad
    dehydroabietadienol
  }

  branch from d_allulose side right {
    d_allulose
    <-> ec_1_1_1_15 [1.1.1.15] +nadh +h +nad
    d_altritol
  }

  branch from d_allulose side left {
    d_allulose
    <-> ec_5_3_1_3 [5.3.1.3]
    d_altropyranose
  }

  branch from h side right {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    thiostrepton
  }

  branch from h side left {
    h
    <-> ec_3_6_3_44 [3.6.3.44] +adp +phosphate +atp +h2o
    pentalenolactone_d
  }

  branch from nad side right {
    nad
    <-> ec_1_1_1_71 [1.1.1.71] +nadh +h +isopimara_7_15_dienol
    isopimara_7_15_dienal
  }

  branch from nad side left {
    nad
    <-> ec_1_1_1_71 [1.1.1.71] +nadh +2e_geranial +h
    r_linalool
  }

  branch from nadp side right {
    nadp
    <-> ec_1_1_1_71 [1.1.1.71] +2e_geranial +h +nadph
    thujan_3_ol
  }

  branch from nadp side left {
    nadp
    <-> ec_1_1_1_71 [1.1.1.71] +2e_geranial +h +nadph
    r_terpineol
  }

  branch from nadph side right {
    nadph
    <-> ec_1_1_1_71 [1.1.1.71] +2e_geranial +h +nadp
    thujan_3_ol
  }

  branch from nadph side left {
    nadph
    <-> ec_1_1_1_71 [1.1.1.71] +2e_geranial +h +nadp
    1r_2s_4r_borneol
  }

  branch from atp side right {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    neopentalenolactone_d
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_44 [3.6.3.44] +h +adp +phosphate +h2o
    neopentalenolactone_f
  }

  branch from adp side right {
    adp
    <-> ec_3_6_3_44 [3.6.3.44] +h +phosphate +atp +h2o
    pentalenolactone_e
  }
}
