# Ingested from Rhea. The spine follows the carbon skeleton from
# NADH to 5-Oxo-6-trans-leukotriene B4; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway nadh-to-5-oxo-6-trans-leukotriene "NADH to 5-Oxo-6-trans-leukotriene…" {
  spacing 204

  spine at 0,0 {
    nadh
    <-> ec_1_3_1_48 [1.3.1.48] +h +12_dehydro_leukotriene_b4 -nad
    leukotriene_b4
    <-> . +nadp -h -nadph
    5_oxo_12_s_hydroxy_eicosa_6e_8z_10e_14z_tetraeno
    <-> . +h
    5_oxo_6_trans_leukotriene_b4
  }

  branch from h side left {
    h
    <-> . +adp +phosphate +atp +h2o
    troglitazone_glucuronide
  }

  branch from h side right {
    h
    <-> . +adp +phosphate +atp +h2o
    telmisartan_glucuronide
  }
}
