# Ingested from Rhea. The spine follows the carbon skeleton from
# α-Neu5Ac-(2→8)-α-Neu5Ac-(2→3)-β-Gal-(1→3)-β-GalNAc-(1→4)-[α-Neu5Ac-(2→8)-α-Neu5Ac-(2→3)]-β-Gal-(1→4)-β-Glc-(1↔1')-Cer(d18:1/18:0)(4−) to cytidine 5'-monophosphate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway neu5ac-2-8-neu5ac-to-cytidine-5-monophosphate "α-Neu5Ac-(2→8)-α-Neu5Ac-(… to cytidine 5'-monophosphate" {
  spacing 152

  spine at 0,0 {
    neu5ac_2_8_neu5ac_2_3_gal_1_3_galnac_1_4_neu5ac
    <-> . +h2o -n_acetylneuraminate
    neu5ac_2_3_gal_1_3_galnac_1_4_neu5ac_2_8_neu5ac
    <-> . +h2o -n_acetylneuraminate
    gal_1_3_galnac_1_4_neu5ac_2_8_neu5ac_2_3_gal_1
    <-> . +h2o -n_acetylneuraminate
    ganglioside_gm1
    <-> . +cmp_n_acetyl_neuraminate -cytidine_5_monophosphate -hplus
    neu5ac_2_3_gal_1_3_galnac_1_4_neu5ac_2_3_gal_1
  }

  branch from n_acetylneuraminate side left {
    n_acetylneuraminate
    <-> . +neu5ac_2_8_neu5ac_2_3_gal_1_3_galnac_1_4_neu5ac +h2o
    neu5ac_2_3_gal_1_3_galnac_1_4_neu5ac_2_8_neu5ac
  }

  branch from cytidine_5_monophosphate side right {
    cytidine_5_monophosphate
    <-> . +neu5ac_2_3_d_gal_1_3_d_glcnac_1_3_d_gal_1_4_d_g +cmp_n_acetyl_neuraminate +hplus
    neu5ac_2_3_d_gal_1_3_neu5ac_2_6_d_glcnac_1_3_d
  }
}
