# Ingested from Rhea. The spine follows the carbon skeleton from
# O-((3R)-atrochrysone carboxylpantetheine-4'-phosphoryl)-L-serine(1−) residue to phlegmacin(1−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway o-3r-atrochrysone-to-phlegmacin "O-((3R)-atrochrysone… to phlegmacin" {
  spacing 220

  spine at 0,0 {
    o_3r_atrochrysone_carboxylpantetheine_4_phosphor
    <-> . +h2o -holo-acp -hplus
    3r_atrochrysone_carboxylate
    <-> . +hplus -co2
    3r_atrochrysone
    <-> ec_2_1_1_404 [2.1.1.404] +sam -sah -hplus
    r_torosachrysone
    <-> ec_1_11_2_7 [1.11.2.7] +h2o2 -h2o -hplus
    phlegmacin
  }

  branch from sah side left {
    sah
    <-> ec_2_1_1_77 [2.1.1.77] +d_aspartate +sam
    d_aspartate_methyl_ester
  }

  branch from sah side right {
    sah
    <-> . +esculetin +sam +hplus
    isoscopoletin
  }
}
