# Ingested from Rhea. The spine follows the carbon skeleton from
# O-(S-hexanoylpantetheine-4'-phosphoryl)serine(1−) residue to O-(S-octanoylpantetheine-4-phosphoryl)serine(1−) residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway o-s-hexanoylpantetheine-to-o-s-octanoylpantethei "O-(S-hexanoylpantetheine-… to O-(S-octanoylpantetheine-…" {
  spacing 152

  spine at 0,0 {
    o_s_hexanoylpantetheine_4_phosphoryl_serine_1
    <-> . +malonyl-acp +hplus -holo-acp -co2
    o_s_3_oxooctanoylpantetheine_4_phosphoryl_serine
    <-> . +nadph +hplus -nadp
    o_s_3r_hydroxyoctanoylpantetheine_4_phosphoryl_s
    <-> . -h2o
    o_s_2e_octenoylpantetheine_4_phosphoryl_serine_1
    <-> . +nadph +hplus -nadp
    o_s_octanoylpantetheine_4_phosphoryl_serine_1
  }
}
