# Ingested from Rhea. The spine follows the carbon skeleton from
# O-[S-(3R)-hydroxyhexadecanoylpantetheine-4'-phosphoryl]serine(1−) residue to O-(pantetheine-4'-phosphoryl)serine(1−) residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway o-s-3r-hydroxyhexadeca-to-o-pantetheine-4-phosph "O-[S-(3R)-hydroxyhexadeca… to O-(pantetheine-4'-phospho…" {
  spacing 220

  spine at 0,0 {
    o_s_3r_hydroxyhexadecanoylpantetheine_4_phosphor
    <-> . -h2o
    o_s_2e_hexadecenoylpantetheine_4_phosphoryl_seri
    <-> . +nadph +hplus -nadp
    o_s_hexadecanoylpantetheine_4_phosphoryl_serine
    <-> ec_3_1_2_14 [3.1.2.14] +h2o -holo-acp -hplus
    palmitate
  }
}
