# Ingested from Rhea. The spine follows the carbon skeleton from
# oxaloacetate(2−) to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway oxaloacetate-to-succinate "oxaloacetate to succinate" {
  spacing 152

  spine at 0,0 {
    oxaloacetate
    <-> ec_2_3_3_1 [2.3.3.1] +acetyl_coa +h2o -coa -hplus
    citrate
    <-> ec_4_2_1_3 [4.2.1.3]
    d_threo_isocitrate
    <-> ec_4_1_3_1 [4.1.3.1] -succinate
    glyoxylate
  }
}
