# Ingested from Rhea. The spine follows the carbon skeleton from
# papaverine to (S)-laudanine(1+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway papaverine-to-s-laudanine "papaverine to (S)-laudanine" {
  spacing 220

  spine at 0,0 {
    papaverine
    <-> ec_1_3_3_8 [1.3.3.8] +h +h2o2 -o2
    s_tetrahydropapaverine
    <-> ec_2_1_1_337 [2.1.1.337] +sam -sah -hplus
    s_laudanosine
    <-> . +s_adenosyl_l_homocysteine +h -s_laudanine
    s_adenosyl_l_methionine
  }

  branch from o2 side left {
    o2
    <-> ec_1_14_11_13 [1.14.11.13] +gibberellin_a29 +co2 +h +succinate +2_oxoglutarate
    gibberellin_a20
  }

  branch from o2 side right {
    o2
    <-> ec_1_14_21_1 [1.14.21.1] +s_cheilanthifoline +h +nadph +nadp +h2o
    s_stylopine
  }

  branch from sah side left {
    sah
    <-> . +s_adenosyl_s_carboxymethyl_l_homocysteine_dizwit +5_hydroxyuridine_5_phosphate_1 +hplus
    5_carboxymethoxy_uridine_5_phosphate_2
  }

  branch from sah side right {
    sah
    <-> . +5_n7_methyl_5_triphosphoguanosine_2_o_methyl_pur +sam +hplus
    5_n7_methyl_5_triphosphoguanosine_2_o_methyl_pur
  }

  branch from s_adenosyl_l_methionine side left {
    s_adenosyl_l_methionine
    <-> ec_2_1_1_201 [2.1.1.201] +s_adenosyl_l_homocysteine +h +6_methoxy_3_methyl_2_all_trans_polyprenyl_1_4_be
    2_methoxy_6_all_trans_polyprenyl_1_4_benzoquinol
  }

  branch from s_adenosyl_l_methionine side right {
    s_adenosyl_l_methionine
    <-> ec_2_1_1_114 [2.1.1.114] +s_adenosyl_l_homocysteine +h +3_polyprenyl_4_hydroxy_5_methoxybenzoate
    3_polyprenyl_4_5_dihydroxybenzoate
  }
}
