# Ingested from Rhea. The spine follows the carbon skeleton from
# paraoxon to maleylacetate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway paraoxon-to-maleylacetate "paraoxon to maleylacetate" {
  spacing 256

  spine at 0,0 {
    paraoxon
    <-> ec_3_1_8_1 [3.1.8.1] +h2o -4_nitrophenolate -hplus
    diethylphosphate
    <-> ec_1_14_13_29 [1.14.13.29] +4_nitrophenolate +nadh +o2 +hplus -nad -h2o
    2_hydroxy_4_nitrophenolate
    <-> ec_1_14_13_166 [1.14.13.166] +nadph +o2 -nitrite -nadp -h2o
    3_6_dioxocyclohexa_1_4_dien_1_olate
    <-> ec_1_6_5_7 [1.6.5.7] +nadh +hplus -nad
    benzene_1_2_4_triol
    <-> . +o2 -hplus
    3_hydroxy_cis_cis_muconate
    <-> .
    maleylacetate
  }

  branch from diethylphosphate side left {
    diethylphosphate
    <-> . +ethanol +ethyl_dihydrogen_phosphate +h2o
    h
  }

  branch from 4_nitrophenolate side right {
    4_nitrophenolate
    <-> ec_1_14_13_167 [1.14.13.167] +nadph +o2 +hplus +nitrite +nadp +h2o
    quinone
  }

  branch from 4_nitrophenolate side left {
    4_nitrophenolate
    <-> . +3_phosphonato_5_adenylyl_sulfate +adenosine_3_5_bismonophosphate
    4_nitrophenyl_sulfate
  }

  branch from nitrite side right {
    nitrite
    <-> ec_1_7_1_4 [1.7.1.4] +nadp +h2o +nadph +hplus
    nh3
  }

  branch from nitrite side left {
    nitrite
    <-> ec_3_5_99_9 [3.5.99.9] +2_nitroimidazole +h2o +hplus
    1_3_dihydro_2h_imidazol_2_one
  }

  branch from benzene_1_2_4_triol side right {
    benzene_1_2_4_triol
    <-> ec_1_14_13_219 [1.14.13.219] +nadph +o2 +hplus +nadp +h2o
    resorcinol
  }

  branch from maleylacetate side left {
    maleylacetate
    <-> ec_1_3_1_32 [1.3.1.32] +nadp +nadph +hplus
    3_oxoadipate
  }

  branch from maleylacetate side right {
    maleylacetate
    <-> ec_1_2_1_61 [1.2.1.61] +nad +h2o +nadh +hplus
    2z_4e_4_hydroxymuconic_semialdehyde
  }
}
