# Ingested from Rhea. The spine follows the carbon skeleton from
# pentadecan-1-ol to 16-feruloyloxypalmitate; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway pentadecan-1-ol-to-16-feruloyloxypalmitate "pentadecan-1-ol to 16-feruloyloxypalmitate" {
  spacing 244

  spine at 0,0 {
    pentadecan_1_ol
    <-> . +1_palmitoylglycerone_3_phosphate -palmitate -hplus
    1_pentadecylglycerone_3_phosphate
    <-> ec_1_14_14_80 [1.14.14.80] +palmitate +fmnh2 +o2 -fmn -h2o -hplus
    16_hydroxyhexadecanoate
    <-> ec_2_3_1_188 [2.3.1.188] +trans_feruloyl_coa -coa
    16_feruloyloxypalmitate
  }

  branch from palmitate side left {
    palmitate
    <-> . +1_palmitoyl_2_arachidonoyl_sn_glycero_3_phosphoc +h2o +hplus
    2_arachidonoyl_sn_glycero_3_phosphocholine
  }

  branch from 16_hydroxyhexadecanoate side right {
    16_hydroxyhexadecanoate
    <-> . +atp +coa +amp +ppi
    16_hydroxyhexadecanoyl_coa
  }

  branch from fmn side left {
    fmn
    <-> ec_1_14_14_42 [1.14.14.42] +l_tetrahomomethionine +fmnh2 +o2 +co2 +h2o +hplus
    e_7_methylsulfanyl_heptanal_oxime
  }
}
