# Ingested from Rhea. The spine follows the carbon skeleton from
# peonidin(1−) to (R)-norreticuline; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway peonidin-to-r-norreticuline "peonidin to (R)-norreticuline" {
  spacing 340

  spine at 0,0 {
    peonidin
    <-> ec_2_4_1_115 [2.4.1.115] +udp_d_glucose -udp
    peonidin_3_o_d_glucoside_betaine
    <-> ec_2_1_1_267 [2.1.1.267] +s_adenosyl_l_homocysteine -cyanidin_3_o_beta_d_glucoside
    s_s_adenosyl_l_methionine
    <-> . +s_reticuline -h -laudanine
    s_adenosyl_l_homocysteine
    <-> ec_2_1_1_291 [2.1.1.291] +h +laudanine -r_reticuline
    s_adenosyl_l_methionine
    <-> ec_2_1_1_115 [2.1.1.115] +s_adenosyl_l_homocysteine +r_reticuline -s_adenosyl_l_methionine
    r_norreticuline
  }

  branch from s_s_adenosyl_l_methionine side left {
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_145 [2.1.1.145] +s_adenosyl_l_homocysteine +e_2_methoxycarbonylmethyl_but_2_enedioate
    trans_aconitate
  }

  branch from s_s_adenosyl_l_methionine side right {
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_155 [2.1.1.155] +s_adenosyl_l_homocysteine +h +prunetin_5_olate
    genistein
  }

  branch from cyanidin_3_o_beta_d_glucoside side left {
    cyanidin_3_o_beta_d_glucoside
    <-> ec_2_3_1_215 [2.3.1.215] +cyanidin_3_6_p_caffeoyl_glucoside +coa +h
    trans_caffeoyl_coa
  }

  branch from cyanidin_3_o_beta_d_glucoside side right {
    cyanidin_3_o_beta_d_glucoside
    <-> . +glucose +h +h2o
    cyanidin_3_7_di_o_d_glucoside_betaine
  }

  branch from s_adenosyl_l_homocysteine side left {
    s_adenosyl_l_homocysteine
    <-> . +2_methyl_6_all_trans_nonaprenyl_1_4_benzoquinone +h +s_adenosyl_l_methionine
    2_all_trans_nonaprenyl_benzene_1_4_diol
  }

  branch from s_adenosyl_l_homocysteine side right {
    s_adenosyl_l_homocysteine
    <-> . +gentamicin_x2_cation +s_adenosyl_l_methionine +h
    gentamicin_a
  }

  branch from h side left {
    h
    <-> . +dtdp +calicheamicin_alpha1_i +dtdp_4_ethylamino_3_o_methyl_2_4_dideoxy_l_threo
    calicheamicin_psag
  }

  branch from h side right {
    h
    <-> . +calicheamicin_gamma_1_i +dtdp +calicheamicin_alpha1_i
    dtdp_3_o_methyl_beta_l_rhamnose
  }

  branch from s_adenosyl_l_methionine side left {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +h +c33_botryococcene
    3_20_dimethyl_1_2_21_22_tetradehydro_2_3_20_21_t
  }

  branch from s_adenosyl_l_methionine side right {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +h +a_c34_botryococcenes
    c33_botryococcene
  }

  branch from peonidin side left {
    peonidin
    <-> . +udp_d_galactose +udp
    peonidin_3_o_d_galactoside_betaine
  }

  branch from udp_d_glucose side right {
    udp_d_glucose
    <-> . +16_hydroxyhexadecanoate +udp +hplus
    16_d_glucopyranosyloxy_hexadecanoate
  }

  branch from udp_d_glucose side left {
    udp_d_glucose
    <-> . +quercetin_7_olate +udp +hplus
    quercetin_3_o_d_glucopyranoside
  }

  branch from s_adenosyl_l_homocysteine side right {
    s_adenosyl_l_homocysteine
    <-> . +sulochrin +s_adenosyl_l_methionine
    demethylsulochrin
  }

  branch from s_adenosyl_l_homocysteine side left {
    s_adenosyl_l_homocysteine
    <-> . +dtdp_3_n_methylamino_4_oxo_2_3_6_trideoxy_alpha +h +s_adenosyl_l_methionine
    dtdp_3_amino_2_3_6_trideoxy_d_threo_hexopyranos
  }

  branch from s_s_adenosyl_l_methionine side right {
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_159 [2.1.1.159] +s_adenosyl_l_homocysteine +h +caffeine
    1_7_dimethylxanthine
  }

  branch from s_s_adenosyl_l_methionine side left {
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_283 [2.1.1.283] +s_adenosyl_l_homocysteine +h +questin
    emodin
  }

  branch from cyanidin_3_o_beta_d_glucoside side right {
    cyanidin_3_o_beta_d_glucoside
    <-> . +glucose +h +h2o
    cyanidin_3_5_di_o_beta_d_glucoside
  }

  branch from cyanidin_3_o_beta_d_glucoside side left {
    cyanidin_3_o_beta_d_glucoside
    <-> . +udp +cyanidin_3_o_rutinoside
    udp_beta_l_rhamnose
  }

  branch from s_reticuline side right {
    s_reticuline
    <-> ec_2_1_1_115 [2.1.1.115] +s_adenosyl_l_homocysteine +h +s_adenosyl_l_methionine
    s_norreticuline
  }

  branch from s_reticuline side left {
    s_reticuline
    <-> . +o2 +nadph +nadp +h2o
    s_corytuberine
  }

  branch from h side right {
    h
    <-> . +2_oxoglutarate +dtdp_4_amino_2_4_dideoxy_beta_l_xylose +l_glutamate
    dtdp_4_oxo_2_deoxy_beta_l_xylose
  }

  branch from h side left {
    h
    <-> . +valienol_1_phosphate
    valienol_7_phosphate
  }

  branch from s_adenosyl_l_methionine side right {
    s_adenosyl_l_methionine
    <-> . +dtdp_3_n_methylamino_4_oxo_2_3_6_trideoxy_alpha +s_adenosyl_l_homocysteine
    dtdp_3_n_n_dimethylamino_2_3_6_trideoxy_4_keto_d
  }

  branch from s_adenosyl_l_methionine side left {
    s_adenosyl_l_methionine
    <-> ec_2_1_1_9 [2.1.1.9] +s_adenosyl_l_homocysteine +s_methyl_benzenecarbothioate +h
    thiobenzoate
  }
}
