# Ingested from Rhea. The spine follows the carbon skeleton from
# petiveriin to diiodine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway petiveriin-to-diiodine-null "petiveriin to diiodine" {
  spacing 284

  spine at 0,0 {
    petiveriin
    <-> ec_4_4_1_4 [4.4.1.4] -phenylmethanesulfenate
    2_aminoprop_2_enoate
    <-> ec_1_11_1_8 [1.11.1.8] +3_3_5_triiodo_l_thyronine +h2o -h -3_5_diiodo_l_tyrosine -h2o2
    3_iodo_l_tyrosine
    <-> ec_1_11_1_8 [1.11.1.8] +iodide +h -diiodine
    l_tyrosine
  }

  branch from 2_aminoprop_2_enoate side left {
    2_aminoprop_2_enoate
    <-> ec_4_4_1_4 [4.4.1.4] +homoisoalliin
    e_but_1_en_1_so_peroxol
  }

  branch from 2_aminoprop_2_enoate side right {
    2_aminoprop_2_enoate
    <-> ec_4_4_1_4 [4.4.1.4] +2_hydroxysulfanyl_ethanol
    2_hydroxyethiin
  }

  branch from phenylmethanesulfenate side left {
    phenylmethanesulfenate
    <-> . +petiveriin +h2o +nh4
    pyruvate
  }

  branch from h side right {
    h
    <-> . +udp +5_demethoxy_6_methoxypodophyllotoxin_7_glucoside +5_demethoxy_6_methoxypodophyllotoxin
    udp_alpha_d_glucose
  }

  branch from h side left {
    h
    <-> ec_2_4_1_237 [2.4.1.237] +udp +gossypetin_7_o_glucoside +udp_alpha_d_glucose
    3_3_4_5_7_8_hexahydroxyflavone
  }

  branch from h2o2 side right {
    h2o2
    <-> . +hexanedioyl_coa +o2 +h2o
    3_hydroxyadipyl_coa
  }

  branch from h2o2 side left {
    h2o2
    <-> . +5_hydroxyindol_3_yl_acetaldehyde +nh4 +serotonin +o2 +h2o
    pmf
  }

  branch from l_tyrosine side right {
    l_tyrosine
    <-> . +n_6_n_6_o_tridemethylpuromycin_5_phosphate +h2o
    3_amino_3_deoxy_amp
  }

  branch from l_tyrosine side left {
    l_tyrosine
    <-> . +glycine +h2o
    l_tyrosine_n_glycyl
  }

  branch from 2_aminoprop_2_enoate side right {
    2_aminoprop_2_enoate
    <-> ec_4_4_1_4 [4.4.1.4] +methylsulfanol
    s_methylcysteine_s_oxide
  }

  branch from 2_aminoprop_2_enoate side left {
    2_aminoprop_2_enoate
    <-> ec_4_4_1_4 [4.4.1.4] +ethylsulfenate
    ethiin
  }

  branch from 3_3_5_triiodo_l_thyronine side right {
    3_3_5_triiodo_l_thyronine
    <-> . +iodide +nadp +nadph
    l_thyroxine
  }

  branch from 3_3_5_triiodo_l_thyronine side left {
    3_3_5_triiodo_l_thyronine
    <-> . +nadph +iodide +3_5_diiodo_l_thyronine
    nadp
  }

  branch from h2o side right {
    h2o
    <-> ec_3_7_1_14 [3.7.1.14] +2e_2_hydroxypenta_2_4_dienoate +h +fumarate
    2_hydroxy_6_ketononatrienedioate
  }

  branch from h2o side left {
    h2o
    <-> ec_3_7_1_9 [3.7.1.9] +2e_2_hydroxypenta_2_4_dienoate +h +formate
    2e_4z_2_hydroxy_6_oxohexa_2_4_dienoate
  }

  branch from h side right {
    h
    <-> ec_1_11_2_3 [1.11.2.3] +9z_12z_octadecadienoate +9s_hydroperoxy_10e_12z_15z_octadecatrienoate +vernolate
    9_s_hotre
  }

  branch from h side left {
    h
    <-> ec_2_4_1_338 [2.4.1.338] +udp +validienamycin +udp_alpha_d_glucose
    1_1_bis_valienamine
  }

  branch from h2o2 side right {
    h2o2
    <-> . +2e_4z_7z_decatrienoyl_coa +4z_7z_decadienoyl_coa
    o2
  }

  branch from h2o2 side left {
    h2o2
    <-> . +4z_7z_10z_13z_hexadecatetraenoyl_coa +o2
    2e_4z_7z_10z_13z_hexadecapentaenoyl_coa
  }

  branch from iodide side right {
    iodide
    <-> . +nadp +3_monoiodo_l_thyronine +3_5_diiodo_l_thyronine
    nadph
  }

  branch from l_tyrosine side left {
    l_tyrosine
    <-> . +ala_tyr +h2o
    alanine
  }

  branch from l_tyrosine side right {
    l_tyrosine
    <-> . +l_alanine +h2o
    ala_tyr
  }
}
