# Ingested from Rhea. The spine follows the carbon skeleton from
# phloretate to β-D-glucose; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway phloretate-to-d-glucose "phloretate to β-D-glucose" {
  spacing 296

  spine at 0,0 {
    phloretate
    <-> . +nad -nadh -hplus
    trans_4_coumarate
    <-> . +udp_d_glucose -udp
    1_o_4_coumaroyl_d_glucose
    <-> ec_2_3_1_213 [2.3.1.213] +cyanidin_3_o_6_o_glucosyl_2_o_xylosylgalactoside -d_glucose -hplus
    cyanidin_3_o_6_o_6_o_4_coumaroyl_d_glucosyl_2_o
  }
}
