# Ingested from Rhea. The spine follows the carbon skeleton from
# PMF to ammonium; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway pmf-to-ammonium-null "PMF to ammonium" {
  spacing 284

  spine at 0,0 {
    pmf
    <-> . +n_acetylputrescine +o2 +h2o -pmf -nh4 -h2o2
    4_acetamidobutanal
    <-> . +nad +h2o -nadh -hplus
    4_acetamidobutanoate
    <-> ec_3_5_1_63 [3.5.1.63] +h2o -acetate
    gaba
    <-> . +o2 +h2o -h2o2 -nh3
    4_oxobutanoate
  }

  branch from pmf side left {
    pmf
    <-> . +asparagine
    l_asparagine
  }

  branch from pmf side right {
    pmf
    <-> ec_7_1_1_12 [7.1.1.12] +menaquinol_9 +fumarate +succinate
    menaquinone_9
  }

  branch from nh4 side left {
    nh4
    <-> ec_1_4_3_2 [1.4.3.2] +3_methyl_2_oxopentanoate +h2o2 +o2 +h2o
    l_isoleucine
  }

  branch from nh4 side right {
    nh4
    <-> ec_1_4_1_20 [1.4.1.20] +nadh +3_methyl_2_oxopentanoate +h +l_isoleucine +h2o
    nad
  }

  branch from h2o2 side left {
    h2o2
    <-> ec_1_1_3_9 [1.1.3.9] +alpha_d_galactose +o2 +h2o +h
    d_galactonate
  }

  branch from h2o2 side right {
    h2o2
    <-> ec_1_1_3_9 [1.1.3.9] +d_galactopyranose +o2
    galacto_hexodialdose
  }

  branch from pmf side left {
    pmf
    <-> . +menaquinol_8 +o2 +h2o
    mk_8
  }

  branch from pmf side right {
    pmf
    <-> ec_1_2_2_1 [1.2.2.1] +menaquinol_8 +co2 +mk_8 +formate
    h
  }

  branch from o2 side left {
    o2
    <-> . +2_methoxy_6_all_trans_octaprenyl_phenol
    6_methoxy_2_octaprenylhydroquinone
  }

  branch from o2 side right {
    o2
    <-> ec_1_13_11_39 [1.13.11.39] +2_hydroxy_6_oxo_2_aminophenyl_hexa_2_4_dienoate +h
    2_aminobiphenyl_2_3_diol
  }

  branch from h2o side left {
    h2o
    <-> . +4_oxo_4_5_dihydroimidazole_5_acetic_acid +h
    n_formimidoyl_l_aspartate
  }

  branch from h2o side right {
    h2o
    <-> . +n_formimidoyl_l_aspartate
    imidazolone_acetate
  }

  branch from nh4 side left {
    nh4
    <-> ec_3_5_4_26 [3.5.4.26] +2_5_diamino_6_hydroxy_4_5_phosphoribosylamino_py +h +h2o
    5_amino_6_5_phosphoribosylaminouracil
  }

  branch from nh4 side right {
    nh4
    <-> . +agropine +h2o +h
    mannopine
  }

  branch from h2o2 side left {
    h2o2
    <-> ec_1_10_3_6 [1.10.3.6] +rifamycin_b +h +o2
    rifamycin_o
  }

  branch from h2o2 side right {
    h2o2
    <-> ec_1_3_3_10 [1.3.3.10] +alpha_beta_didehydrotryptophan +h +o2
    l_tryptophan
  }
}
