# Ingested from Rhea. The spine follows the carbon skeleton from
# Quinolinone B to penigequinolone A; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway quinolinone-b-to-penigequinolone-a "Quinolinone B to penigequinolone A" {
  spacing 152

  spine at 0,0 {
    quinolinone_b
    <-> . +dmapp -ppi
    peniprequinolone
    <-> . +hydrogen_acceptor -hydrogen_donor
    yaequinolone_e
    <-> . +dmapp +h2o -ppi
    1_e_3_hydroxy_3_7_dimethylocta_1_6_dien_1_yl_qu
    <-> . +nadph +o2 +hplus -nadp -h2o
    1_e_5_3_3_dimethyloxiran_2_yl_3_hydroxy_3_methy
    <-> .
    yaequinolone_d
    <-> . +nadph +hplus -nadp -h2o
    penigequinolone_a
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_77 [4.2.3.77] +fpp
    germacrene_d
  }

  branch from hydrogen_donor side right {
    hydrogen_donor
    <-> ec_1_2_99_10 [1.2.99.10] +4_4_diapolycopen_4_al +hydrogen_acceptor +h2o +hplus
    4_4_diapolycopen_4_oate
  }

  branch from 1_e_5_3_3_dimethyloxiran_2_yl_3_hydroxy_3_methy side left {
    1_e_5_3_3_dimethyloxiran_2_yl_3_hydroxy_3_methy
    <-> .
    yaequinolone_c
  }

  branch from yaequinolone_d side right {
    yaequinolone_d
    <-> . +nadph +hplus +nadp +h2o
    penigequinolone_b
  }
}
