# Ingested from Rhea. The spine follows the carbon skeleton from
# (R)-3-(4-hydroxyphenyl)lactate to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway r-3-4-hydroxyphenyl-la-to-succinate "(R)-3-(4-hydroxyphenyl)la… to succinate" {
  spacing 152

  spine at 0,0 {
    r_3_4_hydroxyphenyl_lactate
    <-> ec_1_1_1_237 [1.1.1.237] +nadp -nadph -hplus
    3_4_hydroxyphenyl_pyruvate
    <-> ec_1_13_11_27 [1.13.11.27] +o2 -co2
    homogentisate
    <-> ec_1_13_11_5 [1.13.11.5] +o2 -hplus
    4_maleylacetoacetate
    <-> ec_5_2_1_2 [5.2.1.2]
    4_fumarylacetoacetate
    <-> ec_3_7_1_2 [3.7.1.2] +h2o -fumarate -hplus
    acetoacetate
    <-> ec_2_8_3_9 [2.8.3.9] +butyryl_coa -butyrate
    acetoacetyl_coa
    <-> ec_2_3_3_10 [2.3.3.10] +acetyl_coa +h2o -coa -hplus
    hmg_coa
    <-> ec_3_1_2_5 [3.1.2.5] +h2o -coa -hplus
    3_hydroxy_3_methylglutarate
    <-> ec_2_8_3_13 [2.8.3.13] +succinyl_coa -succinate
    hmg_coa
  }
}
