# Ingested from Rhea. The spine follows the carbon skeleton from
# (R)-dihydroformononetin to apiforol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway r-dihydroformononetin-to-apiforol "(R)-dihydroformononetin to apiforol" {
  spacing 272

  spine at 0,0 {
    r_dihydroformononetin
    <-> . +nadp -h -nadph
    formononetin
    <-> ec_2_1_1_212 [2.1.1.212] +s_adenosyl_l_homocysteine +h -s_adenosyl_l_methionine
    daidzein
    <-> . +h +h2o
    2s_naringenin
    <-> ec_1_1_1_234 [1.1.1.234] +h +nadph -apiforol
    nadp
  }
}
