# Ingested from Rhea. The spine follows the carbon skeleton from
# (R)-dichlorprop(1−) to 2,4-dichloro-cis,cis-muconate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway r-dichlorprop-to-2-4-dichloro-cis-cis-muco "(R)-dichlorprop to 2,4-dichloro-cis,cis-muco…" {
  spacing 240

  spine at 0,0 {
    r_dichlorprop
    <-> ec_1_14_11_44 [1.14.11.44] +akg +o2 -pyruvate -succinate -co2
    2_4_dichlorophenol
    <-> ec_1_14_13_20 [1.14.13.20] +nadph +o2 +hplus -nadp -h2o
    3_5_dichlorocatechol
    <-> . +o2 -hplus
    2_4_dichloro_cis_cis_muconate
  }

  branch from 2_4_dichlorophenol side left {
    2_4_dichlorophenol
    <-> . +2_4_dichlorophenoxy_acetate +akg +o2 +succinate +co2
    glyoxylate
  }

  branch from succinate side right {
    succinate
    <-> ec_2_8_3_22 [2.8.3.22] +l_citramalate +succinyl_coa
    3s_citramalyl_coa
  }

  branch from 2_4_dichloro_cis_cis_muconate side left {
    2_4_dichloro_cis_cis_muconate
    <-> ec_5_5_1_11 [5.5.1.11] +hplus
    2_4_dichloro_5_oxo_2_5_dihydro_2_furylacetate
  }
}
