# Ingested from Rhea. The spine follows the carbon skeleton from
# (R)-lipoamide to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway r-lipoamide-to-h2o "(R)-lipoamide to H2O" {
  spacing 244

  spine at 0,0 {
    r_lipoamide
    <-> ec_1_8_1_4 [1.8.1.4] +h +nadph -nadp
    r_dihydrolipoamide
    <-> ec_2_1_2_10 [2.1.2.10] +6r_5_10_methylene_5_6_7_8_tetrahydrofolate +nh4 -h -s8_aminomethyldihydrolipoamide
    6s_5_6_7_8_tetrahydrofolate
    <-> ec_3_4_17_11 [3.4.17.11] +h +l_glutamate -h2o
    thf_l_glutamate
  }

  branch from r_dihydrolipoamide side left {
    r_dihydrolipoamide
    <-> . +r_lipoamide +glutathione
    glutathione_disulfide
  }

  branch from r_dihydrolipoamide side right {
    r_dihydrolipoamide
    <-> ec_2_3_1_61 [2.3.1.61] +glutaryl_coa +h +s_8_glutaryldihydrolipoamide
    coa
  }

  branch from nadp side left {
    nadp
    <-> ec_1_3_1_94 [1.3.1.94] +h +di_trans_poly_cis_polyprenol_c80 +nadph
    c80_dolichol
  }

  branch from nadp side right {
    nadp
    <-> ec_1_1_1_274 [1.1.1.274] +ethyl_2r_methyl_3s_hydroxybutanoate +h +nadph
    ethyl_2_methylacetoacetate
  }

  branch from 6s_5_6_7_8_tetrahydrofolate side left {
    6s_5_6_7_8_tetrahydrofolate
    <-> . +tetrahydropteroyltri_l_glutamate +h +adp +phosphate +l_glutamate
    atp
  }

  branch from 6s_5_6_7_8_tetrahydrofolate side right {
    6s_5_6_7_8_tetrahydrofolate
    <-> . +nadh +6r_5_10_methylene_5_6_7_8_tetrahydrofolate +co2 +nh4 +nad
    glycine
  }

  branch from h side left {
    h
    <-> . +9z_12z_hexadeca_9_12_15_trienoyl_coa +malonyl_coa +5_pentadeca_8_11_14_trien_1_yl_resorcinol +coa
    co2
  }

  branch from h side right {
    h
    <-> ec_2_3_1_41 [2.3.1.41] +malonyl_coa +dodecanoyl_pantetheine_4_phosphorylserine_1 +co2 +coa
    o_s_3_oxotetradecanoylpantetheine_4_phosphoryl_s
  }

  branch from thf_l_glutamate side left {
    thf_l_glutamate
    <-> ec_2_1_2_1 [2.1.2.1] +5_10_methylenetetrahydropteroyl_di_l_glutamate +h +glycine +h2o
    l_serine
  }

  branch from thf_l_glutamate side right {
    thf_l_glutamate
    <-> ec_6_3_2_17 [6.3.2.17] +h +adp +phosphate +atp +l_glutamate
    tetrahydropteroyltri_l_glutamate
  }

  branch from h2o side left {
    h2o
    <-> ec_3_2_1_86 [3.2.1.86] +beta_d_glucose_6_phosphate +methanol
    methyl_beta_d_glucoside_6_phosphate
  }

  branch from h2o side right {
    h2o
    <-> . +ctp +hydroxyl +h
    5_hydroxy_ctp
  }
}
