# Ingested from Rhea. The spine follows the carbon skeleton from
# roxarsone (III)-glutathione complex to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway roxarsone-iii-glutathio-to-h2o-null "roxarsone (III)-glutathio… to H2O" {
  spacing 158

  spine at 0,0 {
    roxarsone_iii_glutathione_complex
    <-> . +h2o -roxarsone_iii
    glutathione
    <-> . +roxarsone_iii +hydrogen_donor +o2 -arsenite -hydrogen_acceptor -hplus
    4_hydroxy_3_nitrocyclohexa_2_5_dien_1_one
    <-> ec_3_6_3_16 [3.6.3.16] +h +adp +arsenite +phosphate -arsenite -h2o
    atp
  }

  branch from glutathione side left {
    glutathione
    <-> . +trans_urocanate
    s_2_carboxy_1_1h_imidazol_4_yl_ethyl_glutathione
  }
}
