# Ingested from Rhea. The spine follows the carbon skeleton from
# S-[(2E,6E)-farnesyl]-L-cysteine zwitterion to S-adenosyl-L-homocysteine zwitterion; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway s-2e-6e-farnesyl-l-cy-to-s-adenosyl-l-homocystei "S-[(2E,6E)-farnesyl]-L-cy… to S-adenosyl-L-homocysteine" {
  spacing 228

  spine at 0,0 {
    s_2e_6e_farnesyl_l_cysteine
    <-> ec_1_8_3_5 [1.8.3.5] +o2 +h2o -cysteine -h2o2
    2_trans_6_trans_farnesal
    <-> ec_1_2_1_94 [1.2.1.94] +nad +h2o -nadh -hplus
    2e_6e_farnesoate
    <-> ec_2_1_1_325 [2.1.1.325] +sam -sah
    methyl_farnesoate
    <-> ec_1_14_14_127 [1.14.14.127] +fmnh2 +o2 -fmn -h2o -hplus
    juvenile_hormone_iii
    <-> ec_3_1_1_59 [3.1.1.59] +h2o -methanol -hplus
    juvenile_hormone_iii_carboxylate
    <-> ec_2_1_1_325 [2.1.1.325] +sam -sah
    juvenile_hormone_iii
  }

  branch from 2_trans_6_trans_farnesal side left {
    2_trans_6_trans_farnesal
    <-> ec_1_1_1_354 [1.1.1.354] +nad +nadh +hplus
    2_trans_6_trans_farnesol
  }

  branch from cysteine side right {
    cysteine
    <-> ec_1_14_99_52 [1.14.99.52] +l_histidine +o2 +h2o
    s_5_histidyl_cysteine_sulfoxide_dizwitterion
  }

  branch from cysteine side left {
    cysteine
    <-> . +h2s +hplus
    2_ammonioprop_2_enoate
  }

  branch from 2e_6e_farnesoate side right {
    2e_6e_farnesoate
    <-> ec_1_2_1_5 [1.2.1.5] +nadh +h +11r_dihydroartemisinic_aldehyde +h2o
    nad
  }

  branch from sah side left {
    sah
    <-> ec_2_1_1_254 [2.1.1.254] +erythromycin_d +sam +hplus
    erythromycin_b
  }

  branch from sah side right {
    sah
    <-> ec_2_1_1_225 [2.1.1.225] +cytidine_5_monophosphate_1 +sam +hplus
    2_o_methylcytidine_5_monophosphate_1
  }

  branch from fmn side left {
    fmn
    <-> ec_1_14_14_79 [1.14.14.79] +4z_7z_10z_13z_16z_19z_docosahexaenoate +fmnh2 +o2 +h2o +hplus
    4z_7z_10z_13z_16z_19z_22_hydroxydocosahexaenoat
  }

  branch from fmn side right {
    fmn
    <-> ec_1_14_14_33 [1.14.14.33] +edta +fmnh2 +o2 +glyoxylate +h2o +hplus
    ethylenediaminediacetate
  }
}
