# Ingested from Rhea. The spine follows the carbon skeleton from
# S-adenosyl-L-homocysteine to L-methionine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway s-adenosyl-l-homocysteine-to-l-methionine "S-adenosyl-L-homocysteine to L-methionine" {
  spacing 322

  spine at 0,0 {
    s_adenosyl_l_homocysteine
    <-> ec_2_1_1_201 [2.1.1.201] +2_methoxy_5_methyl_6_all_trans_hexaprenyl_1_4_be +h -2_methoxy_6_all_trans_hexaprenyl_1_4_benzoquinon
    s_adenosyl_l_methionine
    <-> ec_2_1_1_333 [2.1.1.333] +12_ethyl_8_isobutylbacteriochlorophyllide_d -s_adenosyl_l_homocysteine -h
    12_ethyl_8_isobutylbacteriochlorophyllide_c
    <-> . +s_adenosyl_l_methionine +h2o -5_deoxyadenosine -h -l_methionine
    12_ethyl_71_hydroxy_8_isobutylbacteriochlorophyl
  }

  branch from s_adenosyl_l_methionine side left {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +methyl_gibberellin_a20 +h
    gibberellin_a20
  }

  branch from s_adenosyl_l_methionine side right {
    s_adenosyl_l_methionine
    <-> . +s_adenosyl_l_homocysteine +h +2_3s_3_carboxylato_3_methylammonio_propyl_l_hist
    2_3s_3_amino_3_carboxypropyl_l_histidine_zwitter
  }

  branch from 12_ethyl_8_isobutylbacteriochlorophyllide_c side left {
    12_ethyl_8_isobutylbacteriochlorophyllide_c
    <-> . +12_ethyl_8_isobutylbacteriochlorophyll_c +diphosphate +h
    2e_6e_farnesyl_diphosphate
  }

  branch from s_adenosyl_l_homocysteine side right {
    s_adenosyl_l_homocysteine
    <-> . +diphthine +s_adenosyl_l_methionine
    2_3s_3_carboxylato_3_dimethylammonio_propyl_l_hi
  }

  branch from s_adenosyl_l_homocysteine side left {
    s_adenosyl_l_homocysteine
    <-> . +h +2_3s_3_carboxylato_3_dimethylammonio_propyl_l_hi +s_adenosyl_l_methionine
    2_3s_3_carboxylato_3_methylammonio_propyl_l_hist
  }

  branch from h side right {
    h
    <-> . +cdp_4_dehydro_3_6_dideoxy_d_glucose_epimer
    cdp_4_dehydro_3_6_dideoxy_d_glucose
  }

  branch from h side left {
    h
    <-> . +cdp_4_dehydro_3_6_dideoxy_d_glucose_epimer +nadph +cdp_ascarylose
    nadp
  }

  branch from 5_deoxyadenosine side right {
    5_deoxyadenosine
    <-> . +l_methionine +divinylprotochlorophyllide +s_adenosyl_l_methionine
    13_1_oxo_mg_protoporphyrin_ix_13_monomethyl_este
  }

  branch from 5_deoxyadenosine side left {
    5_deoxyadenosine
    <-> . +31r_8_12_diethyl_71_hydroxybacteriochlorophylli +h +l_methionine +s_adenosyl_l_methionine +h2o
    31r_8_12_diethylbacteriochlorophyllide_c
  }

  branch from l_methionine side right {
    l_methionine
    <-> ec_3_3_2_6 [3.3.2.6] +l_methionine_p_nitroanilide +h2o
    4_nitroaniline
  }

  branch from l_methionine side left {
    l_methionine
    <-> ec_3_4_11_18 [3.4.11.18] +gly_met_met +h2o
    met_gly_met_met
  }
}
