# Ingested from Rhea. The spine follows the carbon skeleton from
# S-adenosyl-L-homocysteine to 2-Octaprenyl-3-methyl-5-hydroxy-6-methoxy-1,4-benzoquinol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway s-adenosyl-l-homocysteine-to-2-octaprenyl-3-meth "S-adenosyl-L-homocysteine to 2-Octaprenyl-3-methyl-5-h…" {
  spacing 234

  spine at 0,0 {
    s_adenosyl_l_homocysteine
    <-> ec_2_1_1_64 [2.1.1.64] +ubiquinol_8 +h -2_octaprenyl_3_methyl_5_hydroxy_6_methoxy_1_4_be
    s_adenosyl_l_methionine
    <-> . +nadh +2_octaprenyl_3_methyl_5_hydroxy_6_methoxy_1_4_be +h +adp +phosphate -atp -nad -h2o
    2_octaprenyl_3_methyl_6_methoxy_1_4_benzoquinol
    <-> . +o2
    2_octaprenyl_3_methyl_5_hydroxy_6_methoxy_1_4_be
  }

  branch from ubiquinol_8 side left {
    ubiquinol_8
    <-> . +nadh_chebi_57945 +hplus +nad_chebi_57540
    ubiquinone_8
  }
}
