# Ingested from Rhea. The spine follows the carbon skeleton from
# sedoheptulose to 2-oxoglutarate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway sedoheptulose-to-2-oxoglutarate "sedoheptulose to 2-oxoglutarate" {
  spacing 280

  spine at 0,0 {
    sedoheptulose
    <-> ec_2_7_1_14 [2.7.1.14] +atp -adp -hplus
    s7p
    <-> ec_5_3_1_28 [5.3.1.28] -d_glycero_d_manno_heptose_7_phosphate
    d_glycero_d_manno_heptose_7_phosphate
    <-> ec_2_7_1_168 [2.7.1.168] +atp -adp -hplus
    d_glycero_d_manno_heptose_1_7_bisphosphate
    <-> ec_3_1_3_83 [3.1.3.83] +h2o -pi
    d_glycero_d_manno_heptose_1_phosphate
    <-> ec_2_7_7_71 [2.7.7.71] +gtp +hplus -ppi
    gdp_d_glycero_d_manno_heptose
    <-> . +akg -s_2_hydroxyglutarate
    gdp_d_glycero_4_keto_d_lyxo_heptose
    <-> . +s_2_hydroxyglutarate +o2 -h2o2
    akg
  }

  branch from s7p side left {
    s7p
    <-> . +atp +adp +hplus
    sedoheptulose_1_7_bisphosphate
  }

  branch from ppi side right {
    ppi
    <-> ec_4_2_3_56 [4.2.3.56] +fpp
    himachalene
  }

  branch from akg side left {
    akg
    <-> ec_1_1_1_42 [1.1.1.42] +nadp +co2 +nadph
    d_threo_isocitrate
  }
}
