# Ingested from Rhea. The spine follows the carbon skeleton from
# staphyloferrin A(5−) to O-citryl-ethanolamine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway staphyloferrin-a-to-o-citryl-ethanolamine-null "staphyloferrin A to O-citryl-ethanolamine" {
  spacing 158

  spine at 0,0 {
    staphyloferrin_a
    <-> . +diphosphate +h +amp -atp -l_ornithine
    citrate
    <-> . +atp +l_serine -o_citryl_l_serine -amp
    diphosphate
    <-> . +o_citryl_l_serine +h -o_citryl_ethanolamine
    co2
  }

  branch from citrate side left {
    citrate
    <-> ec_4_2_1_3 [4.2.1.3]
    isocitrate
  }
}
