# Ingested from Rhea. The spine follows the carbon skeleton from
# thymidine 3'-monophosphate(2−) to succinate(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway thymidine-3-monophosphate-to-succinate "thymidine 3'-monophosphate to succinate" {
  spacing 158

  spine at 0,0 {
    thymidine_3_monophosphate
    <-> . +h2o -pi
    thymidine
    <-> ec_2_7_1_114 [2.7.1.114] +amp -adenosine
    dtmp
    <-> . +h2o -thymine
    2_deoxy_d_ribofuranose_5_phosphate
    <-> ec_1_14_11_6 [1.14.11.6] +thymine +akg +o2 -succinate -co2
    5_hydroxymethyluracil
  }

  branch from thymine side left {
    thymine
    <-> ec_1_3_1_1 [1.3.1.1] +nad +nadh +hplus
    5_6_dihydrothymine
  }
}
