# Ingested from Rhea. The spine follows the carbon skeleton from
# trans-isoeugenol to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway trans-isoeugenol-to-h2o "trans-isoeugenol to H2O" {
  spacing 318

  spine at 0,0 {
    trans_isoeugenol
    <-> ec_2_1_1_146 [2.1.1.146] +sam -sah -hplus
    trans_isomethyleugenol
    <-> ec_2_1_1_146 [2.1.1.146] +s_adenosyl_l_homocysteine +h -isoeugenol
    s_s_adenosyl_l_methionine
    <-> ec_2_1_1_137 [2.1.1.137] +arsenite +h -methylarsonate
    s_adenosyl_l_homocysteine
    <-> ec_2_1_1_137 [2.1.1.137] +h +methylarsonate -arsenite
    s_adenosyl_l_methionine
    <-> . +methylselenol -h -dimethylselenide
    s_adenosyl_l_homocysteine
    <-> ec_4_4_1_11 [4.4.1.11] +2_oxobutanoate +h +dimethylselenide +nh4 -h2o
    se_methyl_l_selenomethionine
    <-> ec_2_1_1_12 [2.1.1.12] +s_adenosyl_l_homocysteine -l_selenomethionine
    s_adenosyl_l_methionine
    <-> . +l_selenomethionine +h +o2 +nadph -selenomethionine_se_oxide -h2o
    nadp
  }




















}
