# Ingested from Rhea. The spine follows the carbon skeleton from
# triacetate lactone to diphosphate(3−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway triacetate-lactone-to-diphosphate "triacetate lactone to diphosphate" {
  spacing 260

  spine at 0,0 {
    triacetate_lactone
    <-> ec_3_1_1_38 [3.1.1.38] +h2o -hplus
    triacetate
    <-> ec_2_3_1_319 [2.3.1.319] +acetyl_coa -acetoacetate
    acetoacetyl_coa
    <-> ec_6_3_2_50 [6.3.2.50] +isoleucine +atp -amp -ppi -coa -hplus
    tenuazonic_acid
  }
}
