# Ingested from Rhea. The spine follows the carbon skeleton from
# tricaprin to 3-oxolauroyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway tricaprin-to-3-oxolauroyl-coa "tricaprin to 3-oxolauroyl-CoA" {
  spacing 194

  spine at 0,0 {
    tricaprin
    <-> . +h2o -decanoate -hplus
    r_1_2_didecanoylglycerol
    <-> . +decanoate +atp +coa -amp -ppi
    decanoyl_coa
    <-> . +acetyl_coa -coa
    3_oxolauroyl_coa
  }

  branch from decanoate side left {
    decanoate
    <-> . +nad +h2o +nadh +hplus
    decanal
  }

  branch from decanoate side right {
    decanoate
    <-> . +n6_capryl_l_lysine +h2o
    l_lysinium
  }

  branch from decanoyl_coa side left {
    decanoyl_coa
    <-> . +1_o_palmityl_2_acetyl_sn_glycerol +coa
    1_hexadecyl_2_acetyl_3_decanoyl_sn_glycerol
  }

  branch from decanoyl_coa side right {
    decanoyl_coa
    <-> . +malonyl-acp +hplus +co2 +coa
    o_s_3_oxododecanoylpantetheine_4_phosphoryl_seri
  }

  branch from ppi side left {
    ppi
    <-> ec_2_5_1_153 [2.5.1.153] +tuberculosinyl_diphosphate +h2o
    13s_edaxadiene
  }

  branch from ppi side right {
    ppi
    <-> ec_4_2_3_87 [4.2.3.87] +fpp
    guaiene
  }

  branch from 3_oxolauroyl_coa side left {
    3_oxolauroyl_coa
    <-> . +nad +nadh +hplus
    r_3_hydroxylauroyl_coa
  }
}
