# Ingested from Rhea. The spine follows the carbon skeleton from
# tricaprin to 3-oxolauroyl-CoA(4−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway tricaprin-to-3-oxolauroyl-coa "tricaprin to 3-oxolauroyl-CoA" {
  spacing 218

  spine at 0,0 {
    tricaprin
    <-> . +h2o -decanoate -hplus
    r_1_2_didecanoylglycerol
    <-> . +decanoate +atp +coa -amp -ppi
    decanoyl_coa
    <-> . +acetyl_coa -coa
    3_oxolauroyl_coa
  }

  branch from decanoate side left {
    decanoate
    <-> . +nad +h2o +nadh +hplus
    decanal
  }

  branch from decanoate side right {
    decanoate
    <-> . +n6_capryl_l_lysine +h2o
    l_lysinium
  }

  branch from decanoyl_coa side left {
    decanoyl_coa
    <-> . +carnitine +coa
    o_decanoyl_l_carnitine
  }

  branch from decanoyl_coa side right {
    decanoyl_coa
    <-> . +fad +hplus +fadh2
    trans_dec_2_enoyl_coa
  }

  branch from ppi side left {
    ppi
    <-> . +c_terminal_gly_gly_1 +atp +hplus
    c_terminal_gly_gly_amp_1_group
  }

  branch from ppi side right {
    ppi
    <-> ec_2_7_7_100 [2.7.7.100] +atp +hplus +c_terminal_gly_gly_amp_1_group
    c_terminal_gly_gly_1
  }

  branch from 3_oxolauroyl_coa side left {
    3_oxolauroyl_coa
    <-> . +nad +nadh +hplus
    r_3_hydroxylauroyl_coa
  }

  branch from decanoyl_coa side right {
    decanoyl_coa
    <-> . +l_serine +coa
    o_decanoyl_l_serine
  }

  branch from decanoyl_coa side left {
    decanoyl_coa
    <-> . +ketosphinganine +coa +hplus
    n_decanoyl_3_ketodihydrosphingosine
  }

  branch from ppi side right {
    ppi
    <-> . +fpp
    cadinene
  }

  branch from ppi side left {
    ppi
    <-> . +neryl_diphosphate +h2o
    1_8_cineole
  }
}
