# Ingested from Rhea. The spine follows the carbon skeleton from
# trilinoleoyl 2-monolysocardiolipin(2−) to 1-acyl-2-palmitoleoyl-sn-glycero-3-phosphocholine; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway trilinoleoyl-to-1-acyl-2-palmitoleoyl-sn "trilinoleoyl… to 1-acyl-2-palmitoleoyl-sn-…" {
  spacing 152

  spine at 0,0 {
    trilinoleoyl_2_monolysocardiolipin
    <-> . +1_2_dioleoyl_sn_glycero_3_phosphocholine -1_o_oleoyl_sn_glycero_3_phosphocholine
    1_1_2_trilinoleoyl_2_oleoyl_cardiolipin
    <-> . +1_o_oleoyl_sn_glycero_3_phosphocholine +h2o -oleate -hplus
    choline_alfoscerate
    <-> . +acyl_coa -coa
    1_o_acyl_sn_glycero_3_phosphocholine
    <-> . +palmitoleoyl_coa -coa
    1_acyl_2_palmitoleoyl_sn_glycero_3_phosphocholin
  }
}
