# Ingested from Rhea. The spine follows the carbon skeleton from
# trithionate(2−) to menadiol; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway trithionate-to-menadiol "trithionate to menadiol" {
  spacing 340

  spine at 0,0 {
    trithionate
    <-> ec_3_12_1_1 [3.12.1.1] +h2o -sulfate -hplus
    trioxidosulfanidosulfate
    <-> ec_1_8_5_2 [1.8.5.2] +6_decylubiquinone -tetrathionate
    6_decylubiquinol
    <-> ec_1_3_5_2 [1.3.5.2] +orotate -6_decylubiquinone
    s_dihydroorotate
    <-> ec_1_3_3_1 [1.3.3.1] +ubiquinone_6 -ubiquinol_6
    orotate
    <-> ec_1_3_5_2 [1.3.5.2] +menadiol -s_dihydroorotate
    menadione
    <-> . +h2o -o2
    menadiol
    <-> . +o2 -superoxide -hplus
    menadione
    <-> . +nadph +hplus -nadp
    menadiol
  }

  branch from trioxidosulfanidosulfate side left {
    trioxidosulfanidosulfate
    <-> ec_2_8_5_2 [2.8.5.2] +3_disulfanyl_l_alanine +iron +fe2 +hplus
    s_2_sulfodisulfanyl_l_cysteine_1
  }

  branch from trioxidosulfanidosulfate side right {
    trioxidosulfanidosulfate
    <-> ec_2_8_5_1 [2.8.5.1] +pser +pi
    s_sulfo_l_cysteinate
  }

  branch from sulfate side left {
    sulfate
    <-> . +z_n_sulfonatooxy_prop_2_enimidothioate +sulfur_atom
    allyl_cyanide
  }

  branch from sulfate side right {
    sulfate
    <-> . +z_3_hydroxypropyl_n_sulfonatooxy_methanimidothi
    3_hydroxypropyl_isothiocyanate
  }

  branch from 6_decylubiquinol side left {
    6_decylubiquinol
    <-> ec_1_6_5_2 [1.6.5.2] +h +6_decylubiquinone +nadph
    nadp
  }

  branch from 6_decylubiquinol side right {
    6_decylubiquinol
    <-> ec_1_6_5_2 [1.6.5.2] +nadh +h +6_decylubiquinone
    nad
  }

  branch from tetrathionate side left {
    tetrathionate
    <-> . +thiosulfate +2_demethylmenaquinone_8
    2_demethylmenaquinol_8
  }

  branch from tetrathionate side right {
    tetrathionate
    <-> . +thiosulfate +ubiquinone_8
    ubiquinol_8
  }

  branch from s_dihydroorotate side left {
    s_dihydroorotate
    <-> ec_1_3_5_2 [1.3.5.2] +orotate +hydroquinone
    1_4_benzoquinone
  }

  branch from s_dihydroorotate side right {
    s_dihydroorotate
    <-> ec_1_3_5_2 [1.3.5.2] +ubiquinol_2 +orotate
    ubiquinone_2
  }

  branch from 6_decylubiquinone side left {
    6_decylubiquinone
    <-> . +6_decylubiquinol +h2o
    h2o2
  }

  branch from orotate side right {
    orotate
    <-> ec_1_3_5_2 [1.3.5.2] +ubiquinol_9 +s_dihydroorotate
    ubiquinone_9
  }

  branch from orotate side left {
    orotate
    <-> ec_1_3_5_2 [1.3.5.2] +ubiquinol_10 +s_dihydroorotate
    ubiquinone_10
  }

  branch from ubiquinol_6 side right {
    ubiquinol_6
    <-> ec_2_1_1_64 [2.1.1.64] +3_demethylubiquinol_6 +sam +hplus
    sah
  }

  branch from ubiquinol_6 side left {
    ubiquinol_6
    <-> . +spermidine +ubiquinone_6 +h2o +4_aminobutanal
    propane_1_3_diamine
  }

  branch from menadione side right {
    menadione
    <-> ec_1_10_5_1 [1.10.5.1] +n_methyldihydronicotinamide +h +menadiol
    1_methylnicotinamide
  }

  branch from menadione side left {
    menadione
    <-> ec_1_10_5_1 [1.10.5.1] +beta_nicotinamide_d_riboside +menadiol +1_d_ribofuranosyl_1_4_dihydronicotinamide
    h
  }

  branch from menadiol side right {
    menadiol
    <-> . +2_trans_6_trans_10_trans_geranylgeranyl_diphosph +ppi
    menaquinol_4
  }

  branch from menadiol side left {
    menadiol
    <-> ec_1_3_5_3 [1.3.5.3] +protoporphyrin_ix +menadione
    protoporphyrinogen_ix
  }

  branch from o2 side right {
    o2
    <-> . +nadh +h +7alpha_hydroxycholest_4_en_3_one +nad +h2o
    7alpha_12alpha_dihydroxycholest_4_en_3_one
  }

  branch from o2 side left {
    o2
    <-> ec_1_14_15_6 [1.14.15.6] +20_hydroxycholesterol +nadp +h2o +h +nadph
    cholesterol
  }

  branch from superoxide side right {
    superoxide
    <-> . +chromium +nadph +o2 +nadp +hplus
    chromium
  }

  branch from superoxide side left {
    superoxide
    <-> . +nadh +o2 +chromium +nad +hplus
    chromium
  }
}
