# Ingested from Rhea. The spine follows the carbon skeleton from
# ubiquinol-9 to CoA; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway ubiquinol-9-to-coa "ubiquinol-9 to CoA" {
  spacing 152

  spine at 0,0 {
    ubiquinol_9
    <-> . +7_7_9_9_tetra_cis_lycopene -7_9_9_tri_cis_neurosporene
    ubiquinone_9
    <-> . +ubiquinol_10 +7_9_9_tri_cis_neurosporene -9_9_di_cis_carotene
    ubiquinone_10
    <-> . +dodecanoyl_coa -ubiquinol_10
    2e_dodecenoyl_coa
    <-> . +r_carnitine -coa
    o_5z_dodecenoyl_carnitine
  }
}
