# Ingested from Rhea. The spine follows the carbon skeleton from
# UDP to UDP-2-acetamido-2,6-dideoxy-α-D-xylo-hex-4-ulose(2−); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway udp-to-udp-2-acetamido-2-6-dideo "UDP to UDP-2-acetamido-2,6-dideo…" {
  spacing 340

  spine at 0,0 {
    udp
    <-> ec_2_4_1_227 [2.4.1.227] +und_pp_beta_d_glcnac_1_4_murnac_l_ala_gamma_d_gl +h -und_pp_murnac_l_ala_gamma_d_glu_l_lys_d_ala
    udp_n_acetyl_alpha_d_glucosamine
    <-> ec_4_2_1_135 [4.2.1.135] +h -h2o
    udp_2_acetamido_4_dehydro_2_6_dideoxy_beta_d_glu
    <-> . -udp_2_acetamido_2_6_dideoxy_d_xylo_hex_4_ulose
    h
  }

  branch from udp_n_acetyl_alpha_d_glucosamine side left {
    udp_n_acetyl_alpha_d_glucosamine
    <-> ec_2_4_1_145 [2.4.1.145] +udp +h +n4_d_glcnac_1_2_d_glcnac_1_4_d_man_1_3_d_glcnac
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6
  }

  branch from udp_n_acetyl_alpha_d_glucosamine side right {
    udp_n_acetyl_alpha_d_glucosamine
    <-> . +utp +n_acetyl_beta_d_glucosamine_6_phosphate +h
    diphosphate
  }

  branch from udp_2_acetamido_4_dehydro_2_6_dideoxy_beta_d_glu side left {
    udp_2_acetamido_4_dehydro_2_6_dideoxy_beta_d_glu
    <-> ec_2_6_1_34 [2.6.1.34] +udp_2_acetamido_4_amino_2_4_6_trideoxyglucose +2_oxoglutarate +h
    l_glutamate
  }

  branch from h2o side right {
    h2o
    <-> ec_3_2_1_149 [3.2.1.149] +2_phenylethanol +a_6_o_beta_d_xylopyranosyl_beta_d_glucopyranose
    2_phenylethyl_primeveroside
  }

  branch from h2o side left {
    h2o
    <-> ec_3_2_1_149 [3.2.1.149] +linalyl_beta_vicianoside +vicianose
    linalool
  }

  branch from h side right {
    h
    <-> . +malonyl_coa +anthraniloyl_coa +2_methyl_4_quinolinol +coa
    co2
  }

  branch from h side left {
    h
    <-> ec_3_1_1_4 [3.1.1.4] +9z_octadecenoate +1_oleoyl_sn_glycero_3_phosphoethanolamine +h2o
    1_2_dioleoyl_sn_glycero_3_phosphoethanolamine
  }

  branch from udp_2_acetamido_2_6_dideoxy_d_xylo_hex_4_ulose side right {
    udp_2_acetamido_2_6_dideoxy_d_xylo_hex_4_ulose
    <-> ec_1_1_1_426 [1.1.1.426] +nad +nadh +hplus
    udp_n_acetyl_d_quinovosamine
  }

  branch from udp_2_acetamido_2_6_dideoxy_d_xylo_hex_4_ulose side left {
    udp_2_acetamido_2_6_dideoxy_d_xylo_hex_4_ulose
    <-> ec_2_6_1_92 [2.6.1.92] +udp_2_acetamido_4_amino_2_4_6_trideoxy_d_galacto +akg
    glutamate
  }
}
