# Ingested from Rhea. The spine follows the carbon skeleton from
# UDP to orientin; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway udp-to-orientin "UDP to orientin" {
  spacing 292

  spine at 0,0 {
    udp
    <-> . +h +kaempferol_3_o_beta_d_glucosyl_1_2_beta_d_glucos -kaempferol_3_o_d_glucosyl_1_2_d_glucoside
    udp_beta_l_rhamnose
    <-> ec_2_4_1_239 [2.4.1.239] +udp +kaempferol_3_o_d_glucosyl_1_2_d_glucoside -kaempferol_3_o_beta_d_glucoside
    udp_alpha_d_glucose
    <-> . +luteolin -orientin
    udp
  }









}
