# Ingested from Rhea. The spine follows the carbon skeleton from
# UDP to oleanolic acid 3-O-beta-D-glucosiduronic acid; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway udp-to-oleanolic-acid-null "UDP to oleanolic acid…" {
  spacing 164

  spine at 0,0 {
    udp
    <-> . +oleanolate_3_beta_d_glucuronoside_3_1_galactosid +h -oleanolate_3_beta_d_glucuronoside_3_1_galactosid
    udp_alpha_d_glucose
    <-> . +udp +oleanolate_3_beta_d_glucuronoside_3_1_galactosid +h -chikusetsusaponin_iva
    udp_alpha_d_galactose
    <-> . +udp +chikusetsusaponin_iva +h -oleanolic_acid_3_o_beta_d_glucosiduronic_acid
    udp_alpha_d_glucose
  }

  branch from udp_alpha_d_galactose side left {
    udp_alpha_d_galactose
    <-> ec_2_4_1_38 [2.4.1.38] +udp +beta_d_gal_1_4_alpha_d_glcnac_1_2_alpha_d_d_hep +h
    alpha_d_glcnac_1_2_alpha_d_d_hep_1_3_3_alpha_d_g
  }

  branch from udp_alpha_d_galactose side right {
    udp_alpha_d_galactose
    <-> ec_2_4_1_38 [2.4.1.38] +udp +beta_d_gal_1_4_alpha_d_glcnac_1_2_beta_d_gal_1_4 +h
    alpha_d_glcnac_1_2_beta_d_gal_1_4_alpha_l_fuc_1
  }
}
