# Ingested from Rhea. The spine follows the carbon skeleton from
# UDP to D-glucopyranose; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway udp-to-d-glucopyranose "UDP to D-glucopyranose" {
  spacing 340

  spine at 0,0 {
    udp
    <-> . +3beta_12beta_3_12_dihydroxydammar_24_en_20_yl_b +h -20s_protopanaxadiol
    udp_alpha_d_glucose
    <-> . +glucose +20s_protopanaxadiol -h2o
    20s_ginsenoside_rh2
    <-> ec_2_4_1_365 [2.4.1.365] +udp_d_glucose -udp -hplus
    20s_ginsenoside_rg3
    <-> . +h2o -glucose
    20s_ginsenoside_rh2
  }

  branch from h2o side left {
    h2o
    <-> . +l_aspartate +h +glycine
    glycyl_aspartate
  }

  branch from h2o side right {
    h2o
    <-> . +h +glycine +l_glutamate
    glycyl_glutamate
  }
}
