# Ingested from Rhea. The spine follows the carbon skeleton from
# UDP to oleanolic acid 3-O-beta-D-glucosiduronic acid; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway udp-to-oleanolic-acid "UDP to oleanolic acid…" {
  spacing 152

  spine at 0,0 {
    udp
    <-> . +oleanolate_3_beta_d_glucuronoside_3_1_galactosid +h -oleanolate_3_beta_d_glucuronoside_3_1_galactosid_mnxm1372529
    udp_alpha_d_glucose
    <-> . +udp +oleanolate_3_beta_d_glucuronoside_3_1_galactosid_mnxm1372529 +h -chikusetsusaponin_iva
    udp_alpha_d_galactose
    <-> . +udp +chikusetsusaponin_iva +h -oleanolic_acid_3_o_beta_d_glucosiduronic_acid
    udp_alpha_d_glucose
  }
}
