# Ingested from Rhea. The spine follows the carbon skeleton from
# UDP-4-amino-4-deoxy-β-L-arabinopyranose(1−) to N4-{β-D-GlcNAc-(1→2)-α-D-Man-(1→3)-[β-D-GlcNAc-(1→2)-α-D-Man-(1→6)]-[β-D-Xyl-(1→2)]-β-D-Man-(1→4)-β-D-GlcNAcl-(1→4)-β-D-GlcNAc}-Asn residue; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway udp-4-amino-4-deoxy-l-a-to-n4-d-glcnac-1-2-d "UDP-4-amino-4-deoxy-β-L-a… to N4-{β-D-GlcNAc-(1→2)-α-D-…" {
  spacing 292

  spine at 0,0 {
    udp_4_amino_4_deoxy_l_arabinopyranose
    <-> ec_2_6_1_87 [2.6.1.87] +akg -glutamate
    udp_l_threo_pentopyranos_4_ulose
    <-> . +nadh +hplus -nad
    udp_d_xylose
    <-> ec_2_4_2_38 [2.4.2.38] +n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6 -udp -hplus
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6
  }

  branch from udp_d_xylose side left {
    udp_d_xylose
    <-> ec_2_4_2_56 [2.4.2.56] +kaempferol_oxoanion +udp +hplus
    kaempferol_3_o_d_xyloside
  }

  branch from udp_d_xylose side right {
    udp_d_xylose
    <-> ec_2_4_2_50 [2.4.2.50] +cyanidin_3_o_d_galactoside +udp +hplus
    cyanidin_3_o_d_xylosyl_1_2_d_galactoside
  }

  branch from udp_d_xylose side left {
    udp_d_xylose
    <-> ec_2_4_2_51 [2.4.2.51] +anthocyanidin_3_o_d_glucoside +udp +hplus
    anthocyanidin_3_o_d_sambubioside_betaine
  }

  branch from udp_d_xylose side right {
    udp_d_xylose
    <-> ec_2_4_2_26 [2.4.2.26] +l_serine +udp +hplus
    o3_d_xylosyl_l_serine
  }

  branch from n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6 side left {
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6
    <-> ec_2_4_1_214 [2.4.1.214] +gdp_l_fucose +gdp +hplus
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6
  }

  branch from n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6 side right {
    n4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2_d_man_1_6
    <-> . +udp_d_galactose +udp +hplus
    n4_d_gal_1_4_d_glcnac_1_2_d_man_1_3_d_glcnac_1_2
  }
}
