# Ingested from Rhea. The spine follows the carbon skeleton from
# undecanoate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway undecanoate-to-h2o "undecanoate to H2O" {
  spacing 340

  spine at 0,0 {
    undecanoate
    <-> . +atp +coa -amp -ppi
    undecanoyl_coa
    <-> . +fad +hplus -fadh2
    trans_2_undecenoyl_coa
    <-> ec_5_3_3_8 [5.3.3.8]
    3e_undec_3_enoyl_coa
    <-> ec_1_3_1_124 [1.3.1.124] +nadp -h -nadph
    2e_4z_undeca_2_4_dienoyl_coa
    <-> ec_1_3_3_6 [1.3.3.6] +h2o2 -o2
    4_cis_undecenoyl_coa
    <-> ec_2_3_1_16 [2.3.1.16] +acetyl_coa -coa
    6_cis_3_oxo_tridecenoyl_coa
    <-> . +nadh +h -nad
    3r_hydroxy_6_cis_tridecenoyl_coa
    <-> ec_4_2_1_119 [4.2.1.119] -h2o
    2_trans_6_cis_tridecadienoyl_coa
    <-> ec_1_3_3_6 [1.3.3.6] +h2o2 -o2
    6_cis_tridecenoyl_coa
    <-> . +nadh +acetyl_coa +h +h2o2 -coa -o2 -nad -h2o
    10z_heptadecenoyl_coa
    <-> . +diphosphate +h +amp -coa -10z_heptadecenoic_acid
    atp
    <-> . +h +adp +10z_heptadecenoic_acid +phosphate -atp -h2o
    10z_heptadecenoic_acid
  }

  branch from undecanoyl_coa side left {
    undecanoyl_coa
    <-> . +nadh +acetyl_coa +fadh2 +h +fad +coa +nad +h2o
    tridecanoyl_coa
  }

  branch from undecanoyl_coa side right {
    undecanoyl_coa
    <-> . +acetyl_coa +coa
    3_oxotridecanoyl_coenzyme_a
  }

  branch from ppi side left {
    ppi
    <-> ec_4_2_3_94 [4.2.3.94] +fpp
    curcumene
  }

  branch from ppi side right {
    ppi
    <-> ec_3_1_7_10 [3.1.7.10] +geranylgeranyl_diphosphate +h2o
    13e_labda_7_13_dien_15_ol
  }

  branch from trans_2_undecenoyl_coa side left {
    trans_2_undecenoyl_coa
    <-> . +h +h2o
    3_hydroxyundecanoyl_coa
  }

  branch from 3e_undec_3_enoyl_coa side right {
    3e_undec_3_enoyl_coa
    <-> ec_1_3_1_124 [1.3.1.124] +h +nadph +nadp
    2e_4e_undeca_2_4_dienoyl_coa
  }

  branch from h side left {
    h
    <-> . +rac_5_6_epoxy_retinoyl_beta_d_glucuronide +udp +rac_5_6_epoxy_retinoate
    udp_alpha_d_glucuronate
  }

  branch from h side right {
    h
    <-> . +udp +4_oxo_9_cis_retinoyl_beta_glucuronide +udp_alpha_d_glucuronate
    4_oxo_9_cis_retinoate
  }

  branch from nadph side left {
    nadph
    <-> . +8z_11z_14z_17z_3_oxoicosatetraenoyl_coa +h +nadp
    3s_8z_11z_14z_17z_3_hydroxyicosatetraenoyl_coa
  }

  branch from nadph side right {
    nadph
    <-> . +h +7z_10z_13z_16z_19z_3_oxodocosapentaenoyl_coa +nadp
    3_s_hydroxy_docosa_7_10_13_16_19_all_cis_pentaen
  }

  branch from o2 side left {
    o2
    <-> . +coa_18_cooh_16e_dinor_lte5 +h2o2
    coa_omega_cooh_dinor_lte4
  }

  branch from o2 side right {
    o2
    <-> . +benzo_a_pyrene_2_3_oxide +nadp +h2o +h +nadph
    benzo_a_pyrene
  }

  branch from coa side left {
    coa
    <-> . +acetyl_coa +l_asparagine
    n_acetyl_l_asparagine
  }

  branch from coa side right {
    coa
    <-> . +3_methylbut_2_enoyl_coa +glycine
    3_methylcrotonyl_glycine
  }

  branch from nad side left {
    nad
    <-> ec_1_6_1_1 [1.6.1.1] +nadh +nadp +nadph
    pmf
  }

  branch from nad side right {
    nad
    <-> ec_1_14_18_2 [1.14.18.2] +nadh +n_glycoloylneuraminic_acid +h +o2 +h2o
    n_acetyl_neuraminic_acid
  }

  branch from h2o side left {
    h2o
    <-> . +2e_9z_12z_15z_18z_21z_tetracosahexaenoyl_coa
    3_s_hydroxy_tetracosa_9_12_15_18_21_all_cis_pent
  }

  branch from h2o side right {
    h2o
    <-> . +3_s_hydroxy_tetracosa_12_15_18_21_all_cis_tetrae
    2e_9z_12z_15z_18z_tetracosapentaenoyl_coa
  }

  branch from 10z_heptadecenoyl_coa side left {
    10z_heptadecenoyl_coa
    <-> . +nadp +h2o +h +o2 +nadph
    heptadecanoyl_coa
  }

  branch from 10z_heptadecenoyl_coa side right {
    10z_heptadecenoyl_coa
    <-> . +r_carnitine +coa
    heptadecenoylcarnitine_7
  }

  branch from atp side left {
    atp
    <-> ec_3_6_3_36 [3.6.3.36] +h +adp +phosphate +h2o
    taurine
  }

  branch from atp side right {
    atp
    <-> . +h +adp +phosphate +h2o
    taurocholate
  }
}
