# Ingested from Rhea. The spine follows the carbon skeleton from
# UTP to H(+); everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway utp-to-h "UTP to H" {
  spacing 248

  spine at 0,0 {
    utp
    <-> ec_2_7_1_48 [2.7.1.48] +uridine -ump -h
    udp
    <-> . +ump +phosphate -alpha_d_ribose_1_5_bisphosphate
    uracil
    <-> ec_4_1_1_66 [4.1.1.66] +co2 -h
    uracil_5_carboxylate
  }

  branch from udp side left {
    udp
    <-> . +fluvstatin_glucuronide +fluvastatin
    udp_alpha_d_glucuronate
  }

  branch from udp side right {
    udp
    <-> . +des_isopropyl_dihydro_fluvastatin_tetranor_glucu +udp_alpha_d_glucuronate
    des_isopropyl_dihydro_fluvastatin_tetranor
  }

  branch from h side left {
    h
    <-> . +adp +12s_hht +phosphate +12s_hht +h2o
    atp
  }

  branch from h side right {
    h
    <-> . +adp +phosphate +atp +h2o
    cholestane_3_7_12_24_25_pentol
  }

  branch from uracil side left {
    uracil
    <-> ec_1_3_3_7 [1.3.3.7] +h2o2 +o2
    5_6_dihydrouracil
  }

  branch from uracil side right {
    uracil
    <-> ec_2_5_1_53 [2.5.1.53] +o_acetyl_l_serine +h +3_uracil_1_yl_l_alanine
    acetate
  }

  branch from alpha_d_ribose_1_5_bisphosphate side left {
    alpha_d_ribose_1_5_bisphosphate
    <-> . +alpha_d_ribose_5_phosphate +atp +h
    adp
  }

  branch from uracil_5_carboxylate side right {
    uracil_5_carboxylate
    <-> ec_1_14_11_6 [1.14.11.6] +2_oxoglutarate +5_formyluracil +o2 +co2 +h
    succinate
  }
}
