# Ingested from Rhea. The spine follows the carbon skeleton from
# (Z)-(indol-3-yl)-N-(sulfonatooxy)methanimidothioate to H2O; everything entering or leaving at the
# side is a cofactor on that step. Generated by tools/ingest/build-modules.mjs —
# edit the generator, not this file.

pathway z-indol-3-yl-n-sulfo-to-h2o "(Z)-(indol-3-yl)-N-(sulfo… to H2O" {
  spacing 250

  spine at 0,0 {
    z_indol_3_yl_n_sulfonatooxy_methanimidothioate
    <-> . -sulfur_atom -sulfate
    indole_3_acetonitrile
    <-> ec_3_5_5_1 [3.5.5.1] +h2o -nh3
    indole_3_acetate
    <-> ec_1_14_13_235 [1.14.13.235] +nadh +o2 +hplus -nad -h2o
    2_hydroxy_indol_3_yl_acetate
    <-> . +nadh +h +o2 -nad -h2o
    1h_indole_3_acetic_acid_2_3_dihydro_3_hydroxy_2
  }

  branch from indole_3_acetonitrile side left {
    indole_3_acetonitrile
    <-> . +h2o
    indole_3_acetamide
  }

  branch from sulfur_atom side right {
    sulfur_atom
    <-> ec_1_13_11_18 [1.13.11.18] +o2 +h2o +h
    sulfite
  }

  branch from sulfur_atom side left {
    sulfur_atom
    <-> . +h +sulfite
    thiosulfate
  }

  branch from indole_3_acetate side right {
    indole_3_acetate
    <-> . +akg +o2 +succinate +co2
    2_oxindole_3_acetate
  }

  branch from nh3 side left {
    nh3
    <-> . +agmatinium +o2 +h2o +h2o2
    2r_2_hydroxypyrrolidine_1_carboximidamide
  }

  branch from nh3 side right {
    nh3
    <-> ec_2_6_1_123 [2.6.1.123] +chorismate +glutamine +h2o +glutamate
    4_amino_4_deoxychorismate
  }

  branch from 1h_indole_3_acetic_acid_2_3_dihydro_3_hydroxy_2 side left {
    1h_indole_3_acetic_acid_2_3_dihydro_3_hydroxy_2
    <-> . +h +o2
    indol_3_yl_acetate
  }

  branch from nad side right {
    nad
    <-> ec_1_1_1_306 [1.1.1.306] +nadh +s_formylmycothiol +h +mycothiol
    formaldehyde
  }

  branch from nad side left {
    nad
    <-> ec_1_14_99_31 [1.14.99.31] +nadh +tetradecanoyl_coa +h +o2 +h2o
    trans_tetradec_11_enoyl_coa
  }

  branch from h2o side right {
    h2o
    <-> ec_3_1_4_43 [3.1.4.43] +1d_myo_inositol_1_phosphate +h
    1d_myo_inositol_1_2_cyclic_phosphate
  }

  branch from h2o side left {
    h2o
    <-> ec_4_1_2_34 [4.1.2.34] +2_formylbenzoate +h +pyruvate
    trans_2_carboxybenzylidenepyruvic_acid
  }
}
